### ISSUE TITLE
Amazon drive: "Couldn't move: object not found"

### ISSUE THREAD

**Issue by mathieucarbou** [rclone/rclone#1587]
When using rclone v1.37, I have an error like this when a file has changed:

`2017/08/07 11:57:25 ERROR : System/rclone/nas-sync.sh: Couldn't move: object not found`

I do not have this issue when using:

```
rclone v1.37-067-gee13ea74β
- os/arch: linux/amd64
- go version: go1.8.3
```

**Comment by ncw** [comment]
Can you give an example of the problem this is causing along with a log with `-vv` please?

**Comment by mathieucarbou** [comment]
Also, I have a lot of errors like this one

```
2017/08/09 08:20:35 ERROR : Photography/Pictures/mathieu/2013/2013-03-09_Glissades/jpeg-raw/_DSF0076.jpg: Couldn't move: object not found
2017/08/09 08:20:35 ERROR : Photography/Pictures/mathieu/2013/2013-03-09_Glissades/jpeg-raw/_DSF0076.jpg: Couldn't move into backup dir: object not found
```

**Comment by mathieucarbou** [comment]
@ncw : yes of course! Here is a GIST of the logs for example:

https://gist.github.com/mathieucarbou/72db7f5e0f31da8b18eea100aeca01d7

The command and inclusions/exclusions  are the same as in issue #1586.

It does not happen always. It is quite random. And occurs when some files have to be moved to the backup dir (replace or delete).

**Comment by ncw** [comment]
And do you see the errors with [the latest beta](https://beta.rclone.org)?

**Comment by mathieucarbou** [comment]
I'll try it for a few days and let you know. thanks!

**Comment by mathieucarbou** [comment]
Hi,
I did a test.
Logs: https://gist.github.com/mathieucarbou/6fda402cfedb93c0ccba9393d8cfaaa8
So this is working fine, removed folders are moved to backup dir also.

**Comment by ncw** [comment]
> I see twice the output for the symlink (this is like the program runs twice internally)

It did run twice to fix the error in point 2 - see the log message

    2017/08/10 11:35:31 ERROR : Attempt 1/5 failed with 1 errors and: object not found

> I still have this error, which is reported also in the log (`Errors: 1) but when the program run again internally, the file is copied

It looks like there was some kind of error in the first retry, but in the second it was fixed.

Cloud storage systems aren't 100% reliable which is why rclone does retries like that.  Amazon drive is particularly unreliable in my experience!  rclone will get there in the end though.

I'm not sure what causes that error - can you make me a log with `-vv` please and I'll investigate further?

**Comment by mathieucarbou** [comment]
It will require some effort because it does not happen always and considering the amount of files I am syncing, `-vv` would produce too many logs... So I would need to try to isolate to a folder with less content and try to get this error again.

**Comment by mathieucarbou** [comment]
Hi,

The task run this night and it works and even if I still have some failures at the first run, they are "fixed" in a second attempt. Here is an extract of the logs:

```
[~] # cd /share/System/logs/
[/share/System/logs] # cat NAS.2017-08-11T06h30m00Z.log | grep " ERROR "
2017/08/11 02:30:32 ERROR : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4561.xmp: Couldn't move: object not found
2017/08/11 02:30:32 ERROR : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4582.xmp: Couldn't move: object not found
2017/08/11 02:30:32 ERROR : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4614.xmp: Couldn't move: object not found
2017/08/11 02:30:32 ERROR : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4570.xmp: Couldn't move: object not found
2017/08/11 02:30:32 ERROR : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4621.xmp: Couldn't move: object not found
2017/08/11 02:31:06 ERROR : Photography/Pictures/mathieu/Shooting/Amandine & Chris/2015-03-28 Photos Famille/_DSC0765.xmp: Couldn't move: object not found
2017/08/11 02:31:58 ERROR : Photography/Pictures/mathieu/Places/Charlevoix/2013-06-22/_DSF0188.xmp: Couldn't move: object not found
2017/08/11 02:31:58 ERROR : Photography/Pictures/mathieu/Places/Carcassonne/2015-12-23 Cite/_DSC4973.xmp: Couldn't move: object not found
2017/08/11 02:32:33 ERROR : Photography/Pictures/mathieu/Shooting/Marie & Olivier/2015-05-31 Grossesse/_DSC2910.xmp: Couldn't move: object not found
2017/08/11 02:32:34 ERROR : Photography/Pictures/mathieu/Shooting/Marie & Olivier/2015-05-31 Grossesse/_DSC2955.xmp: Couldn't move: object not found
2017/08/11 02:34:21 ERROR : Photography/Pictures/mathieu/Places/Owls Head/2015-10-11 Automne/_DSC4311.xmp: Couldn't move: object not found
2017/08/11 02:35:02 ERROR : Photography/Pictures/mathieu/Places/Quebec City/2015-10-18/_DSC4360.xmp: Couldn't move: object not found
2017/08/11 02:39:02 ERROR : amazon drive root 'NAS': not deleting files as there were IO errors
2017/08/11 02:39:02 ERROR : amazon drive root 'NAS': not deleting directories as there were IO errors
2017/08/11 02:39:02 ERROR : Attempt 1/10 failed with 12 errors and: object not found
2017/08/11 02:47:59 ERROR : Attempt 2/10 succeeded
[/share/System/logs] # cat NAS.2017-08-11T06h30m00Z.log | grep /_DSC4561.xmp
2017/08/11 02:30:14 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4561.xmp: Sizes differ
2017/08/11 02:30:17 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4561.xmp: Wait for directory listing to update after move 1/10
2017/08/11 02:30:18 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4561.xmp: Wait for directory listing to update after move 2/10
2017/08/11 02:30:19 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4561.xmp: Wait for directory listing to update after move 3/10
2017/08/11 02:30:21 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4561.xmp: Wait for directory listing to update after move 4/10
2017/08/11 02:30:24 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4561.xmp: Wait for directory listing to update after move 5/10
2017/08/11 02:30:25 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4561.xmp: Wait for directory listing to update after move 6/10
2017/08/11 02:30:27 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4561.xmp: Wait for directory listing to update after move 7/10
2017/08/11 02:30:28 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4561.xmp: Wait for directory listing to update after move 8/10
2017/08/11 02:30:29 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4561.xmp: Wait for directory listing to update after move 9/10
2017/08/11 02:30:31 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4561.xmp: Wait for directory listing to update after move 10/10
2017/08/11 02:30:32 ERROR : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4561.xmp: Couldn't move: object not found
2017/08/11 02:39:16 INFO  : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4561.xmp: Copied (new)
[/share/System/logs] # cat NAS.2017-08-11T06h30m00Z.log | grep _DSC4582.xmp
2017/08/11 02:30:14 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4582.xmp: Sizes differ
2017/08/11 02:30:17 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4582.xmp: Wait for directory listing to update after move 1/10
2017/08/11 02:30:18 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4582.xmp: Wait for directory listing to update after move 2/10
2017/08/11 02:30:19 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4582.xmp: Wait for directory listing to update after move 3/10
2017/08/11 02:30:21 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4582.xmp: Wait for directory listing to update after move 4/10
2017/08/11 02:30:24 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4582.xmp: Wait for directory listing to update after move 5/10
2017/08/11 02:30:25 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4582.xmp: Wait for directory listing to update after move 6/10
2017/08/11 02:30:27 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4582.xmp: Wait for directory listing to update after move 7/10
2017/08/11 02:30:28 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4582.xmp: Wait for directory listing to update after move 8/10
2017/08/11 02:30:29 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4582.xmp: Wait for directory listing to update after move 9/10
2017/08/11 02:30:31 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4582.xmp: Wait for directory listing to update after move 10/10
2017/08/11 02:30:32 ERROR : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4582.xmp: Couldn't move: object not found
2017/08/11 02:39:17 INFO  : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4582.xmp: Copied (new)
[/share/System/logs] # cat NAS.2017-08-11T06h30m00Z.log | grep _DSC4614.xmp
2017/08/11 02:30:14 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4614.xmp: Sizes differ
2017/08/11 02:30:17 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4614.xmp: Wait for directory listing to update after move 1/10
2017/08/11 02:30:18 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4614.xmp: Wait for directory listing to update after move 2/10
2017/08/11 02:30:19 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4614.xmp: Wait for directory listing to update after move 3/10
2017/08/11 02:30:21 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4614.xmp: Wait for directory listing to update after move 4/10
2017/08/11 02:30:24 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4614.xmp: Wait for directory listing to update after move 5/10
2017/08/11 02:30:25 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4614.xmp: Wait for directory listing to update after move 6/10
2017/08/11 02:30:27 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4614.xmp: Wait for directory listing to update after move 7/10
2017/08/11 02:30:28 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4614.xmp: Wait for directory listing to update after move 8/10
2017/08/11 02:30:29 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4614.xmp: Wait for directory listing to update after move 9/10
2017/08/11 02:30:31 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4614.xmp: Wait for directory listing to update after move 10/10
2017/08/11 02:30:32 ERROR : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4614.xmp: Couldn't move: object not found
2017/08/11 02:39:17 INFO  : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4614.xmp: Copied (new)
[/share/System/logs] # cat NAS.2017-08-11T06h30m00Z.log | grep _DSC4360.xmp
2017/08/11 02:34:46 DEBUG : Photography/Pictures/mathieu/Places/Quebec City/2015-10-18/_DSC4360.xmp: Sizes differ
2017/08/11 02:34:48 DEBUG : Photography/Pictures/mathieu/Places/Quebec City/2015-10-18/_DSC4360.xmp: Wait for directory listing to update after move 1/10
2017/08/11 02:34:49 DEBUG : Photography/Pictures/mathieu/Places/Quebec City/2015-10-18/_DSC4360.xmp: Wait for directory listing to update after move 2/10
2017/08/11 02:34:50 DEBUG : Photography/Pictures/mathieu/Places/Quebec City/2015-10-18/_DSC4360.xmp: Wait for directory listing to update after move 3/10
2017/08/11 02:34:52 DEBUG : Photography/Pictures/mathieu/Places/Quebec City/2015-10-18/_DSC4360.xmp: Wait for directory listing to update after move 4/10
2017/08/11 02:34:53 DEBUG : Photography/Pictures/mathieu/Places/Quebec City/2015-10-18/_DSC4360.xmp: Wait for directory listing to update after move 5/10
2017/08/11 02:34:54 DEBUG : Photography/Pictures/mathieu/Places/Quebec City/2015-10-18/_DSC4360.xmp: Wait for directory listing to update after move 6/10
2017/08/11 02:34:56 DEBUG : Photography/Pictures/mathieu/Places/Quebec City/2015-10-18/_DSC4360.xmp: Wait for directory listing to update after move 7/10
2017/08/11 02:34:58 DEBUG : Photography/Pictures/mathieu/Places/Quebec City/2015-10-18/_DSC4360.xmp: Wait for directory listing to update after move 8/10
2017/08/11 02:34:59 DEBUG : Photography/Pictures/mathieu/Places/Quebec City/2015-10-18/_DSC4360.xmp: Wait for directory listing to update after move 9/10
 * Photography/Pictures/mathieu/Places/Quebec City/2015-10-18/_DSC4360.xmp
2017/08/11 02:35:01 DEBUG : Photography/Pictures/mathieu/Places/Quebec City/2015-10-18/_DSC4360.xmp: Wait for directory listing to update after move 10/10
2017/08/11 02:35:02 ERROR : Photography/Pictures/mathieu/Places/Quebec City/2015-10-18/_DSC4360.xmp: Couldn't move: object not found
2017/08/11 02:43:42 INFO  : Photography/Pictures/mathieu/Places/Quebec City/2015-10-18/_DSC4360.xmp: Copied (new)
[/share/System/logs] #
```

**Comment by mathieucarbou** [comment]
I have successfully verified that the file has been moved to the backup dir, and then, in the second run, it gets copied.

**Comment by ncw** [comment]
Ah, very useful log, thanks.  These are the problem lines

```
2017/08/11 02:30:17 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4561.xmp: Wait for directory listing to update after move 1/10
2017/08/11 02:30:18 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4561.xmp: Wait for directory listing to update after move 2/10
2017/08/11 02:30:19 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4561.xmp: Wait for directory listing to update after move 3/10
2017/08/11 02:30:21 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4561.xmp: Wait for directory listing to update after move 4/10
2017/08/11 02:30:24 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4561.xmp: Wait for directory listing to update after move 5/10
2017/08/11 02:30:25 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4561.xmp: Wait for directory listing to update after move 6/10
2017/08/11 02:30:27 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4561.xmp: Wait for directory listing to update after move 7/10
2017/08/11 02:30:28 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4561.xmp: Wait for directory listing to update after move 8/10
2017/08/11 02:30:29 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4561.xmp: Wait for directory listing to update after move 9/10
2017/08/11 02:30:31 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4561.xmp: Wait for directory listing to update after move 10/10
2017/08/11 02:30:32 ERROR : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4561.xmp: Couldn't move: object not found
```

Looking at [the code](https://github.com/ncw/rclone/blob/master/amazonclouddrive/amazonclouddrive.go#L648) I see that rclone is waiting for the object to appear in its new place after the move.  ACD has terrible eventual consistency which means that sometimes those things take ages!  The move went through just fine though.

If you increase `--low-level-retries` from its default of 10 that will help.  Can you try that to find a level where it always works, then I can tweak the retry logic a bit?

This was put in here e9da14ac2ed024ff06570a8d3926fc711f11e854 then updated in 381b8453070d4c9d6ada204eae6efd72cc65971d

**Comment by mathieucarbou** [comment]
OK! I'll try and let you know. Thank you!

**Comment by mathieucarbou** [comment]
So the task is running for several hours now, I have 100Mo of logs. If  I extract some of them, I still have the same errors and the `--low-level-retries` does not seem to change the number of retries.

Logs:

```
[/share/System/logs] # cat NAS.2017-08-11T06h30m00Z.log | grep " ERROR "
2017/08/11 02:30:32 ERROR : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4561.xmp: Couldn't move: object not found
2017/08/11 02:30:32 ERROR : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4582.xmp: Couldn't move: object not found
2017/08/11 02:30:32 ERROR : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4614.xmp: Couldn't move: object not found
2017/08/11 02:30:32 ERROR : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4570.xmp: Couldn't move: object not found
2017/08/11 02:30:32 ERROR : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4621.xmp: Couldn't move: object not found
2017/08/11 02:31:06 ERROR : Photography/Pictures/mathieu/Shooting/Amandine & Chris/2015-03-28 Photos Famille/_DSC0765.xmp: Couldn't move: object not found
2017/08/11 02:31:58 ERROR : Photography/Pictures/mathieu/Places/Charlevoix/2013-06-22/_DSF0188.xmp: Couldn't move: object not found
2017/08/11 02:31:58 ERROR : Photography/Pictures/mathieu/Places/Carcassonne/2015-12-23 Cite/_DSC4973.xmp: Couldn't move: object not found
2017/08/11 02:32:33 ERROR : Photography/Pictures/mathieu/Shooting/Marie & Olivier/2015-05-31 Grossesse/_DSC2910.xmp: Couldn't move: object not found
2017/08/11 02:32:34 ERROR : Photography/Pictures/mathieu/Shooting/Marie & Olivier/2015-05-31 Grossesse/_DSC2955.xmp: Couldn't move: object not found
2017/08/11 02:34:21 ERROR : Photography/Pictures/mathieu/Places/Owls Head/2015-10-11 Automne/_DSC4311.xmp: Couldn't move: object not found
2017/08/11 02:35:02 ERROR : Photography/Pictures/mathieu/Places/Quebec City/2015-10-18/_DSC4360.xmp: Couldn't move: object not found
2017/08/11 02:39:02 ERROR : amazon drive root 'NAS': not deleting files as there were IO errors
2017/08/11 02:39:02 ERROR : amazon drive root 'NAS': not deleting directories as there were IO errors
2017/08/11 02:39:02 ERROR : Attempt 1/10 failed with 12 errors and: object not found
2017/08/11 02:47:59 ERROR : Attempt 2/10 succeeded
[/share/System/logs] # cat NAS.2017-08-11T06h30m00Z.log | grep _DSC4621.xmp
2017/08/11 02:30:14 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4621.xmp: Sizes differ
2017/08/11 02:30:17 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4621.xmp: Wait for directory listing to update after move 1/10
2017/08/11 02:30:18 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4621.xmp: Wait for directory listing to update after move 2/10
2017/08/11 02:30:20 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4621.xmp: Wait for directory listing to update after move 3/10
2017/08/11 02:30:21 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4621.xmp: Wait for directory listing to update after move 4/10
2017/08/11 02:30:24 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4621.xmp: Wait for directory listing to update after move 5/10
2017/08/11 02:30:26 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4621.xmp: Wait for directory listing to update after move 6/10
2017/08/11 02:30:27 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4621.xmp: Wait for directory listing to update after move 7/10
2017/08/11 02:30:28 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4621.xmp: Wait for directory listing to update after move 8/10
2017/08/11 02:30:30 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4621.xmp: Wait for directory listing to update after move 9/10
2017/08/11 02:30:31 DEBUG : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4621.xmp: Wait for directory listing to update after move 10/10
2017/08/11 02:30:32 ERROR : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4621.xmp: Couldn't move: object not found
2017/08/11 02:39:18 INFO  : Photography/Pictures/mathieu/Commercial/Anne-Marie Tremblay/2015-11-15 Ceramique/_DSC4621.xmp: Copied (new)
[/share/System/logs] # cat NAS.2017-08-11T06h30m00Z.log | grep _DSC4360.xmp
2017/08/11 02:34:46 DEBUG : Photography/Pictures/mathieu/Places/Quebec City/2015-10-18/_DSC4360.xmp: Sizes differ
2017/08/11 02:34:48 DEBUG : Photography/Pictures/mathieu/Places/Quebec City/2015-10-18/_DSC4360.xmp: Wait for directory listing to update after move 1/10
2017/08/11 02:34:49 DEBUG : Photography/Pictures/mathieu/Places/Quebec City/2015-10-18/_DSC4360.xmp: Wait for directory listing to update after move 2/10
2017/08/11 02:34:50 DEBUG : Photography/Pictures/mathieu/Places/Quebec City/2015-10-18/_DSC4360.xmp: Wait for directory listing to update after move 3/10
2017/08/11 02:34:52 DEBUG : Photography/Pictures/mathieu/Places/Quebec City/2015-10-18/_DSC4360.xmp: Wait for directory listing to update after move 4/10
2017/08/11 02:34:53 DEBUG : Photography/Pictures/mathieu/Places/Quebec City/2015-10-18/_DSC4360.xmp: Wait for directory listing to update after move 5/10
2017/08/11 02:34:54 DEBUG : Photography/Pictures/mathieu/Places/Quebec City/2015-10-18/_DSC4360.xmp: Wait for directory listing to update after move 6/10
2017/08/11 02:34:56 DEBUG : Photography/Pictures/mathieu/Places/Quebec City/2015-10-18/_DSC4360.xmp: Wait for directory listing to update after move 7/10
2017/08/11 02:34:58 DEBUG : Photography/Pictures/mathieu/Places/Quebec City/2015-10-18/_DSC4360.xmp: Wait for directory listing to update after move 8/10
2017/08/11 02:34:59 DEBUG : Photography/Pictures/mathieu/Places/Quebec City/2015-10-18/_DSC4360.xmp: Wait for directory listing to update after move 9/10
 * Photography/Pictures/mathieu/Places/Quebec City/2015-10-18/_DSC4360.xmp
2017/08/11 02:35:01 DEBUG : Photography/Pictures/mathieu/Places/Quebec City/2015-10-18/_DSC4360.xmp: Wait for directory listing to update after move 10/10
2017/08/11 02:35:02 ERROR : Photography/Pictures/mathieu/Places/Quebec City/2015-10-18/_DSC4360.xmp: Couldn't move: object not found
2017/08/11 02:43:42 INFO  : Photography/Pictures/mathieu/Places/Quebec City/2015-10-18/_DSC4360.xmp: Copied (new)
[/share/System/logs] #
```

Command:

```
"$RCLONE" sync "$SOURCE" "$REMOTE:/$BUCKET" \
    --log-level "DEBUG" \
    --retries 10 \
    --transfers 2 \
    --delete-excluded \
    --backup-dir "$REMOTE:/Backups/$BUCKET/$DT" \
    --config "$CONFIG" \
    --dump-filters \
    --low-level-retries 30 \
    --checksum \
    --filter-from "$FILTERS" $* 2>&1 | tee -a "$LOGFILE"
```

**Comment by mathieucarbou** [comment]
Hi, the task finished with `--checksum`: 330Mo of logs and more than 1,163,483 files in 13 hours. I think a more efficient way for comparison (#1593) would be really helpfull !

I also had several errors like this one:

```
[/share/System/logs] # cat NAS.2017-08-11T22h40m11Z.log | grep _DSC3025.xmp
2017/08/11 19:14:22 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: MD5 = fa493fd0b3f3791710bb00ca80071980 (Local file system at /share/CE_CACHEDEV1_DATA)
2017/08/11 19:14:22 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: MD5 = 06f83dcc96dffd78416b48845275955a (amazon drive root 'NAS')
2017/08/11 19:14:22 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: MD5 differ
2017/08/11 19:14:23 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Wait for directory listing to update after move 1/30
2017/08/11 19:14:24 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Wait for directory listing to update after move 2/30
2017/08/11 19:14:25 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Wait for directory listing to update after move 3/30
2017/08/11 19:14:26 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Wait for directory listing to update after move 4/30
2017/08/11 19:14:28 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Wait for directory listing to update after move 5/30
2017/08/11 19:14:29 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Wait for directory listing to update after move 6/30
2017/08/11 19:14:30 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Wait for directory listing to update after move 7/30
2017/08/11 19:14:31 INFO  : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Moved (server side)
2017/08/11 19:14:48 INFO  : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Copied (new)
2017/08/11 20:37:00 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Error detected after finished upload - waiting to see if object was uploaded correctly: HTTP code 409: "409 Conflict": response body: "{\"logref\":\"5b5aef11-7ef6-11e7-95f4-69286e16b225\",\"message\":\"Node with the name _dsc3025.xmp already exists under parentId xvIix0ZITvaEje9IAJDzSQ conflicting NodeId: 0471vdN0S1GsaWa6slYIuA\",\"code\":\"NAME_ALREADY_EXISTS\",\"info\":{\"nodeId\":\"0471vdN0S1GsaWa6slYIuA\"}}" ("409 Conflict")
2017/08/11 20:37:00 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Object not found - waiting (1/1)
2017/08/11 20:37:05 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Giving up waiting for object - returning original error: HTTP code 409: "409 Conflict": response body: "{\"logref\":\"5b5aef11-7ef6-11e7-95f4-69286e16b225\",\"message\":\"Node with the name _dsc3025.xmp already exists under parentId xvIix0ZITvaEje9IAJDzSQ conflicting NodeId: 0471vdN0S1GsaWa6slYIuA\",\"code\":\"NAME_ALREADY_EXISTS\",\"info\":{\"nodeId\":\"0471vdN0S1GsaWa6slYIuA\"}}" ("409 Conflict")
2017/08/11 20:37:05 ERROR : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Failed to copy: HTTP code 409: "409 Conflict": response body: "{\"logref\":\"5b5aef11-7ef6-11e7-95f4-69286e16b225\",\"message\":\"Node with the name _dsc3025.xmp already exists under parentId xvIix0ZITvaEje9IAJDzSQ conflicting NodeId: 0471vdN0S1GsaWa6slYIuA\",\"code\":\"NAME_ALREADY_EXISTS\",\"info\":{\"nodeId\":\"0471vdN0S1GsaWa6slYIuA\"}}"
2017/08/11 21:51:51 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Error detected after finished upload - waiting to see if object was uploaded correctly: HTTP code 409: "409 Conflict": response body: "{\"logref\":\"d037bab7-7f00-11e7-bf7f-47a1f5911187\",\"message\":\"Node with the name _dsc3025.xmp already exists under parentId xvIix0ZITvaEje9IAJDzSQ conflicting NodeId: 0471vdN0S1GsaWa6slYIuA\",\"code\":\"NAME_ALREADY_EXISTS\",\"info\":{\"nodeId\":\"0471vdN0S1GsaWa6slYIuA\"}}" ("409 Conflict")
2017/08/11 21:51:51 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Object not found - waiting (1/1)
2017/08/11 21:51:56 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Giving up waiting for object - returning original error: HTTP code 409: "409 Conflict": response body: "{\"logref\":\"d037bab7-7f00-11e7-bf7f-47a1f5911187\",\"message\":\"Node with the name _dsc3025.xmp already exists under parentId xvIix0ZITvaEje9IAJDzSQ conflicting NodeId: 0471vdN0S1GsaWa6slYIuA\",\"code\":\"NAME_ALREADY_EXISTS\",\"info\":{\"nodeId\":\"0471vdN0S1GsaWa6slYIuA\"}}" ("409 Conflict")
2017/08/11 21:51:56 ERROR : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Failed to copy: HTTP code 409: "409 Conflict": response body: "{\"logref\":\"d037bab7-7f00-11e7-bf7f-47a1f5911187\",\"message\":\"Node with the name _dsc3025.xmp already exists under parentId xvIix0ZITvaEje9IAJDzSQ conflicting NodeId: 0471vdN0S1GsaWa6slYIuA\",\"code\":\"NAME_ALREADY_EXISTS\",\"info\":{\"nodeId\":\"0471vdN0S1GsaWa6slYIuA\"}}"
2017/08/11 23:05:15 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Error detected after finished upload - waiting to see if object was uploaded correctly: HTTP code 409: "409 Conflict": response body: "{\"logref\":\"117ecddd-7f0b-11e7-8a6c-1ff5135c7181\",\"message\":\"Node with the name _dsc3025.xmp already exists under parentId xvIix0ZITvaEje9IAJDzSQ conflicting NodeId: 0471vdN0S1GsaWa6slYIuA\",\"code\":\"NAME_ALREADY_EXISTS\",\"info\":{\"nodeId\":\"0471vdN0S1GsaWa6slYIuA\"}}" ("409 Conflict")
2017/08/11 23:05:16 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Object not found - waiting (1/1)
2017/08/11 23:05:21 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Giving up waiting for object - returning original error: HTTP code 409: "409 Conflict": response body: "{\"logref\":\"117ecddd-7f0b-11e7-8a6c-1ff5135c7181\",\"message\":\"Node with the name _dsc3025.xmp already exists under parentId xvIix0ZITvaEje9IAJDzSQ conflicting NodeId: 0471vdN0S1GsaWa6slYIuA\",\"code\":\"NAME_ALREADY_EXISTS\",\"info\":{\"nodeId\":\"0471vdN0S1GsaWa6slYIuA\"}}" ("409 Conflict")
2017/08/11 23:05:21 ERROR : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Failed to copy: HTTP code 409: "409 Conflict": response body: "{\"logref\":\"117ecddd-7f0b-11e7-8a6c-1ff5135c7181\",\"message\":\"Node with the name _dsc3025.xmp already exists under parentId xvIix0ZITvaEje9IAJDzSQ conflicting NodeId: 0471vdN0S1GsaWa6slYIuA\",\"code\":\"NAME_ALREADY_EXISTS\",\"info\":{\"nodeId\":\"0471vdN0S1GsaWa6slYIuA\"}}"
2017/08/12 00:22:15 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Error detected after finished upload - waiting to see if object was uploaded correctly: HTTP code 409: "409 Conflict": response body: "{\"logref\":\"d2e6ef5f-7f15-11e7-a7b7-63a97c8ae7fb\",\"message\":\"Node with the name _dsc3025.xmp already exists under parentId xvIix0ZITvaEje9IAJDzSQ conflicting NodeId: 0471vdN0S1GsaWa6slYIuA\",\"code\":\"NAME_ALREADY_EXISTS\",\"info\":{\"nodeId\":\"0471vdN0S1GsaWa6slYIuA\"}}" ("409 Conflict")
2017/08/12 00:22:15 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Object not found - waiting (1/1)
2017/08/12 00:22:20 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Giving up waiting for object - returning original error: HTTP code 409: "409 Conflict": response body: "{\"logref\":\"d2e6ef5f-7f15-11e7-a7b7-63a97c8ae7fb\",\"message\":\"Node with the name _dsc3025.xmp already exists under parentId xvIix0ZITvaEje9IAJDzSQ conflicting NodeId: 0471vdN0S1GsaWa6slYIuA\",\"code\":\"NAME_ALREADY_EXISTS\",\"info\":{\"nodeId\":\"0471vdN0S1GsaWa6slYIuA\"}}" ("409 Conflict")
2017/08/12 00:22:20 ERROR : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Failed to copy: HTTP code 409: "409 Conflict": response body: "{\"logref\":\"d2e6ef5f-7f15-11e7-a7b7-63a97c8ae7fb\",\"message\":\"Node with the name _dsc3025.xmp already exists under parentId xvIix0ZITvaEje9IAJDzSQ conflicting NodeId: 0471vdN0S1GsaWa6slYIuA\",\"code\":\"NAME_ALREADY_EXISTS\",\"info\":{\"nodeId\":\"0471vdN0S1GsaWa6slYIuA\"}}"
2017/08/12 01:37:07 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Error detected after finished upload - waiting to see if object was uploaded correctly: HTTP code 409: "409 Conflict": response body: "{\"logref\":\"4873f7c3-7f20-11e7-b3bc-9b82a8ba39f9\",\"message\":\"Node with the name _dsc3025.xmp already exists under parentId xvIix0ZITvaEje9IAJDzSQ conflicting NodeId: 0471vdN0S1GsaWa6slYIuA\",\"code\":\"NAME_ALREADY_EXISTS\",\"info\":{\"nodeId\":\"0471vdN0S1GsaWa6slYIuA\"}}" ("409 Conflict")
2017/08/12 01:37:07 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Object not found - waiting (1/1)
 * ...ence Vie/2015-06-16 Longueuil/_DSC3025.xmp: 100% done, 8.079 kBytes/s, ETA: 0s
2017/08/12 01:37:12 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Giving up waiting for object - returning original error: HTTP code 409: "409 Conflict": response body: "{\"logref\":\"4873f7c3-7f20-11e7-b3bc-9b82a8ba39f9\",\"message\":\"Node with the name _dsc3025.xmp already exists under parentId xvIix0ZITvaEje9IAJDzSQ conflicting NodeId: 0471vdN0S1GsaWa6slYIuA\",\"code\":\"NAME_ALREADY_EXISTS\",\"info\":{\"nodeId\":\"0471vdN0S1GsaWa6slYIuA\"}}" ("409 Conflict")
2017/08/12 01:37:12 ERROR : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Failed to copy: HTTP code 409: "409 Conflict": response body: "{\"logref\":\"4873f7c3-7f20-11e7-b3bc-9b82a8ba39f9\",\"message\":\"Node with the name _dsc3025.xmp already exists under parentId xvIix0ZITvaEje9IAJDzSQ conflicting NodeId: 0471vdN0S1GsaWa6slYIuA\",\"code\":\"NAME_ALREADY_EXISTS\",\"info\":{\"nodeId\":\"0471vdN0S1GsaWa6slYIuA\"}}"
2017/08/12 03:02:36 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Error detected after finished upload - waiting to see if object was uploaded correctly: HTTP code 409: "409 Conflict": response body: "{\"logref\":\"39594707-7f2c-11e7-a7b7-63a97c8ae7fb\",\"message\":\"Node with the name _dsc3025.xmp already exists under parentId xvIix0ZITvaEje9IAJDzSQ conflicting NodeId: 0471vdN0S1GsaWa6slYIuA\",\"code\":\"NAME_ALREADY_EXISTS\",\"info\":{\"nodeId\":\"0471vdN0S1GsaWa6slYIuA\"}}" ("409 Conflict")
2017/08/12 03:02:36 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Object not found - waiting (1/1)
2017/08/12 03:02:41 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Giving up waiting for object - returning original error: HTTP code 409: "409 Conflict": response body: "{\"logref\":\"39594707-7f2c-11e7-a7b7-63a97c8ae7fb\",\"message\":\"Node with the name _dsc3025.xmp already exists under parentId xvIix0ZITvaEje9IAJDzSQ conflicting NodeId: 0471vdN0S1GsaWa6slYIuA\",\"code\":\"NAME_ALREADY_EXISTS\",\"info\":{\"nodeId\":\"0471vdN0S1GsaWa6slYIuA\"}}" ("409 Conflict")
2017/08/12 03:02:41 ERROR : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Failed to copy: HTTP code 409: "409 Conflict": response body: "{\"logref\":\"39594707-7f2c-11e7-a7b7-63a97c8ae7fb\",\"message\":\"Node with the name _dsc3025.xmp already exists under parentId xvIix0ZITvaEje9IAJDzSQ conflicting NodeId: 0471vdN0S1GsaWa6slYIuA\",\"code\":\"NAME_ALREADY_EXISTS\",\"info\":{\"nodeId\":\"0471vdN0S1GsaWa6slYIuA\"}}"
2017/08/12 04:21:21 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Error detected after finished upload - waiting to see if object was uploaded correctly: HTTP code 409: "409 Conflict": response body: "{\"logref\":\"39fe10da-7f37-11e7-bf2a-45e58b96af19\",\"message\":\"Node with the name _dsc3025.xmp already exists under parentId xvIix0ZITvaEje9IAJDzSQ conflicting NodeId: 0471vdN0S1GsaWa6slYIuA\",\"code\":\"NAME_ALREADY_EXISTS\",\"info\":{\"nodeId\":\"0471vdN0S1GsaWa6slYIuA\"}}" ("409 Conflict")
2017/08/12 04:21:21 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Object not found - waiting (1/1)
2017/08/12 04:21:26 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Giving up waiting for object - returning original error: HTTP code 409: "409 Conflict": response body: "{\"logref\":\"39fe10da-7f37-11e7-bf2a-45e58b96af19\",\"message\":\"Node with the name _dsc3025.xmp already exists under parentId xvIix0ZITvaEje9IAJDzSQ conflicting NodeId: 0471vdN0S1GsaWa6slYIuA\",\"code\":\"NAME_ALREADY_EXISTS\",\"info\":{\"nodeId\":\"0471vdN0S1GsaWa6slYIuA\"}}" ("409 Conflict")
2017/08/12 04:21:26 ERROR : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Failed to copy: HTTP code 409: "409 Conflict": response body: "{\"logref\":\"39fe10da-7f37-11e7-bf2a-45e58b96af19\",\"message\":\"Node with the name _dsc3025.xmp already exists under parentId xvIix0ZITvaEje9IAJDzSQ conflicting NodeId: 0471vdN0S1GsaWa6slYIuA\",\"code\":\"NAME_ALREADY_EXISTS\",\"info\":{\"nodeId\":\"0471vdN0S1GsaWa6slYIuA\"}}"
2017/08/12 05:40:45 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Error detected after finished upload - waiting to see if object was uploaded correctly: HTTP code 409: "409 Conflict": response body: "{\"logref\":\"519a1139-7f42-11e7-b8a0-17afeaec8c2e\",\"message\":\"Node with the name _dsc3025.xmp already exists under parentId xvIix0ZITvaEje9IAJDzSQ conflicting NodeId: 0471vdN0S1GsaWa6slYIuA\",\"code\":\"NAME_ALREADY_EXISTS\",\"info\":{\"nodeId\":\"0471vdN0S1GsaWa6slYIuA\"}}" ("409 Conflict")
2017/08/12 05:40:46 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Object not found - waiting (1/1)
2017/08/12 05:40:51 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Giving up waiting for object - returning original error: HTTP code 409: "409 Conflict": response body: "{\"logref\":\"519a1139-7f42-11e7-b8a0-17afeaec8c2e\",\"message\":\"Node with the name _dsc3025.xmp already exists under parentId xvIix0ZITvaEje9IAJDzSQ conflicting NodeId: 0471vdN0S1GsaWa6slYIuA\",\"code\":\"NAME_ALREADY_EXISTS\",\"info\":{\"nodeId\":\"0471vdN0S1GsaWa6slYIuA\"}}" ("409 Conflict")
2017/08/12 05:40:51 ERROR : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Failed to copy: HTTP code 409: "409 Conflict": response body: "{\"logref\":\"519a1139-7f42-11e7-b8a0-17afeaec8c2e\",\"message\":\"Node with the name _dsc3025.xmp already exists under parentId xvIix0ZITvaEje9IAJDzSQ conflicting NodeId: 0471vdN0S1GsaWa6slYIuA\",\"code\":\"NAME_ALREADY_EXISTS\",\"info\":{\"nodeId\":\"0471vdN0S1GsaWa6slYIuA\"}}"
2017/08/12 06:55:16 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Error detected after finished upload - waiting to see if object was uploaded correctly: HTTP code 409: "409 Conflict": response body: "{\"logref\":\"ba5cdf95-7f4c-11e7-b113-d509c65e524a\",\"message\":\"Node with the name _dsc3025.xmp already exists under parentId xvIix0ZITvaEje9IAJDzSQ conflicting NodeId: 0471vdN0S1GsaWa6slYIuA\",\"code\":\"NAME_ALREADY_EXISTS\",\"info\":{\"nodeId\":\"0471vdN0S1GsaWa6slYIuA\"}}" ("409 Conflict")
2017/08/12 06:55:16 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Object not found - waiting (1/1)
2017/08/12 06:55:21 DEBUG : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Giving up waiting for object - returning original error: HTTP code 409: "409 Conflict": response body: "{\"logref\":\"ba5cdf95-7f4c-11e7-b113-d509c65e524a\",\"message\":\"Node with the name _dsc3025.xmp already exists under parentId xvIix0ZITvaEje9IAJDzSQ conflicting NodeId: 0471vdN0S1GsaWa6slYIuA\",\"code\":\"NAME_ALREADY_EXISTS\",\"info\":{\"nodeId\":\"0471vdN0S1GsaWa6slYIuA\"}}" ("409 Conflict")
2017/08/12 06:55:21 ERROR : Photography/Pictures/mathieu/Commercial/Urgence Vie/2015-06-16 Longueuil/_DSC3025.xmp: Failed to copy: HTTP code 409: "409 Conflict": response body: "{\"logref\":\"ba5cdf95-7f4c-11e7-b113-d509c65e524a\",\"message\":\"Node with the name _dsc3025.xmp already exists under parentId xvIix0ZITvaEje9IAJDzSQ conflicting NodeId: 0471vdN0S1GsaWa6slYIuA\",\"code\":\"NAME_ALREADY_EXISTS\",\"info\":{\"nodeId\":\"0471vdN0S1GsaWa6slYIuA\"}}"
```

**Comment by animosity22** [comment]
Legacy ACD item and closing out.
