### ISSUE TITLE
DLNA + Samsung

### ISSUE THREAD

**Issue by ilteoood** [rclone/rclone#4346]
#### What is the problem you are having with rclone?

I've tried to use the serve dlna command, on VLC I can see every file while on my Samsung TVs I have a message like "No content found" 

#### What is your rclone version (output from `rclone version`)

1.52.0 and latest beta image version

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Rpi 2, docker, 32 bit
Rpi 1, 32 bit

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive, local

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone serve dlna -vv --log-trace GDrive:/Media/Film

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

        <SCPDURL>/static/ConnectionManager.xml<
/SCPDURL>                                      
        <controlURL>/ctl</controlURL>          
        <eventSubURL></eventSubURL>            
      </service>                               
      <service>                                
        <serviceType>urn:microsoft.com:service:
X_MS_MediaReceiverRegistrar:1</serviceType>    
        <serviceId>urn:microsoft.com:serviceId:
X_MS_MediaReceiverRegistrar</serviceId>        
        <SCPDURL>/static/X_MS_MediaReceiverRegi
strar.xml</SCPDURL>                            
        <controlURL>/ctl</controlURL>          
        <eventSubURL></eventSubURL>            
      </service>                               
    </serviceList>                             
    <presentationURL>/</presentationURL>       
  </device>                                    
</root>                                        
2020/06/13 17:06:04 INFO  : /rootDesc.xml: 192.
168.1.86:47054 GET 200                         
2020/06/13 17:06:04 INFO  : /static/X_MS_MediaR
eceiverRegistrar.xml: 192.168.1.86:47057 GET 20
0                                              
2020/06/13 17:06:04 INFO  : /static/ContentDire
ctory.xml: 192.168.1.86:47055 GET 200          
2020/06/13 17:06:04 INFO  : /static/ConnectionM
anager.xml: 192.168.1.86:47056 GET 200         
2020/06/13 17:06:04 INFO  : /static/rclone-120x
120.png: 192.168.1.86:47058 GET 200            
2020/06/13 17:06:28 DEBUG : Google drive root '
Media/Film': Checking for changes on remote    
2020/06/13 17:07:28 DEBUG : Google drive root '
Media/Film': Checking for changes on remote    
                                               
[0] 0:rclone*     "raspberrypi" 17:07 13-Jun-20

**Comment by ncw** [comment]
@sretlawd you were trying to make serve dlna work for Samsung TVs weren't you?

**Comment by sretlawd** [comment]
Yes, last I checked it’s working on mine, which is an F series (from 2013 or so.)  Not sure what model this one is?  From the log posted on the other thread, best I could tell it’s only fetching the rootDesc.xml and stopping, so there's something about that descriptor that the TV doesn’t like.  With the model info I might find something in another project.

Other than that, all I can suggest is what I did - first verify that it works with some other server like minidlna, then make guesses and change the rootDesc.xml template until it works.  I believe you can actually make a special cable (https://wiki.samygo.tv/index.php?title=Main_Page#SamyGO_DIY_Hardwares <https://wiki.samygo.tv/index.php?title=Main_Page#SamyGO_DIY_Hardwares>) and get an error message from the TV’s debug log, but it's a big project!

**Comment by ilteoood** [comment]
Hi @sretlawd,
I'm using two different models: a series 7 of which I can't remember now the precise model, and a series 6: UE43KU6400UXZT.

I've tested both with minidlna, which is my current dlna server, and I've no problem with it.

**Comment by ilteoood** [comment]
Hi all,
I've made other tests: using the version 1.50.2, the one provided by ubuntu's PPA, it works.
So, I've made some tests with the image tag 1.50.2, and it works.
After that, I tested the image tag 1, and doesn't work.
The last that was made on image tag 1.51, and it works.

I think that is a regression made from 1.51 to 1.52: @ncw  do you know something about it?

**Comment by ilteoood** [comment]
OK, I think I've found a fix.
My samsung tv don't like the absence of the childCount attribute.
I've made a patch here (https://github.com/rclone/rclone/pull/4350) using a childCount = 1, in order to avoid subfolder recursion.

I've tested it on VLC and samsung tv, and is working!

**Comment by ilteoood** [comment]
Fixed with https://github.com/rclone/rclone/pull/4350#event-3449116440

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.53

**Comment by ilteoood** [comment]
Hi @ncw ,
was this fix included in version 1.52.2?

**Comment by ncw** [comment]
I didn't put it in 1.52.2 as I wasn't sure it was fully tested.

What do you think? I could queue for the next point release.

**Comment by sretlawd** [comment]
In theory, any client that has a problem with this would also have issues if media files are added/removed from the remote between http requests - which is of course entirely possible, and only a severely broken client would have issues with that?  No way to be 100% sure with DLNA stuff, but I like it & wish I’d thought of it!  :-)  That said I’m still unable to test it myself...

**Comment by ncw** [comment]
I've put it in the queue for 1.52.3 now :-)
