### ISSUE TITLE
Add --chown Flag

### ISSUE THREAD

**Issue by fionera** [rclone/rclone#4742]
#### What is your current rclone version (output from `rclone version`)?
v1.54.0-beta.4877.cd2c06f2a

#### What problem are you are trying to solve?
Moving/Copying Files and Folders and changing the owner on the destination

#### How do you think rclone should be changed to solve that?
Add a --chown Flag which tells rclone to change it on the supporting remotes

**Comment by ivandeex** [comment]
Of all 20+ rclone backends only _local_ supports user/group ids, such flag is useless.

**Comment by fionera** [comment]
This would be a --local prefixed Flag then since it is very handy to copy data to a different folder and change the owner

**Comment by ncw** [comment]
What is your use case for this @fionera ?

Is it copying cloud -> local or local -> local?

Presumably running as root as normal users can't do `chown`?

**Comment by fionera** [comment]
I am doing both right now. Currently I am using rsync to do local -> local since it supports the feature. Else I have to call chown every time. A `chmod` could also be handy

**Comment by hoyho** [comment]
> What is your use case for this @fionera ?
> 
> Is it copying cloud -> local or local -> local?
> 
> Presumably running as root as normal users can't do `chown`?

We have similar use case: 
Migration from one NAS to another
For example, using rclone to copy data from NFS mountpint (say site1 which mounted to local  path  /foo inside a container ) to another NFS site2(mounted to local  path  /bar inside a container).
Everything looks good, the data itself and Mtime as well as hash are all the same.
However for some application don't have permission to access NAS2 after migration, which is not allow to happen in production environment.

I have tried to fork the repo and add this feature to.
But seems there's more things to consider:
1. Only local or NAS(nfs,cifs,which mount to local) need this option.
2. `chown` is not enough. maybe `chmod` is required sometimes
3.  Depend on the user/application. This operation is trying to keep the permission same. But how about ACL( for user not only owner and group)
4. If the goal is just to sync the permission bit. Show we check this bit in `checker` when differ across source and destination
5. Similar to 4, should we do the same check in `rclone check` to make sure every thing is the same

Maybe this is not and easy job at least not for a newcomer

What do you think @ivandeex  @ncw

**Comment by ncw** [comment]
I would like rclone to have a more fully featured metadata system so backends could offer metadata in standard form. The local backend could then offer uid/gid/perms and then that could be implemented by backends which did understand that metadata (like the local backend or sftp).

The easier job would be to break the encapsulation of the incoming object in the upload (passed as `src`) to see if it is a local object and read uid/gid/perms from there.

I implemented this for the s3 backend here (not merged yet) if you want to see how it is done 

https://github.com/rclone/rclone/commit/b7199fe3d71f88ae72718980643eef9a3d3f2ed5

Using that method the change isn't very hard but will only work for local -> local copies

**Comment by hoyho** [comment]
> The easier job would be to break the encapsulation of the incoming object in the upload (passed as `src`) to see if it is a local object and read uid/gid/perms from there.
> 
> I implemented this for the s3 backend here (not merged yet) if you want to see how it is done
> 
> [b7199fe](https://github.com/rclone/rclone/commit/b7199fe3d71f88ae72718980643eef9a3d3f2ed5)
> 
> Using that method the change isn't very hard but will only work for local -> local copies

Yes, That should be easy to implement for files but still have a flaw. 
It may not handle the parent directory and more enclosing dirs

**Comment by ncw** [comment]
Do you want to have a go at that?

**Comment by crabdancing** [comment]
Ran into this six years later. Kinda sucks that we still don't have this. As of 2026, rclone supports SSH and is in dire need of this feature if you happen to use rclone as a more flexible replacement for rsync. I don't think a feature should have to be applicable to all or even many backends to make sense to add.
