### ISSUE TITLE
Erratic vfs-cache behavior: ‘file has changed’ (with -vfs-cache-mode full)

### ISSUE THREAD

**Issue by Piscator74** [rclone/rclone#4763]
#### What is the problem you are having with rclone?
The problem is described in detail on: https://forum.rclone.org/t/erratic-vfs-cache-behavior-file-has-changed/20406
It looks like the modification time is not updated until the cache writeback completes, rather than when the file was written.

#### What is your rclone version (output from `rclone version`)
rclone v1.53.2

    os/arch: linux/amd64
    go version: go1.15.3

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Docker in QNAP

####  Which cloud storage system are you using? (e.g. Google Drive)
Google Drive

**Comment by ncw** [comment]
I can replicate this.

    rclone mount -vv --vfs-cache-mode full --dir-cache-time 10s s3:rclone /mnt/tmp/

The minimal steps are

- edit a text file with nano
- change the file
- write it out with ^O
- wait for the writeback period (5s by default)
- change the file
- write it out with ^O
- get error that the the file has changed from nano

I ran

```
$ while true ; do ls -l --full-time /mnt/tmp/text.txt ; sleep 1 ; done
```

In a terminal while doing this and I see

```
-rw-rw-r-- 1 ncw ncw 13 2020-11-12 12:32:59.325780069 +0000 /mnt/tmp/text.txt
-rw-rw-r-- 1 ncw ncw 13 2020-11-12 12:32:59.325780069 +0000 /mnt/tmp/text.txt
-rw-rw-r-- 1 ncw ncw 13 2020-11-12 12:32:59.325780069 +0000 /mnt/tmp/text.txt
-rw-rw-r-- 1 ncw ncw 13 2020-11-12 12:32:59.325780069 +0000 /mnt/tmp/text.txt
-rw-rw-r-- 1 ncw ncw 14 2020-11-12 12:32:59.325780069 +0000 /mnt/tmp/text.txt <- save from nano here at 2020/11/12 12:35:16
-rw-rw-r-- 1 ncw ncw 14 2020-11-12 12:32:59.325780069 +0000 /mnt/tmp/text.txt
-rw-rw-r-- 1 ncw ncw 14 2020-11-12 12:32:59.325780069 +0000 /mnt/tmp/text.txt
-rw-rw-r-- 1 ncw ncw 14 2020-11-12 12:32:59.325780069 +0000 /mnt/tmp/text.txt
-rw-rw-r-- 1 ncw ncw 14 2020-11-12 12:32:59.325780069 +0000 /mnt/tmp/text.txt
-rw-rw-r-- 1 ncw ncw 14 2020-11-12 12:35:16.499006400 +0000 /mnt/tmp/text.txt <- writeback completes
-rw-rw-r-- 1 ncw ncw 14 2020-11-12 12:35:16.499006400 +0000 /mnt/tmp/text.txt
-rw-rw-r-- 1 ncw ncw 14 2020-11-12 12:35:16.499006400 +0000 /mnt/tmp/text.txt
-rw-rw-r-- 1 ncw ncw 14 2020-11-12 12:35:16.499006400 +0000 /mnt/tmp/text.txt
```

So what it looks like happened is that the modification time wasn't updated until the writeback completed rather than when the file was written.

**Comment by ncw** [comment]
Try this fix - I think it should work. I didn't write tests for it yet though.

[v1.54.0-beta.4890.01836ad61.fix-4763-vfs-modtime](https://beta.rclone.org/branch/fix-4763-vfs-modtime/v1.54.0-beta.4890.01836ad61.fix-4763-vfs-modtime/) on branch [fix-4763-vfs-modtime](https://github.com/rclone/rclone/tree/fix-4763-vfs-modtime) (uploaded in 15-30 mins)

**Comment by Piscator74** [comment]
I have tested it (on the QNAP) and it works perfectly.
Also my original problem is solved now (that the file change causes the markdown editor to truncate the file on a subsequent save).
Thanks for the quick fix!

**Comment by Piscator74** [comment]
Correction: it is not fixed yet. I am still detecting a file change after roughly 10 seconds.
I have the following setup.
* rclone on the QNAP (server) that shares the cloud drives over SAMBA in the local network.
* I edit a file on this share in Windows (with notepad++).

When I do the following.
* Edit a text file with notepad++ and save it.
* After roughly 10 seconds it detects that that file has changed
* I do not have the problem anymore that files get truncated (this happened both with notepad++ and typora, so that problem was related to the fix you did).

**Comment by Piscator74** [comment]
@nsw. When I use your script to monitor file changes, I do not see the same behavior as in my previous post, but I *sometimes* see strange behavior

```
-rw-r----- 1 user none 0 2020-11-12 23:45:02.568774610 +0100 tmp.txt   <-- touch tmp.txt
-rw-r----- 1 user none 0 2020-11-12 23:45:02.568774610 +0100 tmp.txt
-rw-r----- 1 user none 0 2020-11-12 23:45:02.568774610 +0100 tmp.txt
-rw-r----- 1 user none 7 2020-11-12 23:45:10.728518829 +0100 tmp.txt   <-- first save (with nano)
-rw-r----- 1 user none 7 2020-11-12 23:45:10.728518829 +0100 tmp.txt
-rw-r----- 1 user none 7 2020-11-12 23:45:10.728518829 +0100 tmp.txt
-rw-r----- 1 user none 7 2020-11-12 23:45:10.728518829 +0100 tmp.txt
-rw-r----- 1 user none 7 2020-11-12 23:45:10.728518829 +0100 tmp.txt
-rw-r----- 1 user none 7 2020-11-12 23:45:10.728518829 +0100 tmp.txt
-rw-r----- 1 user none 7 2020-11-12 23:45:10.728518829 +0100 tmp.txt
-rw-r----- 1 user none 7 2020-11-12 23:45:10.728518829 +0100 tmp.txt
-rw-r----- 1 user none 7 2020-11-12 23:45:10.728518829 +0100 tmp.txt
-rw-r----- 1 user none 7 2020-11-12 23:45:10.728518829 +0100 tmp.txt
-rw-r----- 1 user none 7 2020-11-12 23:45:10.728518829 +0100 tmp.txt
-rw-r----- 1 user none 7 2020-11-12 23:45:10.728518829 +0100 tmp.txt
-rw-r----- 1 user none 7 2020-11-12 23:45:10.728518829 +0100 tmp.txt
-rw-r----- 1 user none 7 2020-11-12 23:45:10.728518829 +0100 tmp.txt
-rw-r----- 1 user none 0 2020-11-12 23:45:25.548846613 +0100 tmp.txt  <-- second save (with nano). Size should not be 0 (!!!)
-rw-r----- 1 user none 0 2020-11-12 23:45:25.548846613 +0100 tmp.txt
-rw-r----- 1 user none 0 2020-11-12 23:45:25.548846613 +0100 tmp.txt
-rw-r----- 1 user none 13 2020-11-12 23:45:28.531262170 +0100 tmp.txt    <-- no change, but the file size magically changes
-rw-r----- 1 user none 13 2020-11-12 23:45:28.531262170 +0100 tmp.txt
-rw-r----- 1 user none 13 2020-11-12 23:45:28.531262170 +0100 tmp.txt
-rw-r----- 1 user none 13 2020-11-12 23:45:28.531262170 +0100 tmp.txt
-rw-r----- 1 user none 13 2020-11-12 23:45:28.531262170 +0100 tmp.txt
```

**Comment by darthShadow** [comment]
Looks like a typo in the ping. Pinging @ncw.

**Comment by Piscator74** [comment]
@ncw. Did you manage to replicate the behavior I described? Sorry, for the 'ping' typo.

**Comment by ncw** [comment]
@Piscator74 I can't replicate the problem with the fix-4763-vfs-modtime fix.

I rebased the fix - can you try this

[v1.54.0-beta.4957.145e62446.fix-4763-vfs-modtime](https://beta.rclone.org/branch/fix-4763-vfs-modtime/v1.54.0-beta.4957.145e62446.fix-4763-vfs-modtime/) on branch [fix-4763-vfs-modtime](https://github.com/rclone/rclone/tree/fix-4763-vfs-modtime) (uploaded in 15-30 mins)

And if you can get to fail then please provided detailed instructions on how to reproduce - thanks!

I can't test anything on Windows so if you could reproduce the problem on Linux directly on the mount with nano.

**Comment by Piscator74** [comment]
@ncw. I am still able to reproduce it. What happens in general is the following:
* Make an update with nano to temp.txt (write it out with ^O)
* After roughly 6 to 7 seconds, the timestamp of the file is changed (slightly rounded down). This happens consistently.
* Sometimes I see a file size of 0 (for a few seconds) when saving

The output with your one-liner
```
while true ; do ls -l --full-time ./text.txt ; sleep 1 ; done
```
-rw-r----- 1 user none 10 2020-12-08 13:41:41.713000000 +0100 ./text.txt
-rw-r----- 1 user none 10 2020-12-08 13:41:41.713000000 +0100 ./text.txt
-rw-r----- 1 user none 10 2020-12-08 13:41:41.713000000 +0100 ./text.txt
-rw-r----- 1 user none 18 2020-12-08 13:42:02.978319702 +0100 ./text.txt   <-- 1st save with nano
-rw-r----- 1 user none 18 2020-12-08 13:42:02.978319702 +0100 ./text.txt
-rw-r----- 1 user none 18 2020-12-08 13:42:02.978319702 +0100 ./text.txt
-rw-r----- 1 user none 18 2020-12-08 13:42:02.978319702 +0100 ./text.txt
-rw-r----- 1 user none 18 2020-12-08 13:42:02.978319702 +0100 ./text.txt
-rw-r----- 1 user none 18 2020-12-08 13:42:02.978319702 +0100 ./text.txt
-rw-r----- 1 user none 18 2020-12-08 13:42:02.978319702 +0100 ./text.txt
-rw-r----- 1 user none 18 2020-12-08 13:42:02.978000000 +0100 ./text.txt   <-- timestamp magically changed (rounded down)
-rw-r----- 1 user none 18 2020-12-08 13:42:02.978000000 +0100 ./text.txt
-rw-r----- 1 user none 18 2020-12-08 13:42:02.978000000 +0100 ./text.txt
-rw-r----- 1 user none 18 2020-12-08 13:42:02.978000000 +0100 ./text.txt
-rw-r----- 1 user none 18 2020-12-08 13:42:02.978000000 +0100 ./text.txt
-rw-r----- 1 user none 18 2020-12-08 13:42:02.978000000 +0100 ./text.txt
<snip>

-rw-r----- 1 user none 18 2020-12-08 13:42:02.978000000 +0100 ./text.txt
-rw-r----- 1 user none 18 2020-12-08 13:42:02.978000000 +0100 ./text.txt
-rw-r----- 1 user none 0 2020-12-08 13:42:33.474461435 +0100 ./text.txt    <-- 2nd save with nano
-rw-r----- 1 user none 33 2020-12-08 13:42:33.475229443 +0100 ./text.txt  <-- but 1s later it shows the correct siize
-rw-r----- 1 user none 33 2020-12-08 13:42:33.475229443 +0100 ./text.txt
-rw-r----- 1 user none 33 2020-12-08 13:42:33.475229443 +0100 ./text.txt
-rw-r----- 1 user none 33 2020-12-08 13:42:33.475229443 +0100 ./text.txt
-rw-r----- 1 user none 33 2020-12-08 13:42:33.475229443 +0100 ./text.txt
-rw-r----- 1 user none 33 2020-12-08 13:42:33.475229443 +0100 ./text.txt
<snip>

-rw-r----- 1 user none 0 2020-12-08 15:15:52.309000000 +0100 ./text.txt   <-- touch temp.txt (after rm)
-rw-r----- 1 user none 0 2020-12-08 15:15:52.309000000 +0100 ./text.txt
-rw-r----- 1 user none 0 2020-12-08 15:15:52.309000000 +0100 ./text.txt
-rw-r----- 1 user none 0 2020-12-08 15:15:52.309000000 +0100 ./text.txt
-rw-r----- 1 user none 7 2020-12-08 15:16:08.160417657 +0100 ./text.txt   <--- save with nano
-rw-r----- 1 user none 7 2020-12-08 15:16:08.160417657 +0100 ./text.txt
-rw-r----- 1 user none 7 2020-12-08 15:16:08.160417657 +0100 ./text.txt
-rw-r----- 1 user none 7 2020-12-08 15:16:08.160417657 +0100 ./text.txt
-rw-r----- 1 user none 7 2020-12-08 15:16:08.160417657 +0100 ./text.txt
-rw-r----- 1 user none 7 2020-12-08 15:16:08.160417657 +0100 ./text.txt
-rw-r----- 1 user none 7 2020-12-08 15:16:08.160000000 +0100 ./text.txt  <-- timestamp magically changed (rounded down)
-rw-r----- 1 user none 7 2020-12-08 15:16:08.160000000 +0100 ./text.txt

My rclone settings
```
#!/bin/bash
AUTH="--rc-user=$USERNAME --rc-pass=$PASSWORD"

./rclone rcd --rc-web-gui --rc-web-gui-no-open-browser --cache-dir /share/cloud/bert/.cache --rc-addr :5572 $AUTH &
sleep 5

./rclone rc options/set --json '{"main": { "Transfers": 4 }, "vfs" : {"UID": '$PUID', "GID": '$PGID', "Umask": 23, "CacheMode": 3, "CacheMaxAge": 31622400000000000, "DirCacheTime": 31536000000000000}, "mount": {"AllowOther": true}}' $AUTH
./rclone rc mount/mount fs=googledrive: mountPoint=/share/cloud/bert/googledrive $AUTH
```

I hope this helps. If you want me to test something different, please let me know.

**Comment by ncw** [comment]
I know what causes the magically rounded down timestamps - that is when the writeback completes, rclone reads the actual time set on the object back and Google Drive can only store times accurate to the millisecond.

I can reproduce that, but I haven't managed to reproduce the file showing as 0 length for a moment.

Can you make a log for me with `-vv` of this event happening please? If you could supply the notated output of my shell script that would be really helpful - then I can correlate the logs in the mount with the actions taken by you.

Thanks for your help.

**Comment by Piscator74** [comment]
You have to get 'lucky' when you want to get the '0 bytes' to occur.

Repeatedly hitting save with nano gets me the following error in the log file:
```
2020/12/08 20:00:18 ERROR : text.txt: Failed to copy: can't copy - source file is being updated (mod time changed from 2020-12-08 20:00:06.942148516 +0100 CET to 2020-12-08 20:00:14.337166273 +0100 CET)
2020/12/08 20:00:18 ERROR : text.txt: vfs cache: failed to upload try #1, will retry in 10s: vfs cache: failed to transfer file from cache to remote: can't copy - source file is being updated (mod time changed from 2020-12-08 20:00:06.942148516 +0100 CET to 2020-12-08 20:00:14.337166273 +0100 CET)
```

And the output:
```
-rw-r----- 1 bert none 7 2020-12-08 19:59:53.225336214 +0100 text.txt
-rw-r----- 1 bert none 7 2020-12-08 19:59:53.225336214 +0100 text.txt
-rw-r----- 1 bert none 7 2020-12-08 19:59:53.225336214 +0100 text.txt
-rw-r----- 1 bert none 13 2020-12-08 20:00:00.377140221 +0100 text.txt  <-- update
-rw-r----- 1 bert none 13 2020-12-08 20:00:00.377140221 +0100 text.txt
-rw-r----- 1 bert none 13 2020-12-08 20:00:00.377140221 +0100 text.txt
-rw-r----- 1 bert none 13 2020-12-08 20:00:00.377140221 +0100 text.txt
-rw-r----- 1 bert none 13 2020-12-08 20:00:00.377140221 +0100 text.txt
-rw-r----- 1 bert none 13 2020-12-08 20:00:00.377140221 +0100 text.txt
-rw-r----- 1 bert none 19 2020-12-08 20:00:06.942148516 +0100 text.txt  <-- update
-rw-r----- 1 bert none 19 2020-12-08 20:00:06.942148516 +0100 text.txt
-rw-r----- 1 bert none 19 2020-12-08 20:00:06.942148516 +0100 text.txt
-rw-r----- 1 bert none 19 2020-12-08 20:00:06.942148516 +0100 text.txt
-rw-r----- 1 bert none 19 2020-12-08 20:00:06.942148516 +0100 text.txt
-rw-r----- 1 bert none 19 2020-12-08 20:00:06.942148516 +0100 text.txt
-rw-r----- 1 bert none 19 2020-12-08 20:00:06.942148516 +0100 text.txt
-rw-r----- 1 bert none 0 2020-12-08 20:00:18.746845412 +0100 text.txt  <-- update (and see the error above)
-rw-r----- 1 bert none 28 2020-12-08 20:00:18.935354670 +0100 text.txt
-rw-r----- 1 bert none 28 2020-12-08 20:00:18.935354670 +0100 text.txt
-
```

It looks like updating the file at exact the same time as when the mod time is updating?

**Comment by ncw** [comment]
> You have to get 'lucky' when you want to get the '0 bytes' to occur.
> 
> Repeatedly hitting save with nano gets me the following error in the log file:
> 
> ```
> 2020/12/08 20:00:18 ERROR : text.txt: Failed to copy: can't copy - source file is being updated (mod time changed from 2020-12-08 20:00:06.942148516 +0100 CET to 2020-12-08 20:00:14.337166273 +0100 CET)
> 2020/12/08 20:00:18 ERROR : text.txt: vfs cache: failed to upload try #1, will retry in 10s: vfs cache: failed to transfer file from cache to remote: can't copy - source file is being updated (mod time changed from 2020-12-08 20:00:06.942148516 +0100 CET to 2020-12-08 20:00:14.337166273 +0100 CET)```

This error is because you modified the file while it was being uploaded. The upload should have been retried.

> ```EDIT: this appeared a while later in the log
> 2020/12/08 20:09:55 ERROR : text.txt: corrupted on transfer: MD5 hash differ "0e5d2dc0db8b4407625b8bf633b75055" vs "b1946ac92492d2347c6235b4d2611184"
> 2020/12/08 20:09:56 ERROR : text.txt: vfs cache: failed to upload try #1, will retry in 10s: vfs cache: failed to transfer file from cache to remote: corrupted on transfer: MD5 hash differ "0e5d2dc0db8b4407625b8bf633b75055" vs "b1946ac92492d2347c6235b4d2611184"
> ```

And this has the same cause - the file was changed while being uploaded so the MD5 didn't match. It should have caused the file to be re-uploaded.

> ```
> -rw-r----- 1 user none 7 2020-12-08 19:59:53.225336214 +0100 text.txt
> -rw-r----- 1 user none 7 2020-12-08 19:59:53.225336214 +0100 text.txt
> -rw-r----- 1 user none 7 2020-12-08 19:59:53.225336214 +0100 text.txt
> -rw-r----- 1 user none 13 2020-12-08 20:00:00.377140221 +0100 text.txt  <-- update
> -rw-r----- 1 user none 13 2020-12-08 20:00:00.377140221 +0100 text.txt
> -rw-r----- 1 user none 13 2020-12-08 20:00:00.377140221 +0100 text.txt
> -rw-r----- 1 user none 13 2020-12-08 20:00:00.377140221 +0100 text.txt
> -rw-r----- 1 user none 13 2020-12-08 20:00:00.377140221 +0100 text.txt
> -rw-r----- 1 user none 13 2020-12-08 20:00:00.377140221 +0100 text.txt
> -rw-r----- 1 user none 19 2020-12-08 20:00:06.942148516 +0100 text.txt  <-- update
> -rw-r----- 1 user none 19 2020-12-08 20:00:06.942148516 +0100 text.txt
> -rw-r----- 1 user none 19 2020-12-08 20:00:06.942148516 +0100 text.txt
> -rw-r----- 1 user none 19 2020-12-08 20:00:06.942148516 +0100 text.txt
> -rw-r----- 1 user none 19 2020-12-08 20:00:06.942148516 +0100 text.txt
> -rw-r----- 1 user none 19 2020-12-08 20:00:06.942148516 +0100 text.txt
> -rw-r----- 1 user none 19 2020-12-08 20:00:06.942148516 +0100 text.txt
> -rw-r----- 1 user none 0 2020-12-08 20:00:18.746845412 +0100 text.txt  <-- update (and see the error above)
> -rw-r----- 1 user none 28 2020-12-08 20:00:18.935354670 +0100 text.txt
> -rw-r----- 1 user none 28 2020-12-08 20:00:18.935354670 +0100 text.txt
> ```
> 
> It looks like updating the file at exact the same time as when the mod time is updating?

I managed to reproduce this eventually with a lot of button mashing :-)

```
-rw-rw-r-- 1 ncw ncw 30 2020-12-09 16:36:20.299582147 +0000 /mnt/tmp/text.txt
-rw-rw-r-- 1 ncw ncw 30 2020-12-09 16:36:20.299582147 +0000 /mnt/tmp/text.txt
-rw-rw-r-- 1 ncw ncw 30 2020-12-09 16:36:20.299582147 +0000 /mnt/tmp/text.txt
-rw-rw-r-- 1 ncw ncw 30 2020-12-09 16:36:20.299582147 +0000 /mnt/tmp/text.txt
-rw-rw-r-- 1 ncw ncw 0 2020-12-09 16:36:25.368080163 +0000 /mnt/tmp/text.txt
-rw-rw-r-- 1 ncw ncw 0 2020-12-09 16:36:25.368080163 +0000 /mnt/tmp/text.txt
-rw-rw-r-- 1 ncw ncw 0 2020-12-09 16:36:25.368080163 +0000 /mnt/tmp/text.txt
-rw-rw-r-- 1 ncw ncw 0 2020-12-09 16:36:25.368080163 +0000 /mnt/tmp/text.txt
-rw-rw-r-- 1 ncw ncw 0 2020-12-09 16:36:25.368080163 +0000 /mnt/tmp/text.txt
-rw-rw-r-- 1 ncw ncw 0 2020-12-09 16:36:25.368080163 +0000 /mnt/tmp/text.txt
-rw-rw-r-- 1 ncw ncw 0 2020-12-09 16:36:25.368080163 +0000 /mnt/tmp/text.txt
-rw-rw-r-- 1 ncw ncw 0 2020-12-09 16:36:25.368080163 +0000 /mnt/tmp/text.txt
-rw-rw-r-- 1 ncw ncw 0 2020-12-09 16:36:25.368080163 +0000 /mnt/tmp/text.txt
-rw-rw-r-- 1 ncw ncw 31 2020-12-09 16:36:27.248897410 +0000 /mnt/tmp/text.txt
-rw-rw-r-- 1 ncw ncw 31 2020-12-09 16:36:27.248897410 +0000 /mnt/tmp/text.txt
-rw-rw-r-- 1 ncw ncw 31 2020-12-09 16:36:27.248897410 +0000 /mnt/tmp/text.txt
-rw-rw-r-- 1 ncw ncw 31 2020-12-09 16:36:27.248897410 +0000 /mnt/tmp/text.txt
```

The relevant parts of the mount log are

File is normal size here

    2020/12/09 16:36:24 DEBUG : text.txt: Attr: 
    2020/12/09 16:36:24 DEBUG : text.txt: >Attr: a=valid=1s ino=0 size=30 mode=-rw-rw-r--, err=<nil>

Previous upload started

    2020/12/09 16:36:25 DEBUG : text.txt: vfs cache: starting upload

File is opened by nano

    2020/12/09 16:36:25 DEBUG : text.txt: Open: flags=OpenWriteOnly
    2020/12/09 16:36:25 DEBUG : text.txt: Open: flags=O_WRONLY
    2020/12/09 16:36:25 DEBUG : text.txt: newRWFileHandle: 
    2020/12/09 16:36:25 DEBUG : text.txt: >newRWFileHandle: err=<nil>
    2020/12/09 16:36:25 DEBUG : text.txt: >Open: fd=text.txt (rw), err=<nil>
    2020/12/09 16:36:25 DEBUG : text.txt: >Open: fh=&{text.txt (rw)}, err=<nil>

nano truncates the file to 0 size (Settattr size=0) - this call doesn't finish until the upload is cancelled, so the file stays at 0 time for some time

    2020/12/09 16:36:25 DEBUG : text.txt: Setattr: a=Setattr [ID=0x17e Node=0x2 Uid=1000 Gid=1000 Pid=2548343] size=0 handle=INVALID-0x0 lockowner
    2020/12/09 16:36:25 DEBUG : text.txt: Truncating 1 file handles
    2020/12/09 16:36:25 DEBUG : text.txt(0xc00045bec0): openPending: 
    2020/12/09 16:36:25 DEBUG : text.txt: vfs cache: checking remote fingerprint "29,2020-12-09 16:36:11.431 +0000 UTC,53f4758304bf114664d802db15988ec3" against cached fingerprint "29,2020-12-09 16:36:11.431 +0000 UTC,53f4758304bf114664d802db15988ec3"
    2020/12/09 16:36:25 DEBUG : text.txt: vfs cache: truncate to size=30
    2020/12/09 16:36:25 DEBUG : : Added virtual directory entry vAddFile: "text.txt"
    2020/12/09 16:36:25 DEBUG : text.txt(0xc00045bec0): >openPending: err=<nil>
    2020/12/09 16:36:25 DEBUG : text.txt: vfs cache: truncate to size=0

Writeback is then cancelled because the file is changed

    2020/12/09 16:36:25 DEBUG : text.txt: vfs cache: cancelling writeback (uploading true) 0xc0004b6ee0 item 1
    2020/12/09 16:36:25 DEBUG : text.txt: vfs cache: cancelling upload
    2020/12/09 16:36:25 DEBUG : text.txt: Attr: 
    2020/12/09 16:36:25 DEBUG : text.txt: >Attr: a=valid=1s ino=0 size=0 mode=-rw-rw-r--, err=<nil>
    2020/12/09 16:36:26 DEBUG : text.txt: MD5 = d41d8cd98f00b204e9800998ecf8427e (Local file system at /home/ncw/.cache/rclone/vfs/TestDrive)
    2020/12/09 16:36:26 DEBUG : text.txt: MD5 = cc5a48fae507bdb37c3adc6f6dd7e3c9 (Google drive root '')
    2020/12/09 16:36:26 ERROR : text.txt: corrupted on transfer: MD5 hash differ "d41d8cd98f00b204e9800998ecf8427e" vs "cc5a48fae507bdb37c3adc6f6dd7e3c9"
    2020/12/09 16:36:26 INFO  : text.txt: Removing failed copy

The upload fails instead of being cancelled (common for short files)

The file appears 0 length here (size=0)

    2020/12/09 16:36:26 DEBUG : text.txt: Attr: 
    2020/12/09 16:36:26 DEBUG : text.txt: >Attr: a=valid=1s ino=0 size=0 mode=-rw-rw-r--, err=<nil>

The file is queued for retry, then cancelled

    2020/12/09 16:36:27 ERROR : text.txt: vfs cache: failed to upload try #1, will retry in 10s: vfs cache: failed to transfer file from cache to remote: corrupted on transfer: MD5 hash differ "d41d8cd98f00b204e9800998ecf8427e" vs "cc5a48fae507bdb37c3adc6f6dd7e3c9"
    2020/12/09 16:36:27 DEBUG : text.txt: vfs cache: cancelled upload
    2020/12/09 16:36:27 DEBUG : text.txt: >Setattr: err=<nil>

The Setattr call finally finishes here. File size still reads 0

    2020/12/09 16:36:27 DEBUG : text.txt: Attr: 
    2020/12/09 16:36:27 DEBUG : text.txt: >Attr: a=valid=1s ino=0 size=0 mode=-rw-rw-r--, err=<nil>

Now nano writes to the file and closes it

    2020/12/09 16:36:27 DEBUG : &{text.txt (rw)}: Write: len=31, offset=0
    2020/12/09 16:36:27 DEBUG : text.txt(0xc00045bec0): _writeAt: size=31, off=0
    2020/12/09 16:36:27 DEBUG : text.txt(0xc00045bec0): >_writeAt: n=31, err=<nil>
    2020/12/09 16:36:27 DEBUG : &{text.txt (rw)}: >Write: written=31, err=<nil>
    2020/12/09 16:36:27 DEBUG : &{text.txt (rw)}: Flush: 
    2020/12/09 16:36:27 DEBUG : text.txt(0xc00045bec0): RWFileHandle.Flush
    2020/12/09 16:36:27 DEBUG : &{text.txt (rw)}: >Flush: err=<nil>
    2020/12/09 16:36:27 DEBUG : &{text.txt (rw)}: Release: 
    2020/12/09 16:36:27 DEBUG : text.txt(0xc00045bec0): RWFileHandle.Release
    2020/12/09 16:36:27 DEBUG : text.txt(0xc00045bec0): close: 

And only now (2 seconds later) does the file actually appear as the correct length again

In summary, nano truncates the file before writing it - this is pretty common. However if this happens when the file is being uploaded, it takes long enough for the 0 size file to be visible because rclone cancels the ongoing upload. Normally this would happen extrememly quickly so you wouldn't notice the non-zero length file.

So I think this, despite the 0 length and error messages, is working properly and should have uploaded your file correctly.

**Comment by Piscator74** [comment]
I also tried the following script with various delays to see if I could reproduce the problem, but with this script I could never reproduce it. Perhaps because it just concatenates to a file.

```
#!/bin/bash
trap "pkill test.sh" SIGINT

rm text.txt
( while true ; do echo "write now!" && (echo hello >> text.txt) ; sleep 6 ; done ) &
( while true ; do ls -l --full-time text.txt ; sleep 1 ; done )| tee log.txt
```

The original problem I have: when I save a file with typora via rclone on google drive, it says "save failed" and the file is immediately truncated (example here: test.md). I have included the rclone logfile with -vv. Perhaps you can see why this is happening (btw typora is also available under linux). If I could find another way to reproduce it, I would ;-)

```
2020/12/12 20:42:22 DEBUG : rclone: Version "v1.54.0-beta.4957.145e62446.fix-4763-vfs-modtime" starting with parameters ["./rclone" "rcd" "-vv" "--log-file=log.txt" "--rc-web-gui" "--rc-web-gui-no-open-browser" "--cache-dir" "/share/cloud/user/.cache" "--rc-addr" ":5572" "--rc-user=XXXXX" "--rc-pass=XXXXX"]
2020/12/12 20:42:22 DEBUG : Current tag: v2.0.3, Release tag: v2.0.3
2020/12/12 20:42:22 NOTICE: Web GUI exists. Update skipped.
2020/12/12 20:42:22 NOTICE: Serving Web GUI
2020/12/12 20:42:22 INFO  : Using --user XXXXX --pass XXXX as authenticated user
2020/12/12 20:42:22 NOTICE: Serving remote control on http://[::]:5572/
2020/12/12 20:42:22 DEBUG : login_token "cmNsb25lOnJjbG9uZQ=="
2020/12/12 20:42:22 NOTICE: Web GUI is not automatically opening browser. Navigate to http://rclone:rclone@[::]:5572/?login_token=cmNsb25lOnJjbG9uZQ%3D%3D to use.
2020/12/12 20:42:27 DEBUG : rc: "options/set": with parameters map[main:map[Transfers:4] mount:map[AllowOther:true] vfs:map[CacheMaxAge:3.16224e+16 CacheMode:3 DirCacheTime:3.1536e+16 GID:1004 UID:1000 Umask:23]]
2020/12/12 20:42:27 DEBUG : rc: "options/set": reply map[]: <nil>
2020/12/12 20:42:27 DEBUG : rc: "mount/mount": with parameters map[fs:googledrive: mountPoint:/share/cloud/user/googledrive]
2020/12/12 20:42:27 DEBUG : Creating backend with remote "googledrive:"
2020/12/12 20:42:27 DEBUG : Using config file from "/share/system/admin/.config/rclone/rclone.conf"
2020/12/12 20:42:27 DEBUG : Google drive root '': root_folder_id = "0ACa9oEiHSdFQUk9PVA" - save this in the config to speed up startup
2020/12/12 20:42:27 DEBUG : vfs cache: root is "/share/cloud/user/.cache/vfs/googledrive"
2020/12/12 20:42:27 DEBUG : vfs cache: metadata root is "/share/cloud/user/.cache/vfs/googledrive"
2020/12/12 20:42:27 DEBUG : Creating backend with remote "/share/cloud/user/.cache/vfs/googledrive"
2020/12/12 20:42:27 DEBUG : Google drive root '': Mounting on "/share/cloud/user/googledrive"
2020/12/12 20:42:27 DEBUG : Mount for Google drive root '' created at /share/cloud/user/googledrive using mount
2020/12/12 20:42:27 DEBUG : rc: "mount/mount": reply map[]: <nil>
2020/12/12 20:42:27 DEBUG : : Root: 
2020/12/12 20:42:27 DEBUG : : >Root: node=/, err=<nil>
2020/12/12 20:42:30 DEBUG : /: Lookup: name="test"
2020/12/12 20:42:31 DEBUG : /: >Lookup: node=test/, err=<nil>
2020/12/12 20:42:31 DEBUG : test/: Attr: 
2020/12/12 20:42:31 DEBUG : test/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-x---, err=<nil>
2020/12/12 20:42:31 DEBUG : test/: Lookup: name="test.md"
2020/12/12 20:42:31 DEBUG : test/: >Lookup: node=test/test.md, err=<nil>
2020/12/12 20:42:31 DEBUG : test/test.md: Attr: 
2020/12/12 20:42:31 DEBUG : test/test.md: >Attr: a=valid=1s ino=0 size=9044 mode=-rw-r-----, err=<nil>
2020/12/12 20:42:31 DEBUG : /: Attr: 
2020/12/12 20:42:31 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-x---, err=<nil>
2020/12/12 20:42:33 DEBUG : /: Attr: 
2020/12/12 20:42:33 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-x---, err=<nil>
2020/12/12 20:42:33 DEBUG : /: Lookup: name="test"
2020/12/12 20:42:33 DEBUG : /: >Lookup: node=test/, err=<nil>
2020/12/12 20:42:33 DEBUG : test/: Attr: 
2020/12/12 20:42:33 DEBUG : test/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-x---, err=<nil>
2020/12/12 20:42:33 DEBUG : test/: Lookup: name=".~test.md"
2020/12/12 20:42:33 DEBUG : test/: >Lookup: node=<nil>, err=no such file or directory
2020/12/12 20:42:33 DEBUG : test/: Lookup: name=".~test.md"
2020/12/12 20:42:33 DEBUG : test/: >Lookup: node=<nil>, err=no such file or directory
2020/12/12 20:42:33 DEBUG : test/: ReadDirAll: 
2020/12/12 20:42:33 DEBUG : test/: >ReadDirAll: item=1, err=<nil>
2020/12/12 20:42:33 DEBUG : test/: Attr: 
2020/12/12 20:42:33 DEBUG : test/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-x---, err=<nil>
2020/12/12 20:42:33 DEBUG : test/: Lookup: name=".~test.md"
2020/12/12 20:42:33 DEBUG : test/: >Lookup: node=<nil>, err=no such file or directory
2020/12/12 20:42:33 DEBUG : test/: Create: name=".~test.md"
2020/12/12 20:42:33 DEBUG : test/.~test.md: Open: flags=O_RDWR|O_CREATE|O_EXCL
2020/12/12 20:42:33 DEBUG : test/.~test.md: newRWFileHandle: 
2020/12/12 20:42:33 DEBUG : test/.~test.md(0xc0001a4840): openPending: 
2020/12/12 20:42:33 DEBUG : test/.~test.md: vfs cache: truncate to size=0
2020/12/12 20:42:33 DEBUG : test: Added virtual directory entry vAddFile: ".~test.md"
2020/12/12 20:42:33 DEBUG : test/.~test.md(0xc0001a4840): >openPending: err=<nil>
2020/12/12 20:42:33 DEBUG : test/.~test.md: >newRWFileHandle: err=<nil>
2020/12/12 20:42:33 DEBUG : test: Added virtual directory entry vAddFile: ".~test.md"
2020/12/12 20:42:33 DEBUG : test/.~test.md: >Open: fd=test/.~test.md (rw), err=<nil>
2020/12/12 20:42:33 DEBUG : test/: >Create: node=test/.~test.md, handle=&{test/.~test.md (rw)}, err=<nil>
2020/12/12 20:42:33 DEBUG : test/.~test.md: Attr: 
2020/12/12 20:42:33 DEBUG : test/.~test.md: >Attr: a=valid=1s ino=0 size=0 mode=-rw-r-----, err=<nil>
2020/12/12 20:42:33 DEBUG : test/: Attr: 
2020/12/12 20:42:33 DEBUG : test/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-x---, err=<nil>
2020/12/12 20:42:33 DEBUG : : Statfs: 
2020/12/12 20:42:33 DEBUG : : >Statfs: stat={Blocks:3932160 Bfree:2349983 Bavail:2349983 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2020/12/12 20:42:34 DEBUG : &{test/.~test.md (rw)}: Release: 
2020/12/12 20:42:34 DEBUG : test/.~test.md(0xc0001a4840): RWFileHandle.Release
2020/12/12 20:42:34 DEBUG : test/.~test.md(0xc0001a4840): close: 
2020/12/12 20:42:34 DEBUG : /: Lookup: name="test"
2020/12/12 20:42:34 DEBUG : /: >Lookup: node=test/, err=<nil>
2020/12/12 20:42:34 DEBUG : test/: Attr: 
2020/12/12 20:42:34 DEBUG : test/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-x---, err=<nil>
2020/12/12 20:42:34 DEBUG : test/.~test.md: Attr: 
2020/12/12 20:42:34 DEBUG : test/.~test.md: vfs cache: setting modification time to 2020-12-12 20:42:33.569299116 +0100 CET m=+11.211492322
2020/12/12 20:42:34 INFO  : test/.~test.md: vfs cache: queuing for upload in 5s
2020/12/12 20:42:34 DEBUG : test/.~test.md(0xc0001a4840): >close: err=<nil>
2020/12/12 20:42:34 DEBUG : &{test/.~test.md (rw)}: >Release: err=<nil>
2020/12/12 20:42:34 DEBUG : test/.~test.md: >Attr: a=valid=1s ino=0 size=0 mode=-rw-r-----, err=<nil>
2020/12/12 20:42:34 DEBUG : test/.~test.md: Setattr: a=Setattr [ID=0x19 Node=0x4 Uid=1000 Gid=100 Pid=11722] atime=2020-12-12 20:42:33.569299116 +0100 CET mtime=2020-12-12 20:42:34.505705432 +0100 CET handle=INVALID-0x0
2020/12/12 20:42:34 DEBUG : test/.~test.md: vfs cache: setting modification time to 2020-12-12 20:42:34.505705432 +0100 CET
2020/12/12 20:42:34 DEBUG : test/.~test.md: >Setattr: err=<nil>
2020/12/12 20:42:34 DEBUG : test/.~test.md: Attr: 
2020/12/12 20:42:34 DEBUG : test/.~test.md: >Attr: a=valid=1s ino=0 size=0 mode=-rw-r-----, err=<nil>
2020/12/12 20:42:34 DEBUG : test/: Lookup: name="test.md"
2020/12/12 20:42:34 DEBUG : test/: >Lookup: node=test/test.md, err=<nil>
2020/12/12 20:42:34 DEBUG : test/test.md: Attr: 
2020/12/12 20:42:34 DEBUG : test/test.md: >Attr: a=valid=1s ino=0 size=9044 mode=-rw-r-----, err=<nil>
 2020/12/12 20:42:34 DEBUG : test/test.md: Open: flags=OpenReadWrite
2020/12/12 20:42:34 DEBUG : test/test.md: Open: flags=O_RDWR
2020/12/12 20:42:34 DEBUG : test/test.md: newRWFileHandle: 
2020/12/12 20:42:34 DEBUG : test/test.md: >newRWFileHandle: err=<nil>
2020/12/12 20:42:34 DEBUG : test/test.md: >Open: fd=test/test.md (rw), err=<nil>
2020/12/12 20:42:34 DEBUG : test/test.md: >Open: fh=&{test/test.md (rw)}, err=<nil>
2020/12/12 20:42:34 DEBUG : test/test.md: Setattr: a=Setattr [ID=0x1c Node=0x3 Uid=1000 Gid=100 Pid=11722] size=0 handle=0x1 lockowner
2020/12/12 20:42:34 DEBUG : test/test.md: Truncating 1 file handles
2020/12/12 20:42:34 DEBUG : test/test.md(0xc0000a1d40): openPending: 
2020/12/12 20:42:34 DEBUG : test/test.md: vfs cache: checking remote fingerprint "9044,2020-11-20 22:54:01 +0000 UTC,fbf70a833928b7dc3388ac1a8d77dfed" against cached fingerprint "9044,2020-11-20 22:54:01 +0000 UTC,fbf70a833928b7dc3388ac1a8d77dfed"
2020/12/12 20:42:34 DEBUG : test/test.md: vfs cache: truncate to size=9044
2020/12/12 20:42:34 DEBUG : test: Added virtual directory entry vAddFile: "test.md"
2020/12/12 20:42:34 DEBUG : test/test.md(0xc0000a1d40): >openPending: err=<nil>
2020/12/12 20:42:34 DEBUG : test/test.md: vfs cache: truncate to size=0
2020/12/12 20:42:34 DEBUG : test/test.md: >Setattr: err=<nil>
2020/12/12 20:42:34 DEBUG : test/test.md: Attr: 
2020/12/12 20:42:34 DEBUG : test/test.md: >Attr: a=valid=1s ino=0 size=0 mode=-rw-r-----, err=<nil>
2020/12/12 20:42:34 DEBUG : test/: Lookup: name="._test.md"
2020/12/12 20:42:34 DEBUG : test/: >Lookup: node=<nil>, err=no such file or directory
2020/12/12 20:42:34 DEBUG : : Statfs: 
2020/12/12 20:42:34 DEBUG : : >Statfs: stat={Blocks:3932160 Bfree:2349983 Bavail:2349983 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2020/12/12 20:42:35 DEBUG : /: Attr: 
2020/12/12 20:42:35 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-x---, err=<nil>
2020/12/12 20:42:35 DEBUG : /: ReadDirAll: 
2020/12/12 20:42:35 DEBUG : /: >ReadDirAll: item=7, err=<nil>
2020/12/12 20:42:35 DEBUG : /: Lookup: name="Other"
2020/12/12 20:42:35 DEBUG : /: >Lookup: node=Other/, err=<nil>
2020/12/12 20:42:35 DEBUG : Other/: Attr: 
2020/12/12 20:42:35 DEBUG : Other/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-x---, err=<nil>
2020/12/12 20:42:35 DEBUG : /: Lookup: name="Private"
2020/12/12 20:42:35 DEBUG : /: >Lookup: node=Private/, err=<nil>
2020/12/12 20:42:35 DEBUG : Private/: Attr: 
2020/12/12 20:42:35 DEBUG : Private/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-x---, err=<nil>
2020/12/12 20:42:35 DEBUG : /: Lookup: name="Scripts"
2020/12/12 20:42:35 DEBUG : /: >Lookup: node=Scripts/, err=<nil>
2020/12/12 20:42:35 DEBUG : Scripts/: Attr: 
2020/12/12 20:42:35 DEBUG : Scripts/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-x---, err=<nil>
2020/12/12 20:42:35 DEBUG : /: Lookup: name="Security"
2020/12/12 20:42:35 DEBUG : /: >Lookup: node=Security/, err=<nil>
2020/12/12 20:42:35 DEBUG : Security/: Attr: 
2020/12/12 20:42:35 DEBUG : Security/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-x---, err=<nil>
2020/12/12 20:42:35 DEBUG : /: Lookup: name="log.txt"
2020/12/12 20:42:35 DEBUG : /: >Lookup: node=log.txt, err=<nil>
2020/12/12 20:42:35 DEBUG : log.txt: Attr: 
2020/12/12 20:42:35 DEBUG : log.txt: >Attr: a=valid=1s ino=0 size=1555 mode=-rw-r-----, err=<nil>
2020/12/12 20:42:35 DEBUG : /: Lookup: name="text.txt"
2020/12/12 20:42:35 DEBUG : /: >Lookup: node=text.txt, err=<nil>
2020/12/12 20:42:35 DEBUG : text.txt: Attr: 
2020/12/12 20:42:35 DEBUG : text.txt: >Attr: a=valid=1s ino=0 size=24 mode=-rw-r-----, err=<nil>
2020/12/12 20:42:35 DEBUG : /: Attr: 
2020/12/12 20:42:35 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-x---, err=<nil>
2020/12/12 20:42:35 DEBUG : /: ReadDirAll: 
2020/12/12 20:42:35 DEBUG : /: >ReadDirAll: item=7, err=<nil>
2020/12/12 20:42:35 DEBUG : /: Attr: 
2020/12/12 20:42:35 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-x---, err=<nil>
2020/12/12 20:42:35 DEBUG : test/: ReadDirAll: 
2020/12/12 20:42:35 DEBUG : test/: >ReadDirAll: item=2, err=<nil>
2020/12/12 20:42:35 DEBUG : test/: Attr: 
2020/12/12 20:42:35 DEBUG : test/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-x---, err=<nil>
2020/12/12 20:42:35 DEBUG : /: Lookup: name="test"
2020/12/12 20:42:35 DEBUG : /: >Lookup: node=test/, err=<nil>
2020/12/12 20:42:35 DEBUG : test/: Attr: 
2020/12/12 20:42:35 DEBUG : test/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-x---, err=<nil>
2020/12/12 20:42:35 DEBUG : &{test/test.md (rw)}: Release: 
2020/12/12 20:42:35 DEBUG : test/test.md(0xc0000a1d40): RWFileHandle.Release
2020/12/12 20:42:35 DEBUG : test/test.md(0xc0000a1d40): close: 
2020/12/12 20:42:35 DEBUG : vfs cache: looking for range={Pos:0 Size:0} in [] - present true
2020/12/12 20:42:35 DEBUG : test/: Lookup: name="test.md"
2020/12/12 20:42:35 DEBUG : test/: >Lookup: node=test/test.md, err=<nil>
2020/12/12 20:42:35 DEBUG : test/test.md: Attr: 
2020/12/12 20:42:35 DEBUG : test/test.md: vfs cache: setting modification time to 2020-12-12 20:42:34.809802328 +0100 CET m=+12.451995524
2020/12/12 20:42:35 INFO  : test/test.md: vfs cache: queuing for upload in 5s
2020/12/12 20:42:35 DEBUG : test/test.md(0xc0000a1d40): >close: err=<nil>
2020/12/12 20:42:35 DEBUG : &{test/test.md (rw)}: >Release: err=<nil>
2020/12/12 20:42:35 DEBUG : test/test.md: >Attr: a=valid=1s ino=0 size=0 mode=-rw-r-----, err=<nil>
2020/12/12 20:42:35 DEBUG : test/test.md: Setattr: a=Setattr [ID=0x40 Node=0x3 Uid=1000 Gid=100 Pid=11722] atime=2020-12-12 20:42:34.809802328 +0100 CET mtime=2020-12-12 20:42:35.588013361 +0100 CET handle=INVALID-0x0
2020/12/12 20:42:35 DEBUG : test/test.md: vfs cache: setting modification time to 2020-12-12 20:42:35.588013361 +0100 CET
2020/12/12 20:42:36 DEBUG : test/test.md: Applied pending mod time 2020-12-12 20:42:35.588013361 +0100 CET OK
2020/12/12 20:42:36 DEBUG : test/test.md: >Setattr: err=<nil>
2020/12/12 20:42:36 DEBUG : test/test.md: Attr: 
2020/12/12 20:42:36 DEBUG : test/test.md: >Attr: a=valid=1s ino=0 size=0 mode=-rw-r-----, err=<nil>
2020/12/12 20:42:36 DEBUG : test/.~test.md: Attr: 
2020/12/12 20:42:36 DEBUG : test/.~test.md: >Attr: a=valid=1s ino=0 size=0 mode=-rw-r-----, err=<nil>
2020/12/12 20:42:36 DEBUG : test/: Lookup: name="._.~test.md"
2020/12/12 20:42:36 DEBUG : test/: >Lookup: node=<nil>, err=no such file or directory
2020/12/12 20:42:36 DEBUG : test/: ReadDirAll: 
2020/12/12 20:42:36 DEBUG : test/: >ReadDirAll: item=2, err=<nil>
2020/12/12 20:42:36 DEBUG : test/: Attr: 
2020/12/12 20:42:36 DEBUG : test/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-x---, err=<nil>
2020/12/12 20:42:36 DEBUG : test/: Lookup: name="._.~test.md"
2020/12/12 20:42:36 DEBUG : test/: >Lookup: node=<nil>, err=no such file or directory
2020/12/12 20:42:36 DEBUG : test/: Lookup: name="._.~test.md"
2020/12/12 20:42:36 DEBUG : test/: >Lookup: node=<nil>, err=no such file or directory
2020/12/12 20:42:36 DEBUG : test/: Remove: name=".~test.md"
2020/12/12 20:42:36 DEBUG : test/.~test.md: Remove: 
2020/12/12 20:42:36 DEBUG : test/.~test.md: vfs cache: cancelling writeback (uploading false) 0xc00032c1c0 item 1
2020/12/12 20:42:36 INFO  : test/.~test.md: vfs cache: removed cache file as file deleted
2020/12/12 20:42:36 DEBUG : test/.~test.md: vfs cache: removed metadata from cache as file deleted
2020/12/12 20:42:36 DEBUG : test: Added virtual directory entry vDel: ".~test.md"
2020/12/12 20:42:36 DEBUG : test/.~test.md: >Remove: err=<nil>
2020/12/12 20:42:36 DEBUG : test/: >Remove: err=<nil>
2020/12/12 20:42:36 DEBUG : test/: Attr: 
2020/12/12 20:42:36 DEBUG : test/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-x---, err=<nil>
2020/12/12 20:42:36 DEBUG : test/: ReadDirAll: 
2020/12/12 20:42:36 DEBUG : test/: >ReadDirAll: item=1, err=<nil>
2020/12/12 20:42:36 DEBUG : test/: Attr: 
2020/12/12 20:42:36 DEBUG : test/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-x---, err=<nil>
2020/12/12 20:42:36 DEBUG : /: ReadDirAll: 
2020/12/12 20:42:36 DEBUG : /: >ReadDirAll: item=7, err=<nil>
2020/12/12 20:42:36 DEBUG : /: Lookup: name="Other"
2020/12/12 20:42:36 DEBUG : /: >Lookup: node=Other/, err=<nil>
2020/12/12 20:42:36 DEBUG : Other/: Attr: 
2020/12/12 20:42:36 DEBUG : Other/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-x---, err=<nil>
2020/12/12 20:42:36 DEBUG : /: Lookup: name="Private"
2020/12/12 20:42:36 DEBUG : /: >Lookup: node=Private/, err=<nil>
2020/12/12 20:42:36 DEBUG : Private/: Attr: 
2020/12/12 20:42:36 DEBUG : Private/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-x---, err=<nil>
2020/12/12 20:42:36 DEBUG : /: Lookup: name="Scripts"
2020/12/12 20:42:36 DEBUG : /: >Lookup: node=Scripts/, err=<nil>
2020/12/12 20:42:36 DEBUG : Scripts/: Attr: 
2020/12/12 20:42:36 DEBUG : Scripts/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-x---, err=<nil>
2020/12/12 20:42:36 DEBUG : /: Lookup: name="Security"
2020/12/12 20:42:36 DEBUG : /: >Lookup: node=Security/, err=<nil>
2020/12/12 20:42:36 DEBUG : Security/: Attr: 
2020/12/12 20:42:36 DEBUG : Security/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-x---, err=<nil>
2020/12/12 20:42:36 DEBUG : /: Lookup: name="log.txt"
2020/12/12 20:42:36 DEBUG : /: >Lookup: node=log.txt, err=<nil>
2020/12/12 20:42:36 DEBUG : log.txt: Attr: 
2020/12/12 20:42:36 DEBUG : log.txt: >Attr: a=valid=1s ino=0 size=1555 mode=-rw-r-----, err=<nil>
2020/12/12 20:42:36 DEBUG : /: Lookup: name="text.txt"
2020/12/12 20:42:36 DEBUG : /: >Lookup: node=text.txt, err=<nil>
2020/12/12 20:42:36 DEBUG : text.txt: Attr: 
2020/12/12 20:42:36 DEBUG : text.txt: >Attr: a=valid=1s ino=0 size=24 mode=-rw-r-----, err=<nil>
2020/12/12 20:42:36 DEBUG : /: Attr: 
2020/12/12 20:42:36 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-x---, err=<nil>
2020/12/12 20:42:36 DEBUG : /: Lookup: name="test"
2020/12/12 20:42:36 DEBUG : /: >Lookup: node=test/, err=<nil>
2020/12/12 20:42:36 DEBUG : test/: Attr: 
2020/12/12 20:42:36 DEBUG : test/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-x---, err=<nil>
2020/12/12 20:42:36 DEBUG : test/: Lookup: name="test.md"
2020/12/12 20:42:36 DEBUG : test/: >Lookup: node=test/test.md, err=<nil>
2020/12/12 20:42:36 DEBUG : test/test.md: Attr: 
2020/12/12 20:42:36 DEBUG : test/test.md: >Attr: a=valid=1s ino=0 size=0 mode=-rw-r-----, err=<nil>
2020/12/12 20:42:36 DEBUG : test/test.md: Open: flags=OpenReadOnly
2020/12/12 20:42:36 DEBUG : test/test.md: Open: flags=O_RDONLY
2020/12/12 20:42:36 DEBUG : test/test.md: newRWFileHandle: 
2020/12/12 20:42:36 DEBUG : test/test.md: >newRWFileHandle: err=<nil>
2020/12/12 20:42:36 DEBUG : test/test.md: >Open: fd=test/test.md (rw), err=<nil>
2020/12/12 20:42:36 DEBUG : test/test.md: >Open: fh=&{test/test.md (rw)}, err=<nil>
2020/12/12 20:42:37 DEBUG : test/: ReadDirAll: 
2020/12/12 20:42:37 DEBUG : test/: >ReadDirAll: item=1, err=<nil>
2020/12/12 20:42:37 DEBUG : test/: Attr: 
2020/12/12 20:42:37 DEBUG : test/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-x---, err=<nil>
2020/12/12 20:42:40 DEBUG : test/test.md: vfs cache: starting upload
2020/12/12 20:42:41 DEBUG : test/test.md: MD5 = d41d8cd98f00b204e9800998ecf8427e OK
2020/12/12 20:42:41 INFO  : test/test.md: Copied (replaced existing)
2020/12/12 20:42:41 DEBUG : test/test.md: vfs cache: fingerprint now "0,2020-12-12 19:42:35.588 +0000 UTC,d41d8cd98f00b204e9800998ecf8427e"
2020/12/12 20:42:41 DEBUG : test/test.md: vfs cache: writeback object to VFS layer
2020/12/12 20:42:41 DEBUG : test: Added virtual directory entry vAddFile: "test.md"
2020/12/12 20:42:41 INFO  : test/test.md: vfs cache: upload succeeded try #1
2020/12/12 20:42:47 DEBUG : &{test/test.md (rw)}: Flush: 
2020/12/12 20:42:47 DEBUG : test/test.md(0xc000152440): RWFileHandle.Flush
2020/12/12 20:42:47 DEBUG : &{test/test.md (rw)}: >Flush: err=<nil>
2020/12/12 20:42:47 DEBUG : &{test/test.md (rw)}: Release: 
2020/12/12 20:42:47 DEBUG : test/test.md(0xc000152440): RWFileHandle.Release
2020/12/12 20:42:47 DEBUG : test/test.md(0xc000152440): close: 
2020/12/12 20:42:47 DEBUG : test/test.md(0xc000152440): >close: err=<nil>
2020/12/12 20:42:47 DEBUG : &{test/test.md (rw)}: >Release: err=<nil>
```

I can see here it is being truncated (line 98 - 101), but why is hard to get.
```
2020/12/12 20:42:34 DEBUG : test/test.md: vfs cache: truncate to size=9044
2020/12/12 20:42:34 DEBUG : test: Added virtual directory entry vAddFile: "test.md"
2020/12/12 20:42:34 DEBUG : test/test.md(0xc0000a1d40): >openPending: err=<nil>
2020/12/12 20:42:34 DEBUG : test/test.md: vfs cache: truncate to size=0
```

**Comment by ncw** [comment]
> I also tried the following script with various delays to see if I could reproduce the problem, but with this script I could never reproduce it. Perhaps because it just concatenates to a file.

I think that is right. I tried a similar thing when trying to reproduce the problem originally.



> The original problem I have: when I save a file with typora via rclone on google drive, it says "save failed" and the file is immediately truncated (example here: test.md). I have included the rclone logfile with -vv. Perhaps you can see why this is happening (btw typora is also available under linux). If I could find another way to reproduce it, I would ;-)

I can't see anyting obviously wrong with that log. There are no errors returned and the save appears to go OK.

I'll try installing typora later (I'm in the car at the moment), but if you could strace typora around the time that it fails that would be really useful. So run `strace typora` and get to the point just before you save, then what I do is type a whole lot of returns in the terminal to leave a gap, then do the save then more returns in the terminal.  Then paste the middle bit between the returns here!

**Comment by Piscator74** [comment]
I have been trying the same test over "pcloud" instead of "googledrive" with the following script:
Looking just at the changing timestamps (about file corruptions, see my next reply)

```
#!/bin/bash

trap "pkill test.sh" SIGINT

rm text.txt
( while true ; do echo "write now!" && (echo hello >> text.txt) ; sleep 10.0 ; done ) &

( while true ; do ls -l --full-time text.txt ; sleep 1 ; done )| tee log.txt
```

```
-rw-r----- 1 user none 0 2020-12-24 11:20:47.692544499 +0100 text.txt
-rw-r----- 1 user none 6 2020-12-24 11:20:47.712308715 +0100 text.txt
-rw-r----- 1 user none 6 2020-12-24 11:20:47.712308715 +0100 text.txt
-rw-r----- 1 user none 6 2020-12-24 11:20:47.712308715 +0100 text.txt
-rw-r----- 1 user none 6 2020-12-24 11:20:47.712308715 +0100 text.txt
-rw-r----- 1 user none 6 2020-12-24 11:20:47.712308715 +0100 text.txt
-rw-r----- 1 user none 6 2020-12-24 11:20:47.000000000 +0100 text.txt   <--  timestamp rounded down to full second
-rw-r----- 1 user none 6 2020-12-24 11:20:47.000000000 +0100 text.txt
-rw-r----- 1 user none 6 2020-12-24 11:20:47.000000000 +0100 text.txt
-rw-r----- 1 user none 6 2020-12-24 11:20:47.000000000 +0100 text.txt
write now!
-rw-r----- 1 user none 12 2020-12-24 11:20:57.735646885 +0100 text.txt
-rw-r----- 1 user none 12 2020-12-24 11:20:57.735646885 +0100 text.txt
-rw-r----- 1 user none 12 2020-12-24 11:20:57.735646885 +0100 text.txt
-rw-r----- 1 user none 12 2020-12-24 11:20:57.735646885 +0100 text.txt
-rw-r----- 1 user none 12 2020-12-24 11:20:57.735646885 +0100 text.txt
-rw-r----- 1 user none 12 2020-12-24 11:20:57.735646885 +0100 text.txt
-rw-r----- 1 user none 12 2020-12-24 11:20:57.000000000 +0100 text.txt   <--  timestamp rounded down to full second
-rw-r----- 1 user none 12 2020-12-24 11:20:57.000000000 +0100 text.txt
-rw-r----- 1 user none 12 2020-12-24 11:20:57.000000000 +0100 text.txt
-rw-r----- 1 user none 12 2020-12-24 11:20:57.000000000 +0100 text.txt
write now!
-rw-r----- 1 user none 18 2020-12-24 11:21:07.751840591 +0100 text.txt
-rw-r----- 1 user none 18 2020-12-24 11:21:07.751840591 +0100 text.txt
-rw-r----- 1 user none 18 2020-12-24 11:21:07.751840591 +0100 text.txt
-rw-r----- 1 user none 18 2020-12-24 11:21:07.751840591 +0100 text.txt
-rw-r----- 1 user none 18 2020-12-24 11:21:07.751840591 +0100 text.txt
-rw-r----- 1 user none 18 2020-12-24 11:21:07.000000000 +0100 text.txt     <--  timestamp rounded down to full second
-rw-r----- 1 user none 18 2020-12-24 11:21:07.000000000 +0100 text.txt
-rw-r----- 1 user none 18 2020-12-24 11:21:07.000000000 +0100 text.txt
```

Of course, the rounding is different than with google drive ;-)
How do you plan to cope with these changing timestamps?
* Rounding the time in the cache back-end so it matches with the specific cloud storage?

**Comment by Piscator74** [comment]
About the file truncations / corruptions.
With the following scenario, I always get corrupted files. This is perhaps easier to reproduce. 
* Mount cloud drive with rclone on Server (with caching settings as discussed above)
* Share the folder over Samba / Windows File Sharing
* On a client machine, copy files over Samba to the rclone mount.
* Files always get corrupted. This applies both for Windows and Ubuntu clients. Sometimes I get the not so helpful error (on the Windows machine): "**error 0x80070032: The request is not supported**". I have tried it both with CacheMode 3 and CacheMode 0. So, it has likely nothing to do with the caching mechanism.

I am not sure why I have not seen this before, since this is rather basic. It looks like rclone does not work together with samba when writing. Reading files over Samba is no problem. Copying files locally obviously works flawlessly.

I have tested the same behavior with:
* rclone 1.53.3
* rclone v1.54.0-beta.4957.145e62446.fix-4763-vfs-modtime

**Comment by ncw** [comment]
I've seen various reports of Go programs not interacting properly with samba. It seems to be a linux kernel bug. You can work around with `export GODEBUG=asyncpreemptoff=1` - can you try this and see if you can still reproduce the file corruption?

**Comment by Piscator74** [comment]
Unfortunately, it does not make any difference. Thanks for the suggestion. I have Linux kernel version 4.2.8.

This is the script I tested with:
```
#!/bin/bash
AUTH="--rc-user=$USERNAME --rc-pass=$PASSWORD"

export GODEBUG=asyncpreemptoff=1

./rclone rcd -vv --log-file=log.txt --rc-web-gui --rc-web-gui-no-open-browser --cache-dir /share/cloud/user/.cache --rc-addr :5572 $AUTH &
sleep 5

./rclone rc options/set --json '{"main": { "Transfers": 4 }, "vfs" : {"UID": '$PUID', "GID": '$PGID', "Umask": 23, "CacheMode": 3, "CacheMaxAge": 31622400000000000, "DirCacheTime": 31536000000000000}, "mount": {"AllowOther": true}}' $AUTH
./rclone rc mount/mount fs=googledrive: mountPoint=/share/cloud/user/googledrive $AUTH
```

**Comment by BlowflyOZ** [comment]
I can replicate this VFS strangeness  When copying files through samba to a VFS cache shared by samba I consistently see 0x80070032 "the request is not supported". 

Files or directories at first begin to copy from explorer but then then fail with "an unexpected error is keeping you from copying..." 

Copied files from this cannot be deleted or moved from windows and linux shell must be used to clean up. 

Samba works perfectly (same setup I've used in years) to the same raspi but to NON VFS shares. 0x80070032 issue and corruption only occurs with VFS cache shared by samba.

my setup to reproduce is as follows:
client: fresh install from win10 20H2 iso with critical updates to date
server: raspian buster fully updated 
samba 4.9.5
rclone 1.53.3 or 1.53.4 (issues happens with both versions)

rclone config: 
	--vfs-cache-mode full \
        --cache-tmp-upload-path=/home/pi/.rclone_sync_cache \
        --cache-tmp-wait-time 10m0s \
	--cache-db-path=/home/pi/.rclone_cache_db \
        --cache-dir=/home/pi/.rclone_cache_db \
        --allow-other \
        --dir-cache-time 5m \
	--cache-info-age 1h \
	--vfs-cache-max-age 2h \
        --vfs-read-chunk-size 64m \
        --buffer-size 256m \
        --vfs-read-ahead 1g \
	--cache-chunk-size 16m \
        --cache-chunk-total-size 500g \
	--cache-db-wait-time 0m3s \

smb.conf:
global]

workgroup = WORKGROUP
log file = /var/log/samba/log.%m
max log size = 1000
logging = file
panic action = /usr/share/samba/panic-action %d
server role = standalone server
obey pam restrictions = yes
unix password sync = yes
passwd program = /usr/bin/passwd %u
passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .
pam password change = yes
map to guest = bad user
usershare max shares = 0
usershare allow guests = yes
min protocol = SMB2

#======================= Share Definitions =======================

[OneDrive]
   comment = OneDrive Personal VFS Cache
   path = /home/pi/4TBNAS/OneDriveVFS
   browseable = yes
   read only = no
   create mask = 0777
   directory mask = 0777
   valid users = pi, david
   force user = pi
   guest ok = no
   hosts allow = x.x.x.x/24 127.0.0.1

I hope this helps....

**Comment by ncw** [comment]
This is very likely a samba bug or a linux kernel bug... Can you try upgrading (maybe build from source) samba / the linux kernel?

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.55

**Comment by Piscator74** [comment]
Thanks for the update. I assume this is only a fix for the mod-times bugs? I will check it out.
Do you have any info on what kernel versions / samba versions the samba issue in combination with "Go programs" are applicable?

**Comment by ncw** [comment]
Yes it is a fix for the mod times issues.

I think the go team have worked around the samba issues, so rclone compiled with go1.16 should be OK. So the beta should be OK and v1.55 when it is released.

**Comment by Piscator74** [comment]
I have checked the mod times issues (on GoogleDrive, Dropbox and pcloud) and those seem to be fixed. Thanks, that looks like to be working as expected.

However, when I try to copy large files over Samba to rclone, still incorrect things happen. I have been trying to copy a single zip file of roughly 170MB.
*  When "CacheMode": 3. I get a network error after a while (after at most 14% of the transfer, but sometimes also after 2%). The file in the target has the correct size, but is corrupt.
*  When "CacheMode": 0. The file seems to be copying correctly, but very slowly. It copies around 30 KBps, while my internet upload speed is roughly 10 Mbps.

**Comment by ncw** [comment]
@Piscator74 can you make a new issue about the Samba problem - include full info on how to replicate the problem - thanks!

**Comment by Piscator74** [comment]
Done. See issue: https://github.com/rclone/rclone/issues/5163
