### ISSUE TITLE
A way to make Rclone run in the background on Windows

### ISSUE THREAD

**Issue by fxzxmic** [rclone/rclone#5175]
Sorry, I don't know if this issue is repeated with others, but I don't find any relevant statements or methods in the official documents.

#### What is your current rclone version (output from `rclone version`)?
v1.55.0-beta.5343.9c9186183

#### What problem are you are trying to solve?
Make Rclone run in the background on Windows.

#### How do you think rclone should be changed to solve that?
Using VBS scripts is the viable approach I found.
For example, my VBS script is: 
```
DIM Temp
DIM Command
DIM Path
DIM Remote_Path
Quotation=chr(34)
Temp = "D:/Rclone Temp"
Set WS = Wscript.CreateObject("Wscript.Shell")

Remote_Path = "Onedrive_Personal:/Storage/"
Path = "A:"
Command = "rclone mount " & Quotation & Remote_Path & Quotation & " " & Quotation & Path & Quotation & " --cache-dir " & Quotation & Temp & Quotation & " --transfers 16 --buffer-size 32M --vfs-cache-mode writes --volname \\Local\onedrive"
WS.Run Command, 0
```
It does work: 
![image](https://user-images.githubusercontent.com/54622331/112752652-98a3b080-9006-11eb-92d8-bfda7af5e861.png)

**Comment by albertony** [comment]
There was a discussion in the forum where some options are mentioned, including the VBScript approach similar to yours, see: 
- https://forum.rclone.org/t/autostart-mount-on-windows-without-cmd-popping-up/20896

Then, after that we added a command line argument `--no-console`, which should be available in latest version of rclone. See:
- https://github.com/rclone/rclone/pull/4953
- https://rclone.org/flags/

I don't know if you have seen these? Do you think there should be more done, with regards to functionality and/or documentation?

I have started a pull request for detailed documentation of automatic running of rclone, which includes running in background but with main focus on starting on windows startup or on schedule etc.. My attempt has sort of stranded, though, because it turned out to be difficult to find a consistent behavior accross different versions of Windows etc, and then a detailed doc like this needs to considere these differences - or be rewritten to be much less detailed. See:
- https://github.com/rclone/rclone/pull/4972

**Comment by fxzxmic** [comment]
https://rclone.org/commands/rclone_mount/
It's mentioned: `You can only run mount in foreground mode on Windows.`
So I don't know the new way.

**Comment by albertony** [comment]
I see, that can be a bit confusing. But that sentence is related to the `--daemon` flag and internals of the mount command (don't know enough of the details myself). The `--no-console` flag, and the other "third party" methods discussed in the forum thread, are unrelated to this, as these will just hide the console window that rclone creates, while doing nothing with how the process itself runs (which I think the `--deamon` option does).

**Comment by fxzxmic** [comment]
OK, I see. Although VBS scripts are also useful, Rclone itself can solve this problem better. Or you can use VBS as a common method for all Windows versions (I don't know about it, and I don't know if it's possible 🤣).

**Comment by ivandeex** [comment]
I don't think we will implement `--daemon` flag on Windows as is, the Unix daemon semantics is too different from a Windows service.
Currently a good solution is to use [nssm](https://nssm.cc/). It may be partially described in rclone docs by PR #4972 when it gets merged.

If we ever decide to embed the Windows service feature in rclone, we can probably base it on one of the following:
- [golang's windows.svc example](https://github.com/golang/sys/blob/master/windows/svc/example/install.go#L49)
- [golang's windows.svc.mgr](https://pkg.go.dev/golang.org/x/sys@v0.0.0-20200926100807-9d91bd62050c/windows/svc/mgr#Mgr.CreateService)
- [billgraziano/go-windows-svc](https://github.com/billgraziano/go-windows-svc)

Even on Linux the `--daemon` flag currently doesn't work with the `mount` command or in the `--rc` mode. It will be fixed by the relevant tickets (#2968, #2618).

**Comment by ivandeex** [comment]
- Related to https://github.com/billziss-gh/winfsp/wiki/WinFsp-Service-Architecture
- Related to https://github.com/rclone/rclone/issues/3340
- Related to https://github.com/rclone/rclone/issues/3216

**Comment by fxzxmic** [comment]
Okay, thank you. Do I need to close this Issue? Or keep it open? I think my goal has been reached and my question has been resolved.

**Comment by ivandeex** [comment]
Another workaround was published by you at https://translate.google.com/translate?sl=zh-CN&tl=en&u=https://fxic.iblog.ink/articles/page/147.html
A number of other solutions can be extracted from https://forum.rclone.org/

**Comment by fxzxmic** [comment]
> Another workaround was published by you at https://translate.google.com/translate?sl=zh-CN&tl=en&u=https://fxic.iblog.ink/articles/page/147.html
> A number of other solutions can be extracted from https://forum.rclone.org/

EDIT: new domain: https://fxzx.iblog.ink/articles/page/147.html

Ha ha, you found it. Thanks. 😂🤣

**Comment by MaxJahWn** [comment]
I‘ve configured 
`powershell -Command "Start-Process -FilePath rclone -WindowStyle hidden -ArgumentList \"mount MyWebdav: Z: --network-mode {{other arguments}}\""`
in taskschd.msc, it works well.

**Comment by fredinj** [comment]
Kinda sad that this still isn't supported by default.

Using task scheduler is good, but unmounting is a pain, using a windows service is easier as you can just stop the service and it'll unmount properly. Setting up a regular service is almost perfect for me. But it might not be desirable if you have multiple users in your PC.

    $params = @{
      Name = "TestService"
      BinaryPathName = "rclone-path arguements"
      DisplayName = "Rclone"
      StartupType = "Automatic"
      Description = "This is a test service."
      Credential = "DOMAIN\USER"
    }
    New-Service @params

I had to run the service with user credentials or rclone wouldn't write to existing files. But this is the best workaround I've found yet.

**Comment by fxzxmic** [comment]
> Kinda sad that this still isn't supported by default.
> 
> Using task scheduler is good, but unmounting is a pain, using a windows service is easier as you can just stop the service and it'll unmount properly. Setting up a regular service is almost perfect for me. But it might not be desirable if you have multiple users in your PC.
> 
> ```
> $params = @{
>   Name = "Rclone-Mount"
>   BinaryPathName = "rclone-path arguements"
>   DisplayName = "Rclone"
>   StartupType = "Automatic"
>   Description = "This is a test service."
>   Credential = "DOMAIN\USER"
> }
> New-Service @params
> ```
> 
> I had to run the service with user credentials or rclone wouldn't write to existing files. But this is the best workaround I've found yet, no flashing cmd either.

I’m glad you shared your method.

**Comment by Kein** [comment]
> Then, after that we added a command line argument `--no-console`, which should be available in latest version of rclone. See:

It does not work under Windows, it opens cmd prompt asking to run under cmd/shell

**Comment by albertony** [comment]
@Kein : I'm not sure if this is what you refer to, but rclone is still a console application, so even with `--no-console` it will in fact still need to allocate a console, only to hide it early on in the application's initialization code. Please share more details, show an example, if you meant something else or have further questions.

**Comment by DawnImpulse** [comment]
I have found a way to basically start any cli service in background - https://github.com/jeansaad/chalet
Using this tool we can configure any cli command & use it in background (only caveat is you have to start it after every PC restart)

also for a simple tray icon to start/stop services - https://github.com/macav/hotelier

**Comment by ANDiTKO** [comment]
Here is alternative solution that does not require a service, only 2 files.

Fist you need the mount command. For that we will use a .bat file.  Lets call it **mount_cloud.bat** Here is the sample code:

```
@echo off
rclone mount cloud: W: --vfs-cache-mode full --no-console --vfs-cache-max-size 50G --vfs-cache-max-age 24h
``` 
dont forget to replace replace **cloud:** with your remote name, and **W:** with the drive letter that you want to assign to your drive.
this will run your rclone mount command with the --no-console parameter so it won't have a console window open.

Then we need a VBS script that will run the command for you. So the terminal window will remain hidden.
Lets call the second file **mount_rclone.vbs** here is the code:

```
Set WshShell = CreateObject("WScript.Shell")
WshShell.Run chr(34) & "C:\rclone\mount_cloud.bat" & chr(34), 0
Set WshShell = Nothing
``` 

Replace the **C:\rclone\mount_cloud.bat** with the correct path where you stored the previous file.
You can also copy/paste the second line if you want to mount multiple drives at once.

Then in Windows Task Scheduler run the mount_rclone.vbs after you logon or whenever you want this to be triggered. (I think that if you make a shortcut in startitems will work too, but I haven't tried it)
And you can make your windows mount automatically your rclones and it will stay in the background. 
No console windows. No services. Just files.

**Comment by fxzxmic** [comment]
Since Windows will deprecate VBS, the only way to make Rclone run in the background in the future is to use a service.

**Comment by jason-eu** [comment]
> Here is alternative solution that does not require a service, only 2 files.
> 
> Fist you need the mount command. For that we will use a .bat file. Lets call it **mount_cloud.bat** Here is the sample code:
> 
> ```
> @echo off
> rclone mount cloud: W: --vfs-cache-mode full --no-console --vfs-cache-max-size 50G --vfs-cache-max-age 24h
> ```
> 
> dont forget to replace replace **cloud:** with your remote name, and **W:** with the drive letter that you want to assign to your drive. this will run your rclone mount command with the --no-console parameter so it won't have a console window open.
> 
> Then we need a VBS script that will run the command for you. So the terminal window will remain hidden. Lets call the second file **mount_rclone.vbs** here is the code:
> 
> ```
> Set WshShell = CreateObject("WScript.Shell")
> WshShell.Run chr(34) & "C:\rclone\mount_cloud.bat" & chr(34), 0
> Set WshShell = Nothing
> ```
> 
> Replace the **C:\rclone\mount_cloud.bat** with the correct path where you stored the previous file. You can also copy/paste the second line if you want to mount multiple drives at once.
> 
> Then in Windows Task Scheduler run the mount_rclone.vbs after you logon or whenever you want this to be triggered. (I think that if you make a shortcut in startitems will work too, but I haven't tried it) And you can make your windows mount automatically your rclones and it will stay in the background. No console windows. No services. Just files.

THANK YOU !

**Comment by DankestFke** [comment]
> Here is alternative solution that does not require a service, only 2 files.
> 
> Fist you need the mount command. For that we will use a .bat file. Lets call it **mount_cloud.bat** Here is the sample code:
> 
> ```
> @echo off
> rclone mount cloud: W: --vfs-cache-mode full --no-console --vfs-cache-max-size 50G --vfs-cache-max-age 24h
> ```
> 
> dont forget to replace replace **cloud:** with your remote name, and **W:** with the drive letter that you want to assign to your drive. this will run your rclone mount command with the --no-console parameter so it won't have a console window open.
> 
> Then we need a VBS script that will run the command for you. So the terminal window will remain hidden. Lets call the second file **mount_rclone.vbs** here is the code:
> 
> ```
> Set WshShell = CreateObject("WScript.Shell")
> WshShell.Run chr(34) & "C:\rclone\mount_cloud.bat" & chr(34), 0
> Set WshShell = Nothing
> ```
> 
> Replace the **C:\rclone\mount_cloud.bat** with the correct path where you stored the previous file. You can also copy/paste the second line if you want to mount multiple drives at once.
> 
> Then in Windows Task Scheduler run the mount_rclone.vbs after you logon or whenever you want this to be triggered. (I think that if you make a shortcut in startitems will work too, but I haven't tried it) And you can make your windows mount automatically your rclones and it will stay in the background. No console windows. No services. Just files.

Didn't work. Pretty sure it didn't launch because the console closed.

**Comment by albertony** [comment]
@fxzxmic What do you think is still missing in rclone?

As I see it, simply starting rclone with `--no-console` is a ready to use, super easy solution to this. The built-in support for installing rclone as a Windows service, using PowerShell's `New-Service` command, is almost just as easy, if you want more automated execution. This is all documentation at https://rclone.org/install/#autostart now. And in addition, classic Windows tricks with Windows/VB Script, PowerShell, or something else is well covered in rclone forum, and on the internet in general. I fail to see a need for anything more? But I may be missing some specific detail, specific use case, or something?

**Comment by saintech** [comment]
There is also this way using the scheduler:
```
conhost --headless c:\rclone\rclone.exe sync c:\files remote:/files --log-file c:\rclone\logs\sync_files.txt
```
