### ISSUE TITLE
ncdu: handling specials

### ISSUE THREAD

**Issue by jtagcat** [rclone/rclone#6088]
From https://github.com/rclone/rclone/issues/3369

Currently, special files are treated as empty directories, in both:
 - listings (`rclone ncdu /dev/cpu`)
   - Warnings _are_ shown for errors listing them.
 - root dirs (`rclone ncdu /dev/full`)
   - It is opened as empty directory.

I'd say it's a papercut, and niche, as rclone ncdu is expected to operate on cloud remotes, that don't (?) have special files. Feel free to ignore-close.

**Comment by ncw** [comment]
> Currently, special files are treated as empty directories, in both:
> 
> * listings (`rclone ncdu /dev/cpu`)

`/dev/cpu` appears to be a directory so I'd say that is working

>   * Warnings _are_ shown for errors listing them.
> * root dirs (`rclone ncdu /dev/full`)
>   
>   * It is opened as empty directory.

This is possibly a larger bug / misfeature of `rclone ncdu` but you can run `rclone ncdu /path/to/a/file` and it won't complain, it will just show you a directory listing with a single file in. That is what is happening with `/dev/full` - it is just showing you a single file.

Whether that is a sensible thing to do, I'm not sure but `ncdu` blows up immediately with `not a directory` errors so if we are following that lead we should fix it.

However most things in rclone have that behaviour - if you pass a file, you get a directory with just that file in - so it is consistent with other commands.

@albertony thoughts?

**Comment by albertony** [comment]
This is a bit confusing...

Is what you are saying that we could make `rclone ncdu` more compatible with "native" `ncdu` by making it only accept directories as input? That could be an option, not decided yet what I would prefer.

> That is what is happening with /dev/full - it is just showing you a single file.

I don't think that is true:

`rclone ncdu emptydir` succeeds, is rooted (titlebar) at "emptydir" and shows empty list.
`rclone ncdu README.md` succeeds, is rooted at parent (current) directory and lists this single file.
`rclone ncdu /dev/full` succeeds, but is rooted at /dev/full and shows empty list. As if /dev/null was an empty directory.

Also, there is some more confusion as to how to handle non-regular files:

`rclone ls /dev/full` blows up with "not a directory".
`rclone ncdu /dev/full` succeeds, but is rooted at /dev/full and shows empty list. As if /dev/null was an empty directory.

In the local backend's NewFs it returns ErrorIsFile only if the given path is to a *regular* file. `rclone ls` will therefore try to traverse it and fail. If i change local's NewFs so that it returns ErrorIsFile also for devices, both ls and ncdu with argument "/dev/full" will move up to /dev, but will not give any results and instead log notice "Can't transfer non file/directory" for each item. I.e. ncdu is rooted at /dev and shows empty list. Would this be more "correct" and consistent behavior of rclone? But still not consistent with native ncdu..

**Comment by ncw** [comment]
> This is a bit confusing...
> 
> Is what you are saying that we could make `rclone ncdu` more compatible with "native" `ncdu` by making it only accept directories as input?

Yes

> That could be an option, not decided yet what I would prefer.

No me neither. I don't think taking files is too terrible.

> > That is what is happening with /dev/full - it is just showing you a single file.
> 
> I don't think that is true:
> 
> `rclone ncdu emptydir` succeeds, is rooted (titlebar) at "emptydir" and shows empty list. `rclone ncdu README.md` succeeds, is rooted at parent (current) directory and lists this single file. `rclone ncdu /dev/full` succeeds, but is rooted at /dev/full and shows empty list. As if /dev/null was an empty directory.

What is happening is that `/dev/full` is being treated as a file so it kicks rclone into treating it as a directory with just a single file in. However the file object itself isn't included in directory listings

    2022/04/09 14:49:07 NOTICE: full: Can't transfer non file/directory

So it is a bit weird certainly! Probably the local backend file detection should be tightened up so if the root isn't a file or a directory it returns an error.

> Also, there is some more confusion as to how to handle non-regular files:
> 
> `rclone ls /dev/full` blows up with "not a directory". `rclone ncdu /dev/full` succeeds, but is rooted at /dev/full and shows empty list. As if /dev/null was an empty directory.
> 
> In the local backend's NewFs it returns ErrorIsFile only if the given path is to a _regular_ file. `rclone ls` will therefore try to traverse it and fail. If i change local's NewFs so that it returns ErrorIsFile also for devices, both ls and ncdu with argument "/dev/full" will move up to /dev, but will not give any results and instead log notice "Can't transfer non file/directory" for each item. I.e. ncdu is rooted at /dev and shows empty list. Would this be more "correct" and consistent behavior of rclone?

I think i should probably be returning `ErrorNotAFile` if you give it something which isn't a file or a directory at the root.

> But still not consistent with native ncdu..

Indeed!

**Comment by albertony** [comment]
> What is happening is that /dev/full is being treated as a file so it kicks rclone into treating it as a directory with just a single file in. However the file object itself isn't included in directory listings

> 2022/04/09 14:49:07 NOTICE: full: Can't transfer non file/directory

I still don't get this one. Do you mean you get that notice when running rclone ncdu against /dev/full? I don't. No notice logs. Just "local:/dev/null" in top line and empty list, exactly as if it was an empty directory. Only when I change the NewFs as mentioned do I get this notice, then for all "files" under /dev, as rclone ncdu tries to show /dev with full as filter, more like you describe.
