### ISSUE TITLE
If an upload has more than 10000 chunks, it fails and restarts infinitely

### ISSUE THREAD

**Issue by nexxai** [rclone/rclone#6436]
#### The associated forum post URL from `https://forum.rclone.org`
n/a

#### What is the problem you are having with rclone?
Uploading a large file (61,150,874,773 bytes / ~60GB) to S3

#### What is your rclone version (output from `rclone version`)
```
rclone v1.59.1
- os/version: Microsoft Windows Server 2022 Standard 21H2 (64 bit)
- os/kernel: 10.0.20348.946 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.18.5
- go/linking: static
- go/tags: cmount
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Windows Server 2022

#### Which cloud storage system are you using? (e.g. Google Drive)
Amazon S3

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
` rclone copy -P -vv '.\Holding On\' "paz-media-storage:paz-media-storage/Holding On"`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
2022-09-12 15:20:44 DEBUG : Paz - Holding On.mp4: multipart upload starting chunk 9991 size 5Mi offset 48.779Gi/56.951Gi
2022-09-12 15:20:45 DEBUG : Paz - Holding On.mp4: multipart upload starting chunk 9992 size 5Mi offset 48.784Gi/56.951Gi
2022-09-12 15:20:46 DEBUG : Paz - Holding On.mp4: multipart upload starting chunk 9993 size 5Mi offset 48.789Gi/56.951Gi
2022-09-12 15:20:48 DEBUG : Paz - Holding On.mp4: multipart upload starting chunk 9994 size 5Mi offset 48.794Gi/56.951Gi
2022-09-12 15:20:49 DEBUG : Paz - Holding On.mp4: multipart upload starting chunk 9995 size 5Mi offset 48.799Gi/56.951Gi
2022-09-12 15:20:49 DEBUG : Paz - Holding On.mp4: multipart upload starting chunk 9996 size 5Mi offset 48.804Gi/56.951Gi
2022-09-12 15:20:49 DEBUG : Paz - Holding On.mp4: multipart upload starting chunk 9997 size 5Mi offset 48.809Gi/56.951Gi
2022-09-12 15:20:51 DEBUG : Paz - Holding On.mp4: multipart upload starting chunk 9998 size 5Mi offset 48.813Gi/56.951Gi
2022-09-12 15:20:53 DEBUG : Paz - Holding On.mp4: multipart upload starting chunk 9999 size 5Mi offset 48.818Gi/56.951Gi
2022-09-12 15:20:53 DEBUG : Paz - Holding On.mp4: multipart upload starting chunk 10000 size 5Mi offset 48.823Gi/56.951Gi
2022-09-12 15:20:53 DEBUG : Paz - Holding On.mp4: multipart upload starting chunk 10001 size 5Mi offset 48.828Gi/56.951Gi
2022-09-12 15:20:53 DEBUG : pacer: low level retry 1/2 (error InvalidArgument: Part number must be an integer between 1 and 10000, inclusive
        status code: 400, request id: XXXXXXXXXXXXX, host id: BASE64STRINGHERE)
2022-09-12 15:20:53 DEBUG : pacer: Rate limited, increasing sleep to 10ms
2022-09-12 15:20:53 DEBUG : pacer: Reducing sleep to 0s
2022-09-12 15:20:53 DEBUG : Paz - Holding On.mp4: multipart upload starting chunk 10002 size 5Mi offset 48.833Gi/56.951Gi
2022-09-12 15:20:53 DEBUG : pacer: low level retry 2/2 (error InvalidArgument: Part number must be an integer between 1 and 10000, inclusive
        status code: 400, request id: XXXXXXXXXXXXX, host id: BASE64STRINGHERE
2022-09-12 15:20:53 DEBUG : pacer: Rate limited, increasing sleep to 10ms
2022-09-12 15:20:53 DEBUG : pacer: low level retry 1/2 (error RequestCanceled: request context canceled
caused by: context canceled)
2022-09-12 15:20:53 DEBUG : pacer: low level retry 1/2 (error RequestCanceled: request context canceled
caused by: context canceled)
2022-09-12 15:20:53 DEBUG : pacer: low level retry 1/2 (error RequestCanceled: request context canceled
caused by: context canceled)
2022-09-12 15:20:53 DEBUG : pacer: Rate limited, increasing sleep to 20ms
[CTRL-C]
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by nexxai** [comment]
After looking at the docs, it appears that there is a 10,000 chunk limit by design, but it would be nice if it threw up a warning prior to attempting the upload saying that the number of chunks exceeds the allowed limit, or even better, intelligently increased the chunk size so that it would "just work".

**Comment by nexxai** [comment]
Going further, according to https://rclone.org/s3/#s3-max-upload-parts:

> Rclone will automatically increase the chunk size when uploading a large file of a known size to stay below this number of chunks limit.

That does not seem to be the case here?  The source file is local to my machine and so it should be able to readily calculate the size.  I'm not sure what else to look at.

**Comment by nexxai** [comment]
Just confirmed that when specifying `--s3-chunk-size 10M` it uploaded correctly.

And just to confirm, I tried running the original command (without specifying a chunk size) from two different machines, running two different OSs (Windows and macOS) and both had the same issue of not calculating the chunksize automatically.

**Comment by ncw** [comment]
I think this was fixed in 0501773db13221171e102781809378a6555dd312 which you'll find in [the latest beta](https://beta.rclone.org/) - can you give that a go?

**Comment by animosity22** [comment]
I thought this was a duplicate and fixed as well in a beta, but I couldn't find it..

**Comment by nexxai** [comment]
Ugh, once I was able to push the file up to Deep Glacier with the increased chunk size, I deleted it from my local and I won't have any similar files to test with until this weekend.  Looking over the commit that @ncw linked, that will almost certainly fix my problem, so I'll close this issue for now, but if the beta doesn't solve the problem, I'll re-open.

Thanks for both of your help.
