### ISSUE TITLE
Box will not refresh OAuth2 with JWT

### ISSUE THREAD

**Issue by aselafernando** [rclone/rclone#7214]
#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/box-remote-wont-auto-refresh-access-token/40310/6

#### What is the problem you are having with rclone?
Referring to the [box API authentication documentation](https://developer.box.com/guides/authentication/select/) we have 4 authentication methods

1. Oauth2
2. Oauth2 with JWT
3. Client Credentials
4. App Tokens

The [documentation linked here](https://tip.rclone.org/box/#get-your-own-box-app-id) covers 1 using Oauth2 to allow rclone to act as you and therefore you cannot limit access to files in your own account: rclone has all or nothing.

My setup is using 2 where rclone authenticates with box and has a service account hence the **box_sub_type = enterprise**. This allows me to control what rclone can see using permissions. No refresh token is supplied with the Oauth2 flow as I think it is expected the API wants you to do the whole auth flow from scratch to get a new token. Sample code for the Oauth2 JWT flow without the box SDK is [here](https://github.com/box-community/samples-docs-authenticate-with-jwt-api) with [documentation](https://developer.box.com/guides/authentication/jwt/without-sdk/). This method is supported by rclone however does not seem to be working. In my debug log, the refresh does work at least once, it just doesn't happen twice in succession.

#### What is your rclone version (output from `rclone version`)
```
rclone v1.63.1
- os/version: debian 10.13 (64 bit)
- os/kernel: 4.19.0-25-amd64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.20.6
- go/linking: static
- go/tags: none
```
#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Debian 10 x64

#### Which cloud storage system are you using? (e.g. Google Drive)
Box

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone --log-level DEBUG --tpslimit 10 --tpslimit-burst 10 -P --box-box-config-file=/path/to/config.json --log-file=/tmp/box.log copy test.mkv box_enc_ch:test/upload/path

The file  is just over 10GB so is split into 3 parts by the chunker. THe upload is at 2Mbytes/s so will take over 1 hour for the whole transfer of 3 chunks. Tokens are valid for 1 hr.

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
rclone.conf
```
[box]
type = box
client_id = **REDACTED**
client_secret = **REDACTED**
box_config_file = /path/to/config.json
box_sub_type = enterprise
token = {"access_token":"**REDACTED**","token_type":"bearer","expiry":"2023-08-04T19:28:20.114244464+10:00"}

[box_enc]
type = crypt
remote = box:
filename_encryption = standard
directory_name_encryption = true
password = **REDACTED**
password2 = **REDACTED**

[box_enc_ch]
type = chunker
remote = box_enc:
chunk_size = 4900M
hash_type = sha1
```

In the log you can see 1 refresh as successful at 2023/08/04 17:21:22, however the next at 2023/08/04 18:27:14 says it is successful but the upload still fails.

```
2023/08/04 17:16:14 INFO  : Starting transaction limiter: max 10 transactions/s with burst 10
2023/08/04 17:16:14 DEBUG : rclone: Version "v1.63.1" starting with parameters ["rclone" "--log-level" "DEBUG" "--tpslimit" "10" "--tpslimit-burst" "10" "-P" "--box-box-config-file=/path/to/config.json" "--log-file=/tmp/box.log" "copy" "test.mkv" "box_enc_ch:test/upload/path"]
2023/08/04 17:16:14 DEBUG : Creating backend with remote "test.mkv"
2023/08/04 17:16:14 DEBUG : Using config file from "/path/to/.rclone.conf"
2023/08/04 17:16:14 DEBUG : fs cache: adding new entry for parent of "test.mkv", "/"
2023/08/04 17:16:14 DEBUG : Creating backend with remote "box_enc_ch:test/upload/path"
2023/08/04 17:16:14 DEBUG : Creating backend with remote "box_enc:test/upload/path"
2023/08/04 17:16:14 DEBUG : Creating backend with remote "box:**REDACTED**"
2023/08/04 17:16:14 DEBUG : box: detected overridden config - adding "{EOkOO}" suffix to name
2023/08/04 17:16:17 DEBUG : fs cache: renaming cache item "box:**REDACTED**" to be canonical "box{EOkOO}:**REDACTED**"
2023/08/04 17:16:17 DEBUG : fs cache: switching user supplied name "box:**REDACTED**" for canonical name "box{EOkOO}:**REDACTED**"
2023/08/04 17:16:17 DEBUG : Reset feature "ListR"
2023/08/04 17:16:17 DEBUG : test.mkv: Need to transfer - File not found at Destination
2023/08/04 17:16:18 DEBUG : test.mkv: skip slow SHA1 on source file, hashing in-transit
2023/08/04 17:16:19 DEBUG : **REDACTED**: Multipart upload session started for 77 parts of size 64Mi
2023/08/04 17:16:20 DEBUG : **REDACTED**: Uploading part 1/77 offset 0/4.786Gi part size 64Mi
2023/08/04 17:16:21 DEBUG : **REDACTED**: Uploading part 2/77 offset 64Mi/4.786Gi part size 64Mi
2023/08/04 17:16:22 DEBUG : **REDACTED**: Uploading part 3/77 offset 128Mi/4.786Gi part size 64Mi
2023/08/04 17:16:23 DEBUG : **REDACTED**: Uploading part 4/77 offset 192Mi/4.786Gi part size 64Mi
2023/08/04 17:18:12 DEBUG : **REDACTED**: Uploading part 5/77 offset 256Mi/4.786Gi part size 64Mi
2023/08/04 17:18:13 DEBUG : **REDACTED**: Uploading part 6/77 offset 320Mi/4.786Gi part size 64Mi
2023/08/04 17:18:22 DEBUG : **REDACTED**: Uploading part 7/77 offset 384Mi/4.786Gi part size 64Mi
2023/08/04 17:18:23 DEBUG : **REDACTED**: Uploading part 8/77 offset 448Mi/4.786Gi part size 64Mi
2023/08/04 17:20:09 DEBUG : **REDACTED**: Uploading part 9/77 offset 512Mi/4.786Gi part size 64Mi
2023/08/04 17:20:10 DEBUG : **REDACTED**: Uploading part 10/77 offset 576Mi/4.786Gi part size 64Mi
2023/08/04 17:20:16 DEBUG : **REDACTED**: Uploading part 11/77 offset 640Mi/4.786Gi part size 64Mi
2023/08/04 17:20:17 DEBUG : **REDACTED**: Uploading part 12/77 offset 704Mi/4.786Gi part size 64Mi
2023/08/04 17:21:20 DEBUG : box root '**REDACTED**': Token expired - 2 uploads in progress - refreshing
2023/08/04 17:21:22 DEBUG : jwtutil: Response Body: {"access_token":"**REDACTED**","expires_in":3951,"restricted_to":[],"token_type":"bearer"}
2023/08/04 17:21:22 DEBUG : Saving config "token" in section "box" of the config file
2023/08/04 17:21:22 DEBUG : Keeping previous permissions for config file: -rw-r--r--
2023/08/04 17:21:22 DEBUG : box{EOkOO}: Saved new token in config file
2023/08/04 17:21:22 DEBUG : box root '**REDACTED**': Token refresh successful
2023/08/04 17:22:05 DEBUG : **REDACTED**: Uploading part 13/77 offset 768Mi/4.786Gi part size 64Mi
2023/08/04 17:22:05 DEBUG : box{EOkOO}: Loaded fresh token from config file
2023/08/04 17:22:08 DEBUG : **REDACTED**: Uploading part 14/77 offset 832Mi/4.786Gi part size 64Mi
2023/08/04 17:22:10 DEBUG : **REDACTED**: Uploading part 15/77 offset 896Mi/4.786Gi part size 64Mi
2023/08/04 17:22:12 DEBUG : **REDACTED**: Uploading part 16/77 offset 960Mi/4.786Gi part size 64Mi
2023/08/04 17:24:00 DEBUG : **REDACTED**: Uploading part 17/77 offset 1Gi/4.786Gi part size 64Mi
2023/08/04 17:24:02 DEBUG : **REDACTED**: Uploading part 18/77 offset 1.062Gi/4.786Gi part size 64Mi
2023/08/04 17:24:07 DEBUG : **REDACTED**: Uploading part 19/77 offset 1.125Gi/4.786Gi part size 64Mi
2023/08/04 17:24:09 DEBUG : **REDACTED**: Uploading part 20/77 offset 1.188Gi/4.786Gi part size 64Mi
2023/08/04 17:25:52 DEBUG : **REDACTED**: Uploading part 21/77 offset 1.250Gi/4.786Gi part size 64Mi
2023/08/04 17:26:00 DEBUG : **REDACTED**: Uploading part 22/77 offset 1.312Gi/4.786Gi part size 64Mi
2023/08/04 17:26:03 DEBUG : **REDACTED**: Uploading part 23/77 offset 1.375Gi/4.786Gi part size 64Mi
2023/08/04 17:26:04 DEBUG : **REDACTED**: Uploading part 24/77 offset 1.438Gi/4.786Gi part size 64Mi
2023/08/04 17:27:48 DEBUG : **REDACTED**: Uploading part 25/77 offset 1.500Gi/4.786Gi part size 64Mi
2023/08/04 17:27:57 DEBUG : **REDACTED**: Uploading part 26/77 offset 1.562Gi/4.786Gi part size 64Mi
2023/08/04 17:27:58 DEBUG : **REDACTED**: Uploading part 27/77 offset 1.625Gi/4.786Gi part size 64Mi
2023/08/04 17:28:03 DEBUG : **REDACTED**: Uploading part 28/77 offset 1.688Gi/4.786Gi part size 64Mi
2023/08/04 17:29:39 DEBUG : **REDACTED**: Uploading part 29/77 offset 1.750Gi/4.786Gi part size 64Mi
2023/08/04 17:29:49 DEBUG : **REDACTED**: Uploading part 30/77 offset 1.812Gi/4.786Gi part size 64Mi
2023/08/04 17:29:52 DEBUG : **REDACTED**: Uploading part 31/77 offset 1.875Gi/4.786Gi part size 64Mi
2023/08/04 17:30:05 DEBUG : **REDACTED**: Uploading part 32/77 offset 1.938Gi/4.786Gi part size 64Mi
2023/08/04 17:31:35 DEBUG : **REDACTED**: Uploading part 33/77 offset 2Gi/4.786Gi part size 64Mi
2023/08/04 17:31:49 DEBUG : **REDACTED**: Uploading part 34/77 offset 2.062Gi/4.786Gi part size 64Mi
2023/08/04 17:31:50 DEBUG : **REDACTED**: Uploading part 35/77 offset 2.125Gi/4.786Gi part size 64Mi
2023/08/04 17:31:56 DEBUG : **REDACTED**: Uploading part 36/77 offset 2.188Gi/4.786Gi part size 64Mi
2023/08/04 17:33:30 DEBUG : **REDACTED**: Uploading part 37/77 offset 2.250Gi/4.786Gi part size 64Mi
2023/08/04 17:33:43 DEBUG : **REDACTED**: Uploading part 38/77 offset 2.312Gi/4.786Gi part size 64Mi
2023/08/04 17:33:52 DEBUG : **REDACTED**: Uploading part 39/77 offset 2.375Gi/4.786Gi part size 64Mi
2023/08/04 17:33:58 DEBUG : **REDACTED**: Uploading part 40/77 offset 2.438Gi/4.786Gi part size 64Mi
2023/08/04 17:35:23 DEBUG : **REDACTED**: Uploading part 41/77 offset 2.500Gi/4.786Gi part size 64Mi
2023/08/04 17:35:43 DEBUG : **REDACTED**: Uploading part 42/77 offset 2.562Gi/4.786Gi part size 64Mi
2023/08/04 17:35:57 DEBUG : **REDACTED**: Uploading part 43/77 offset 2.625Gi/4.786Gi part size 64Mi
2023/08/04 17:35:58 DEBUG : **REDACTED**: Uploading part 44/77 offset 2.688Gi/4.786Gi part size 64Mi
2023/08/04 17:37:26 DEBUG : **REDACTED**: Uploading part 45/77 offset 2.750Gi/4.786Gi part size 64Mi
2023/08/04 17:37:34 DEBUG : **REDACTED**: Uploading part 46/77 offset 2.812Gi/4.786Gi part size 64Mi
2023/08/04 17:37:55 DEBUG : **REDACTED**: Uploading part 47/77 offset 2.875Gi/4.786Gi part size 64Mi
2023/08/04 17:37:56 DEBUG : **REDACTED**: Uploading part 48/77 offset 2.938Gi/4.786Gi part size 64Mi
2023/08/04 17:39:22 DEBUG : **REDACTED**: Uploading part 49/77 offset 3Gi/4.786Gi part size 64Mi
2023/08/04 17:39:35 DEBUG : **REDACTED**: Uploading part 50/77 offset 3.062Gi/4.786Gi part size 64Mi
2023/08/04 17:39:55 DEBUG : **REDACTED**: Uploading part 51/77 offset 3.125Gi/4.786Gi part size 64Mi
2023/08/04 17:39:56 DEBUG : **REDACTED**: Uploading part 52/77 offset 3.188Gi/4.786Gi part size 64Mi
2023/08/04 17:41:19 DEBUG : **REDACTED**: Uploading part 53/77 offset 3.250Gi/4.786Gi part size 64Mi
2023/08/04 17:41:32 DEBUG : **REDACTED**: Uploading part 54/77 offset 3.312Gi/4.786Gi part size 64Mi
2023/08/04 17:41:55 DEBUG : **REDACTED**: Uploading part 55/77 offset 3.375Gi/4.786Gi part size 64Mi
2023/08/04 17:41:56 DEBUG : **REDACTED**: Uploading part 56/77 offset 3.438Gi/4.786Gi part size 64Mi
2023/08/04 17:43:12 DEBUG : **REDACTED**: Uploading part 57/77 offset 3.500Gi/4.786Gi part size 64Mi
2023/08/04 17:43:33 DEBUG : **REDACTED**: Uploading part 58/77 offset 3.562Gi/4.786Gi part size 64Mi
2023/08/04 17:43:48 DEBUG : **REDACTED**: Uploading part 59/77 offset 3.625Gi/4.786Gi part size 64Mi
2023/08/04 17:43:55 DEBUG : **REDACTED**: Uploading part 60/77 offset 3.688Gi/4.786Gi part size 64Mi
2023/08/04 17:45:07 DEBUG : **REDACTED**: Uploading part 61/77 offset 3.750Gi/4.786Gi part size 64Mi
2023/08/04 17:45:29 DEBUG : **REDACTED**: Uploading part 62/77 offset 3.812Gi/4.786Gi part size 64Mi
2023/08/04 17:45:49 DEBUG : **REDACTED**: Uploading part 63/77 offset 3.875Gi/4.786Gi part size 64Mi
2023/08/04 17:45:51 DEBUG : **REDACTED**: Uploading part 64/77 offset 3.938Gi/4.786Gi part size 64Mi
2023/08/04 17:47:02 DEBUG : **REDACTED**: Uploading part 65/77 offset 4Gi/4.786Gi part size 64Mi
2023/08/04 17:47:34 DEBUG : **REDACTED**: Uploading part 66/77 offset 4.062Gi/4.786Gi part size 64Mi
2023/08/04 17:47:43 DEBUG : **REDACTED**: Uploading part 67/77 offset 4.125Gi/4.786Gi part size 64Mi
2023/08/04 17:47:44 DEBUG : **REDACTED**: Uploading part 68/77 offset 4.188Gi/4.786Gi part size 64Mi
2023/08/04 17:48:58 DEBUG : **REDACTED**: Uploading part 69/77 offset 4.250Gi/4.786Gi part size 64Mi
2023/08/04 17:49:25 DEBUG : **REDACTED**: Uploading part 70/77 offset 4.312Gi/4.786Gi part size 64Mi
2023/08/04 17:49:44 DEBUG : **REDACTED**: Uploading part 71/77 offset 4.375Gi/4.786Gi part size 64Mi
2023/08/04 17:49:45 DEBUG : **REDACTED**: Uploading part 72/77 offset 4.438Gi/4.786Gi part size 64Mi
2023/08/04 17:50:52 DEBUG : **REDACTED**: Uploading part 73/77 offset 4.500Gi/4.786Gi part size 64Mi
2023/08/04 17:51:25 DEBUG : **REDACTED**: Uploading part 74/77 offset 4.562Gi/4.786Gi part size 64Mi
2023/08/04 17:51:40 DEBUG : **REDACTED**: Uploading part 75/77 offset 4.625Gi/4.786Gi part size 64Mi
2023/08/04 17:51:42 DEBUG : **REDACTED**: Uploading part 76/77 offset 4.688Gi/4.786Gi part size 64Mi
2023/08/04 17:52:48 DEBUG : **REDACTED**: Uploading part 77/77 offset 4.750Gi/4.786Gi part size 64Mi
2023/08/04 17:53:39 DEBUG : **REDACTED**: commit multipart upload failed 1/100 - trying again in 30 seconds (not ready yet)
2023/08/04 17:54:11 DEBUG : test.mkv: sha1 = **REDACTED** OK
2023/08/04 17:54:13 DEBUG : **REDACTED**: Multipart upload session started for 77 parts of size 64Mi
2023/08/04 17:54:14 DEBUG : **REDACTED**: Uploading part 1/77 offset 0/4.786Gi part size 64Mi
2023/08/04 17:54:14 DEBUG : **REDACTED**: Uploading part 2/77 offset 64Mi/4.786Gi part size 64Mi
2023/08/04 17:54:15 DEBUG : **REDACTED**: Uploading part 3/77 offset 128Mi/4.786Gi part size 64Mi
2023/08/04 17:54:16 DEBUG : **REDACTED**: Uploading part 4/77 offset 192Mi/4.786Gi part size 64Mi
2023/08/04 17:56:09 DEBUG : **REDACTED**: Uploading part 5/77 offset 256Mi/4.786Gi part size 64Mi
2023/08/04 17:56:10 DEBUG : **REDACTED**: Uploading part 6/77 offset 320Mi/4.786Gi part size 64Mi
2023/08/04 17:56:12 DEBUG : **REDACTED**: Uploading part 7/77 offset 384Mi/4.786Gi part size 64Mi
2023/08/04 17:56:13 DEBUG : **REDACTED**: Uploading part 8/77 offset 448Mi/4.786Gi part size 64Mi
2023/08/04 17:58:04 DEBUG : **REDACTED**: Uploading part 9/77 offset 512Mi/4.786Gi part size 64Mi
2023/08/04 17:58:08 DEBUG : **REDACTED**: Uploading part 10/77 offset 576Mi/4.786Gi part size 64Mi
2023/08/04 17:58:09 DEBUG : **REDACTED**: Uploading part 11/77 offset 640Mi/4.786Gi part size 64Mi
2023/08/04 17:58:10 DEBUG : **REDACTED**: Uploading part 12/77 offset 704Mi/4.786Gi part size 64Mi
2023/08/04 17:59:59 DEBUG : **REDACTED**: Uploading part 13/77 offset 768Mi/4.786Gi part size 64Mi
2023/08/04 18:00:01 DEBUG : **REDACTED**: Uploading part 14/77 offset 832Mi/4.786Gi part size 64Mi
2023/08/04 18:00:02 DEBUG : **REDACTED**: Uploading part 15/77 offset 896Mi/4.786Gi part size 64Mi
2023/08/04 18:00:09 DEBUG : **REDACTED**: Uploading part 16/77 offset 960Mi/4.786Gi part size 64Mi
2023/08/04 18:01:53 DEBUG : **REDACTED**: Uploading part 17/77 offset 1Gi/4.786Gi part size 64Mi
2023/08/04 18:01:58 DEBUG : **REDACTED**: Uploading part 18/77 offset 1.062Gi/4.786Gi part size 64Mi
2023/08/04 18:01:59 DEBUG : **REDACTED**: Uploading part 19/77 offset 1.125Gi/4.786Gi part size 64Mi
2023/08/04 18:02:06 DEBUG : **REDACTED**: Uploading part 20/77 offset 1.188Gi/4.786Gi part size 64Mi
2023/08/04 18:03:48 DEBUG : **REDACTED**: Uploading part 21/77 offset 1.250Gi/4.786Gi part size 64Mi
2023/08/04 18:03:50 DEBUG : **REDACTED**: Uploading part 22/77 offset 1.312Gi/4.786Gi part size 64Mi
2023/08/04 18:03:56 DEBUG : **REDACTED**: Uploading part 23/77 offset 1.375Gi/4.786Gi part size 64Mi
2023/08/04 18:04:04 DEBUG : **REDACTED**: Uploading part 24/77 offset 1.438Gi/4.786Gi part size 64Mi
2023/08/04 18:05:45 DEBUG : **REDACTED**: Uploading part 25/77 offset 1.500Gi/4.786Gi part size 64Mi
2023/08/04 18:05:48 DEBUG : **REDACTED**: Uploading part 26/77 offset 1.562Gi/4.786Gi part size 64Mi
2023/08/04 18:05:51 DEBUG : **REDACTED**: Uploading part 27/77 offset 1.625Gi/4.786Gi part size 64Mi
2023/08/04 18:05:55 DEBUG : **REDACTED**: Uploading part 28/77 offset 1.688Gi/4.786Gi part size 64Mi
2023/08/04 18:07:41 DEBUG : **REDACTED**: Uploading part 29/77 offset 1.750Gi/4.786Gi part size 64Mi
2023/08/04 18:07:44 DEBUG : **REDACTED**: Uploading part 30/77 offset 1.812Gi/4.786Gi part size 64Mi
2023/08/04 18:07:45 DEBUG : **REDACTED**: Uploading part 31/77 offset 1.875Gi/4.786Gi part size 64Mi
2023/08/04 18:07:55 DEBUG : **REDACTED**: Uploading part 32/77 offset 1.938Gi/4.786Gi part size 64Mi
2023/08/04 18:09:33 DEBUG : **REDACTED**: Uploading part 33/77 offset 2Gi/4.786Gi part size 64Mi
2023/08/04 18:09:40 DEBUG : **REDACTED**: Uploading part 34/77 offset 2.062Gi/4.786Gi part size 64Mi
2023/08/04 18:09:42 DEBUG : **REDACTED**: Uploading part 35/77 offset 2.125Gi/4.786Gi part size 64Mi
2023/08/04 18:09:49 DEBUG : **REDACTED**: Uploading part 36/77 offset 2.188Gi/4.786Gi part size 64Mi
2023/08/04 18:11:26 DEBUG : **REDACTED**: Uploading part 37/77 offset 2.250Gi/4.786Gi part size 64Mi
2023/08/04 18:11:34 DEBUG : **REDACTED**: Uploading part 38/77 offset 2.312Gi/4.786Gi part size 64Mi
2023/08/04 18:11:38 DEBUG : **REDACTED**: Uploading part 39/77 offset 2.375Gi/4.786Gi part size 64Mi
2023/08/04 18:11:51 DEBUG : **REDACTED**: Uploading part 40/77 offset 2.438Gi/4.786Gi part size 64Mi
2023/08/04 18:13:22 DEBUG : **REDACTED**: Uploading part 41/77 offset 2.500Gi/4.786Gi part size 64Mi
2023/08/04 18:13:29 DEBUG : **REDACTED**: Uploading part 42/77 offset 2.562Gi/4.786Gi part size 64Mi
2023/08/04 18:13:33 DEBUG : **REDACTED**: Uploading part 43/77 offset 2.625Gi/4.786Gi part size 64Mi
2023/08/04 18:13:45 DEBUG : **REDACTED**: Uploading part 44/77 offset 2.688Gi/4.786Gi part size 64Mi
2023/08/04 18:15:21 DEBUG : **REDACTED**: Uploading part 45/77 offset 2.750Gi/4.786Gi part size 64Mi
2023/08/04 18:15:27 DEBUG : **REDACTED**: Uploading part 46/77 offset 2.812Gi/4.786Gi part size 64Mi
2023/08/04 18:15:28 DEBUG : **REDACTED**: Uploading part 47/77 offset 2.875Gi/4.786Gi part size 64Mi
2023/08/04 18:15:37 DEBUG : **REDACTED**: Uploading part 48/77 offset 2.938Gi/4.786Gi part size 64Mi
2023/08/04 18:17:20 DEBUG : **REDACTED**: Uploading part 49/77 offset 3Gi/4.786Gi part size 64Mi
2023/08/04 18:17:24 DEBUG : **REDACTED**: Uploading part 50/77 offset 3.062Gi/4.786Gi part size 64Mi
2023/08/04 18:17:27 DEBUG : **REDACTED**: Uploading part 51/77 offset 3.125Gi/4.786Gi part size 64Mi
2023/08/04 18:17:34 DEBUG : **REDACTED**: Uploading part 52/77 offset 3.188Gi/4.786Gi part size 64Mi
2023/08/04 18:19:14 DEBUG : **REDACTED**: Uploading part 53/77 offset 3.250Gi/4.786Gi part size 64Mi
2023/08/04 18:19:15 DEBUG : **REDACTED**: Uploading part 54/77 offset 3.312Gi/4.786Gi part size 64Mi
2023/08/04 18:19:30 DEBUG : **REDACTED**: Uploading part 55/77 offset 3.375Gi/4.786Gi part size 64Mi
2023/08/04 18:19:33 DEBUG : **REDACTED**: Uploading part 56/77 offset 3.438Gi/4.786Gi part size 64Mi
2023/08/04 18:21:08 DEBUG : **REDACTED**: Uploading part 57/77 offset 3.500Gi/4.786Gi part size 64Mi
2023/08/04 18:21:11 DEBUG : **REDACTED**: Uploading part 58/77 offset 3.562Gi/4.786Gi part size 64Mi
2023/08/04 18:21:25 DEBUG : **REDACTED**: Uploading part 59/77 offset 3.625Gi/4.786Gi part size 64Mi
2023/08/04 18:21:30 DEBUG : **REDACTED**: Uploading part 60/77 offset 3.688Gi/4.786Gi part size 64Mi
2023/08/04 18:23:06 DEBUG : **REDACTED**: Uploading part 61/77 offset 3.750Gi/4.786Gi part size 64Mi
2023/08/04 18:23:11 DEBUG : **REDACTED**: Uploading part 62/77 offset 3.812Gi/4.786Gi part size 64Mi
2023/08/04 18:23:12 DEBUG : **REDACTED**: Uploading part 63/77 offset 3.875Gi/4.786Gi part size 64Mi
2023/08/04 18:23:27 DEBUG : **REDACTED**: Uploading part 64/77 offset 3.938Gi/4.786Gi part size 64Mi
2023/08/04 18:25:01 DEBUG : **REDACTED**: Uploading part 65/77 offset 4Gi/4.786Gi part size 64Mi
2023/08/04 18:25:07 DEBUG : **REDACTED**: Uploading part 66/77 offset 4.062Gi/4.786Gi part size 64Mi
2023/08/04 18:25:11 DEBUG : **REDACTED**: Uploading part 67/77 offset 4.125Gi/4.786Gi part size 64Mi
2023/08/04 18:25:26 DEBUG : **REDACTED**: Uploading part 68/77 offset 4.188Gi/4.786Gi part size 64Mi
2023/08/04 18:27:01 DEBUG : **REDACTED**: Uploading part 69/77 offset 4.250Gi/4.786Gi part size 64Mi
2023/08/04 18:27:02 DEBUG : **REDACTED**: Uploading part 70/77 offset 4.312Gi/4.786Gi part size 64Mi
2023/08/04 18:27:06 DEBUG : **REDACTED**: Uploading part 71/77 offset 4.375Gi/4.786Gi part size 64Mi
2023/08/04 18:27:06 DEBUG : box{EOkOO}: Loaded invalid token from config file - ignoring
2023/08/04 18:27:07 DEBUG : **REDACTED**: Uploading part 72/77 offset 4.438Gi/4.786Gi part size 64Mi
2023/08/04 18:27:07 DEBUG : box{EOkOO}: Loaded invalid token from config file - ignoring
2023/08/04 18:27:13 DEBUG : box root '**REDACTED**': Token expired - 2 uploads in progress - refreshing
2023/08/04 18:27:14 DEBUG : jwtutil: Response Body: {"access_token":"**REDACTED**","expires_in":3666,"restricted_to":[],"token_type":"bearer"}
2023/08/04 18:27:14 DEBUG : Saving config "token" in section "box" of the config file
2023/08/04 18:27:14 DEBUG : Keeping previous permissions for config file: -rw-r--r--
2023/08/04 18:27:14 DEBUG : box{EOkOO}: Saved new token in config file
2023/08/04 18:27:14 DEBUG : box root '**REDACTED**': Token refresh successful
2023/08/04 18:28:47 DEBUG : **REDACTED**: Cancelling multipart upload: multipart upload failed to upload part: Put "https://upload.box.com/api/2.0/files/upload_sessions/**REDACTED**": token expired and there's no refresh token - manually refresh with "rclone config reconnect box{EOkOO}:"
2023/08/04 18:28:47 DEBUG : box{EOkOO}: Loaded fresh token from config file
2023/08/04 18:28:48 ERROR : test.mkv: Failed to copy: multipart upload failed to upload part: Put "https://upload.box.com/api/2.0/files/upload_sessions/**REDACTED**": token expired and there's no refresh token - manually refresh with "rclone config reconnect box{EOkOO}:"
2023/08/04 18:28:48 ERROR : Fatal error received - not attempting retries
2023/08/04 18:28:48 INFO  : 
Transferred:   	    9.161 GiB / 9.161 GiB, 100%, 625.840 KiB/s, ETA 0s
Errors:                 1 (fatal error encountered)
Elapsed time:   1h12m34.1s

2023/08/04 18:28:48 DEBUG : 9 go routines active
2023/08/04 18:28:48 Failed to copy: multipart upload failed to upload part: Put "https://upload.box.com/api/2.0/files/upload_sessions/**REDACTED**": token expired and there's no refresh token - manually refresh with "rclone config reconnect box{EOkOO}:"
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by vpatel9202** [comment]
Agreed that there needs to be some work done on this but I will add that per Box's [own documentation](https://developer.box.com/guides/authentication/tokens/access-tokens/#server-authentication), the server-side authentication methods (JWT and Client Credentials Grant) do not provide refresh tokens. My "[workaround](https://forum.rclone.org/t/box-getting-403-errors-when-using-chunker-working-fine-without-it/40388/22?u=vashp2029)" using OAuth functions but is less than ideal since as you mentioned, it does not allow you to manage file permissions. 

Since OAuth gives broad permissions and JWT/CCG do not auto-refresh, the only other authentication provided per their documentation is App Tokens. I haven't tried this method, so if someone has the time maybe they can give it a shot. I have a feeling it will work fine for uploading/downloading but we may run into issues renaming files (which will make the chunker useless). We had a discussion about this [here](https://forum.rclone.org/t/box-getting-403-errors-when-using-chunker-working-fine-without-it/40388/10?u=vashp2029).

**Comment by aselafernando** [comment]
The fact there is no refresh token provided with Oauth2 and JWT should not stop this from working. As seen in the debug log, rclone is able to refresh a token without a refresh token provided. The rclone code needs to be modified to follow the API and not expect the refresh token when using OAuth2 with JWT. I haven't looking into the code in depth as to why it is able to refresh with no refresh token once but not twice.

App tokens can be made with no expiry date but given the limited endpoints they grant access to, they are not suitable for rclone usage.

**Comment by kapitainsky** [comment]
I wonder if it has something to do with this not fully tested PR some time ago:

https://github.com/rclone/rclone/pull/6277

**Comment by aselafernando** [comment]
I got rclone to a point where it isnt refreshing the token at all

I tried a simple rclone mkdir box_enc_ch:test

I saw it is requesting it from box but maybe it doesnt like the response it gets. I did run it with --dump headers,bodies,requests,responses,auth but I didn't see a response in the log. The client ID and secret at correct and the grant type appears to be correct based on [this](https://developer.box.com/guides/authentication/jwt/without-sdk/).

```
2023/08/07 18:15:12 DEBUG : You have specified to dump information. Please be noted that the Accept-Encoding as shown may not be correct in the request and the response may not show Content-Encoding if the go standard libraries auto gzip encoding was in effect. In this case the body of the request will be gunzipped before showing it.
2023/08/07 18:15:12 DEBUG : box root '**REDACTED**': Token expired - 1 uploads in progress - refreshing
2023/08/07 18:15:12 DEBUG : box: Loaded invalid token from config file - ignoring
2023/08/07 18:15:12 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2023/08/07 18:15:12 DEBUG : HTTP REQUEST (req 0xc00039a800)
2023/08/07 18:15:12 DEBUG : POST /oauth2/token HTTP/1.1
Host: api.box.com
User-Agent: rclone/v1.63.1
Content-Length: 830
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip

assertion=**REDACTED**&client_id=**REDACTED**&client_secret=**REDACTED**&grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer
2023/08/07 18:15:12 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2023/08/07 18:15:12 DEBUG : box: Loaded invalid token from config file - ignoring
2023/08/07 18:15:12 DEBUG : Reset feature "ListR"
2023/08/07 18:15:12 DEBUG : Chunked 'box_enc_ch:test': Making directory
2023/08/07 18:15:12 DEBUG : box: Loaded invalid token from config file - ignoring
2023/08/07 18:15:12 ERROR : Fatal error received - not attempting retries
2023/08/07 18:15:12 DEBUG : 10 go routines active
2023/08/07 18:15:12 Failed to mkdir: couldn't list files: Get "https://api.box.com/2.0/...." token expired and there's no refresh token - manually refresh with "rclone config reconnect box:"
```

Looking at the assertion field, it is using the correct private key from config.json to encrypt

JWT Header looks OK
```
{
  "alg": "RS256",
  "kid": "**Private Key ID**",
  "typ": "JWT"
}
```

JWT Payload, the request was made at 18:15:12 and the expiry is 18:15:57 (GMT+10) so within the 60 seconds Box specifies as a maximum time. So the payload looks good.
```
{
  "aud": "https://api.box.com/oauth2/token",
  "exp": 1691396157,
  "jti": "**Unique string >16 <128 chars long**",
  "iss": "**Client ID from config.json**",
  "sub": "**Enterprise ID from config.json**",
  "box_sub_type": "enterprise"
}
```

**Is there a way to dump the response rclone gets?** I tried using the --dump commands but I only got the requests, not the responses.

I tried passing the same token from a python script and as predicted I got an error about the expiration date.
```
{'error': 'invalid_grant',
 'error_description': 'Current date/time MUST be before the expiration '
                      "date/time listed in the 'exp' claim"}
```

**Comment by sacwooky** [comment]
Posted this issue with JWT causing a panic error message

https://forum.rclone.org/t/box-jwt-config-erroring-panic/40685

**Comment by ncw** [comment]
Can you try commenting out these 3 lines

https://github.com/rclone/rclone/blob/40de89df73cf26424fdc2a5676f36eefe9d9dc43/lib/oauthutil/oauthutil.go#L270-L272

And see if that works.

I think lib/oauthutil is making an assumption that we need a refresh token to do the refresh which is incorrect here.

If you are working on behalf of a company you might be interested in taking out a [support contract](https://rclone.com/support) which can help you get answers quicker and keeps the rclone project sustainable.

**Comment by aselafernando** [comment]
That worked! (tested on 1.64-DEV)

**Comment by aselafernando** [comment]
Ah looks like I spoke to soon, whilst now doing smaller transactions (like making/listing directories) works, longer running transactions like an upload over the 1 hr mark still does not

I tried uploading a large file again and got the following. It can be seen the code is looping here:
https://github.com/rclone/rclone/blob/40de89df73cf26424fdc2a5676f36eefe9d9dc43/lib/oauthutil/oauthutil.go#L263C2-L291C3 
As now with the lines commented as suggested, it will not return with no refresh token. I suspect it isn't trying to request a new token whereas it should be during this loop. Eventually the code cancels the upload and then it is able to get a new token starting the upload again.

```
2023/08/10 22:01:26 DEBUG : [redacted]: Uploading part 11/77 offset 640Mi/4.786Gi part size 64Mi
2023/08/10 22:02:00 DEBUG : [redacted]: Uploading part 12/77 offset 704Mi/4.786Gi part size 64Mi
2023/08/10 22:02:00 DEBUG : box: Loaded invalid token from config file - ignoring
2023/08/10 22:02:00 DEBUG : box: Token refresh failed try 1/5: oauth2: token expired and refresh token is not set
2023/08/10 22:02:01 DEBUG : box: Loaded invalid token from config file - ignoring
2023/08/10 22:02:01 DEBUG : box: Token refresh failed try 2/5: oauth2: token expired and refresh token is not set
2023/08/10 22:02:02 DEBUG : box: Loaded invalid token from config file - ignoring
2023/08/10 22:02:02 DEBUG : box: Token refresh failed try 3/5: oauth2: token expired and refresh token is not set
2023/08/10 22:02:03 DEBUG : box: Loaded invalid token from config file - ignoring
2023/08/10 22:02:03 DEBUG : box: Token refresh failed try 4/5: oauth2: token expired and refresh token is not set
2023/08/10 22:02:04 DEBUG : box: Loaded invalid token from config file - ignoring
2023/08/10 22:02:04 DEBUG : box: Token refresh failed try 5/5: oauth2: token expired and refresh token is not set
2023/08/10 22:02:05 DEBUG : [redacted]: Uploading part 13/77 offset 768Mi/4.786Gi part size 64Mi
2023/08/10 22:02:05 DEBUG : box: Loaded invalid token from config file - ignoring
2023/08/10 22:02:05 DEBUG : box: Token refresh failed try 1/5: oauth2: token expired and refresh token is not set
2023/08/10 22:02:06 DEBUG : box: Loaded invalid token from config file - ignoring
2023/08/10 22:02:06 DEBUG : box: Token refresh failed try 2/5: oauth2: token expired and refresh token is not set
2023/08/10 22:02:07 DEBUG : box: Loaded invalid token from config file - ignoring
2023/08/10 22:02:07 DEBUG : box: Token refresh failed try 3/5: oauth2: token expired and refresh token is not set
2023/08/10 22:02:08 DEBUG : box: Loaded invalid token from config file - ignoring
2023/08/10 22:02:08 DEBUG : box: Token refresh failed try 4/5: oauth2: token expired and refresh token is not set
2023/08/10 22:02:09 DEBUG : box: Loaded invalid token from config file - ignoring
2023/08/10 22:02:09 DEBUG : box: Token refresh failed try 5/5: oauth2: token expired and refresh token is not set
2023/08/10 22:02:10 DEBUG : box root 'Sync/m': Token expired - 2 uploads in progress - refreshing
2023/08/10 22:02:10 DEBUG : [redacted]: Cancelling multipart upload: multipart upload failed to upload part: Put "https://upload.box.com/api/2.0/files/upload_sessions/[redacted]": couldn't fetch token: oauth2: token expired and refresh token is not set
2023/08/10 22:02:10 DEBUG : box: Loaded invalid token from config file - ignoring
2023/08/10 22:02:10 DEBUG : box: Token refresh failed try 1/5: oauth2: token expired and refresh token is not set
2023/08/10 22:02:10 DEBUG : jwtutil: Response Body: {"access_token":"","expires_in":4044,"restricted_to":[],"token_type":"bearer"}
2023/08/10 22:02:10 DEBUG : Saving config "token" in section "box" of the config file
2023/08/10 22:02:10 DEBUG : Keeping previous permissions for config file: -rw-r--r--
2023/08/10 22:02:10 DEBUG : box: Saved new token in config file
2023/08/10 22:02:10 DEBUG : box root 'Sync/m': Token refresh successful
2023/08/10 22:02:11 DEBUG : box: Loaded fresh token from config file
2023/08/10 22:07:12 DEBUG : pacer: low level retry 1/10 (error Delete "https://api.box.com/2.0/files/[redacted]": net/http: timeout awaiting response headers)
2023/08/10 22:07:12 DEBUG : pacer: Rate limited, increasing sleep to 20ms
2023/08/10 22:07:13 DEBUG : pacer: Reducing sleep to 15ms
2023/08/10 22:07:14 DEBUG : pacer: Reducing sleep to 11.25ms
2023/08/10 22:07:15 DEBUG : pacer: Reducing sleep to 10ms
2023/08/10 22:07:16 ERROR : [redacted]: Failed to copy: multipart upload failed to upload part: Put "https://upload.box.com/api/2.0/files/upload_sessions/[redacted]": couldn't fetch token: oauth2: token expired and refresh token is not set
2023/08/10 22:07:16 ERROR : [redacted]: Not deleting source as copy failed: multipart upload failed to upload part: Put "https://upload.box.com/api/2.0/files/upload_sessions/[redacted]": couldn't fetch token: oauth2: token expired and refresh token is not set
2023/08/10 22:07:16 DEBUG : [redacted]: skip slow SHA1 on source file, hashing in-transit
2023/08/10 22:07:18 DEBUG : [redacted]: Multipart upload session started for 77 parts of size 64Mi
2023/08/10 22:07:18 DEBUG : [redacted]: Uploading part 1/77 offset 0/4.786Gi part size 64Mi
```

I suspect the issue may lie here as well, perhaps always forcing it to create a new tokenSource will allow it to resume. I have tweaked the code here and running another test. I will post the results.
```
                if ts.tokenSource == nil {
                        ts.tokenSource = ts.config.TokenSource(ts.ctx, ts.token)
                }
```

**Comment by ncw** [comment]
Let me know what happens and please post a diff so I can know exactly what you changed - thanks!

**Comment by aselafernando** [comment]
All I did was add more debug statements around to help me understand rclones program flow haha I've never programmed in Go before either. What I did find is that if the program refreshes the token using the OnExpiry() channel in [renewOnExpiry()](https://github.com/rclone/rclone/blob/40de89df73cf26424fdc2a5676f36eefe9d9dc43/lib/oauthutil/renew.go#L36) the token refreshes without a problem and the upload resumes as normal.

```
2023/08/11 00:19:40 DEBUG : [redacted]: Uploading part 42/77 offset 2.562Gi/4.786Gi part size 64Mi
2023/08/11 00:19:54 DEBUG : box root '[redacted]': Token expired - 2 uploads in progress - refreshing
2023/08/11 00:19:55 DEBUG : jwtutil: Response Body: {"access_token":"[redacted]","expires_in":3697,"restricted_to":[],"token_type":"bearer"}
2023/08/11 00:19:55 DEBUG : Saving config "token" in section "box" of the config file
2023/08/11 00:19:55 DEBUG : Keeping previous permissions for config file: -rw-r--r--
2023/08/11 00:19:55 DEBUG : box: Saved new token in config file
2023/08/11 00:19:55 DEBUG : box root '[redacted]': Token refresh successful
2023/08/11 00:20:12 DEBUG : [redacted]: Uploading part 43/77 offset 2.625Gi/4.786Gi part size 64Mi
2023/08/11 00:20:12 DEBUG : box: Loaded fresh token from config file
2023/08/11 00:20:44 DEBUG : [redacted]: Uploading part 44/77 offset 2.688Gi/4.786Gi part size 64Mi
```

However if the program enters [reReadToken()](https://github.com/rclone/rclone/blob/40de89df73cf26424fdc2a5676f36eefe9d9dc43/lib/oauthutil/oauthutil.go#L185C24-L185C37) with an invalid token, the upload will always be cancelled regardless if a token is refreshed. newToken.Valid() seems to always return false. I think this is because in the 5 retries, the renewOnExpiry() method is still waiting for the expiry time before it triggers. I'm guessing Box is expiring the token a few seconds before it should be.

```
2023/08/11 03:34:16 DEBUG : [redacted]: Uploading part 72/77 offset 4.438Gi/4.786Gi part size 64Mi
2023/08/11 03:34:17 DEBUG : box: Loaded invalid token from config file - ignoring
2023/08/11 03:34:17 DEBUG : box: Token refresh failed try 1/5: oauth2: token expired and refresh token is not set
2023/08/11 03:34:18 DEBUG : box: Loaded invalid token from config file - ignoring
2023/08/11 03:34:18 DEBUG : box: Token refresh failed try 2/5: oauth2: token expired and refresh token is not set
2023/08/11 03:34:19 DEBUG : box: Loaded invalid token from config file - ignoring
2023/08/11 03:34:19 DEBUG : box: Token refresh failed try 3/5: oauth2: token expired and refresh token is not set
2023/08/11 03:34:20 DEBUG : box: Loaded invalid token from config file - ignoring
2023/08/11 03:34:20 DEBUG : box: Token refresh failed try 4/5: oauth2: token expired and refresh token is not set
2023/08/11 03:34:21 DEBUG : box: Loaded invalid token from config file - ignoring
2023/08/11 03:34:21 DEBUG : box: Token refresh failed try 5/5: oauth2: token expired and refresh token is not set
2023/08/11 03:34:22 DEBUG : [redacted]: Uploading part 73/77 offset 4.500Gi/4.786Gi part size 64Mi
2023/08/11 03:34:22 DEBUG : box: Loaded invalid token from config file - ignoring
2023/08/11 03:34:22 DEBUG : box: Token refresh failed try 1/5: oauth2: token expired and refresh token is not set
2023/08/11 03:34:23 DEBUG : box: Loaded invalid token from config file - ignoring
2023/08/11 03:34:23 DEBUG : box: Token refresh failed try 2/5: oauth2: token expired and refresh token is not set
2023/08/11 03:34:23 DEBUG : box root '[redacted]': Token expired - 2 uploads in progress - refreshing
2023/08/11 03:34:24 DEBUG : jwtutil: Response Body: {"access_token":"[redacted]","expires_in":4146,"restricted_to":[],"token_type":"bearer"}
2023/08/11 03:34:24 DEBUG : Saving config "token" in section "box" of the config file
2023/08/11 03:34:24 DEBUG : Keeping previous permissions for config file: -rw-r--r--
2023/08/11 03:34:24 DEBUG : box: Saved new token in config file
2023/08/11 03:34:24 DEBUG : box root '[redacted]': Token refresh successful
2023/08/11 03:34:24 DEBUG : box: Loaded fresh token from config file
2023/08/11 03:35:00 DEBUG : [redacted]: Cancelling multipart upload: multipart upload failed to upload part: Put "https://upload.box.com/api/2.0/files/upload_sessions/[redacted]":
couldn't fetch token: oauth2: token expired and refresh token is not set
```

I left rclone going for a few hours and logged the times I got tokens vs the times reReadToken had an issue and I got the following

Log Time | expires_in | Predicted expiry
-- | -- | --
10/08/2023   23:09:37 | 4217 | 11/08/2023 0:19:54
11/08/2023 0:19:55 | 3697 | 11/08/2023 1:21:32
11/08/2023 1:21:33 | 4077 | 11/08/2023 2:29:30
11/08/2023 2:29:31 | 3892 | 11/08/2023 3:34:23
11/08/2023 3:34:17 | Loaded Invalid Token - reReadToken() - Upload failed
11/08/2023 3:34:24 | 4146 | 11/08/2023 4:43:30
11/08/2023 4:43:30 | 3628 | 11/08/2023 5:43:58
11/08/2023 5:43:59 | 4090 | 11/08/2023 6:52:09
11/08/2023 6:52:10 | 4297 | 11/08/2023 8:03:47
11/08/2023 8:03:48 | 4234 | 11/08/2023 9:14:22
11/08/2023 9:14:23 | 4047 | 11/08/2023 10:21:50
11/08/2023   10:21:48 | Loaded Invalid Token - reReadToken()  - Upload failed
11/08/2023   10:21:50 | 4168 | 11/08/2023 11:31:18
11/08/2023   11:31:19 | 3618 | 11/08/2023 12:31:37

This made me think of a workaround, if I make the expiry time lower, then renewOnExpiry() will trigger a renewal before reReadToken() ever gets an invalid token.

So in [timeToExpiry()](https://github.com/rclone/rclone/blob/40de89df73cf26424fdc2a5676f36eefe9d9dc43/lib/oauthutil/oauthutil.go#L337C1-L337C54) I changed the return statement to be
```
return time.Until(t.Expiry.Add(-2 * time.Minute))
```
which will make the token expire 2 minutes earlier than it actually does.

I now have had an upload going for 7 hours and all the token refreshes have worked. As expected renewOnExpiry() is triggering to ensure there is always a valid token so reReadToken() should never get an invalid token. I will keep this upload going for another day and see if this workaround is consistent.

**Comment by aselafernando** [comment]
I had the upload running for 34 hours and no token errors.
I refactored the code to push as much as I could into the box back end as that's where Box workarounds should live haha
I then retested and achieved the same success. The PR has the code that was changed.

**Comment by aniel300** [comment]
has this issue been fixed and when is going to be merged into the stable or beta version?

**Comment by erik-kkr** [comment]
Will this be going in?

**Comment by ncw** [comment]
The code isn't quite ready - it potentially breaks other oauth using backends.

@aselafernando can you look at my comment on the pull request please?

**Comment by ndrarmstrong** [comment]
We are running into this issue too - one of our directories is large enough that listing takes more than an hour, so a sync cannot finish before the token expires.

@aselafernando Would you like assistance implementing the fixes that @ncw suggested in your PR? Happy to lend a hand to get this merged.

**Comment by ncw** [comment]
@ndrarmstrong it would be great to get your help with this. Since we haven't heard from @aselafernando I suggest you create a new PR to fix this with aselafernando changes and any fixes needed.

**Comment by ndrarmstrong** [comment]
Will do - possibly this evening, but if not I will get a PR up over the weekend.

**Comment by ncw** [comment]
> Referring to the [box API authentication documentation](https://developer.box.com/guides/authentication/select/) we have 4 authentication methods
> 
> 1. Oauth2
> 2. Oauth2 with JWT
> 3. Client Credentials
> 4. App Tokens

I will just note that rclone, as of v1.70 does now support client credentials grant: https://rclone.org/box/#box-client-credentials

This was tested extensively with OneDrive - I don't know how you set this up with box but hopefully it works!

**Comment by ndrarmstrong** [comment]
PR is up - though with Box's standard 1-hour token expiry I will let it run in my environment overnight before marking it ready for review. For now, I tested by arbitrarily shortening the token expiry to 2 minutes and confirmed that it was able to consistently refresh ahead of the expiry without error.

After some deeper study I decided to take a different approach than the @aselafernando PR.  The crux of the issue is that the Box backend was letting the JWT-sourced token reach expiry before attempting to refresh it; and at that point oauthutil was already treating it as expired and raising an error.  Simply shortening the expiry would not work, as oauthutil would calculate the token's validity off the adjusted expiry.

Instead, I've added a new signal that fires "shortly before" expiry to allow time for the Box backend to refresh the token prior to expiry.  When the cached token reaches expiry, oauthutil re-reads the token from the config, finds an extended expiry time, and everything continues without disruption.

(there is a possible additional issue in the existing implementation of `oauthutil.OnExpiry()` - it uses the expiry timestamp from the token, while the expiry check that is done inside `ts.token.Valid()` uses a 10-second expiry delta to account for client-server time mismatches.  The same 10-second expiry delta should likely be included in `OnExpiry` as well - but as that would affect other backends, and still not give enough time for the Box JWT refresh, I left as-is for now).

My Go skills are a little rusty, so happy to tweak if you see a more elegant way to accomplish this! As long as my sync runs without errors overnight, this should be ready for review.

**Comment by ndrarmstrong** [comment]
My overnight test ran without issue, refreshing the token prior to expiry and running to completion. I fixed the linting issue on the PR and re-pushed; and marked it as ready for review.

**Comment by ndrarmstrong** [comment]
2-month update: this patch has been running without issue in our environment for the past couple months. We've had many jobs run past the 1-hour mark without issue, and no further failures due to token expiry.

@ncw Is there anything further you need on this? Happy to tweak if you have any comments or would prefer a different approach.

**Comment by ndrarmstrong** [comment]
This continues to work great in our environment - the Box OAuth2 with JWT credentials work indefinitely, with automatic renewals shortly before the old ones expire.

@ncw I would love to see get this merged. The MR is ready for review and works well in my testing - is there anything else I can do to assist?

**Comment by kylepinecroft** [comment]
I am running into this issue still 3 years later. Can this be merged?
