### ISSUE TITLE
onedrive: Authorization header should not be included in PUT request for multipart upload

### ISSUE THREAD

**Issue by chscott** [rclone/rclone#7405]
#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/onedrive-unauthenticated-when-trying-to-copy-sync-but-can-use-lsd/41149/27?u=chscott

#### What is the problem you are having with rclone?

Unable to copy files from one OneDrive remote to another.

#### What is your rclone version (output from `rclone version`)

`1.65.0`

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Windows, 64-bit

#### Which cloud storage system are you using? (e.g. Google Drive)

OneDrive -> OneDrive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

`rclone copy source: target:`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

Details in forum posting.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by cetteup** [comment]
I followed the code path once to see if there's any easy way to fix it.

The `PUT` request for the multipart upload is triggered here.
https://github.com/rclone/rclone/blob/743ea6ac263895fb0091df140bbb6c4e2196e97f/backend/onedrive/onedrive.go#L2239-L2248

`o.fs.srv` is an http client which is generated here.
https://github.com/rclone/rclone/blob/743ea6ac263895fb0091df140bbb6c4e2196e97f/backend/onedrive/onedrive.go#L950-L966

`oauthutil.NewClient` internally calls `oauthutil.NewClientWithBaseClient`, which creates an `oauth2.NewClient` here.
https://github.com/rclone/rclone/blob/743ea6ac263895fb0091df140bbb6c4e2196e97f/lib/oauthutil/oauthutil.go#L410-L422

The `oauth2` package uses a `RoundTrip` which always calls

**Comment by ncw** [comment]
I wonder why this never fails in the integration tests? Maybe it needs very big files?

Anyway, @cetteup your idea of a unauthenticated client is easy to implement.

Please try this @chscott and @cetteup 

[v1.66.0-beta.7595.5841b1253.fix-7405-onedrive-upload](https://beta.rclone.org/branch/fix-7405-onedrive-upload/v1.66.0-beta.7595.5841b1253.fix-7405-onedrive-upload/) on branch [fix-7405-onedrive-upload](https://github.com/rclone/rclone/tree/fix-7405-onedrive-upload) (uploaded in 15-30 mins)

**Comment by cetteup** [comment]
I tested the fix with the same sync job that I first noticed the issue with. With the old v1.65.0, it only created folders in OneDrive, I did not see a single file being uploaded. With v1.66.0-beta.7595.5841b1253.fix-7405-onedrive-upload, it uploaded files successfully.

One thing to note: Both versions seem to have issues cancelling multipart uploads. v1.66.0-beta.7595.5841b1253.fix-7405-onedrive-upload logs
> Failed to cancel multipart upload: unauthenticated: Unauthenticated (upload failed due to: \<nil\>)

v1.65.0 logs
> Failed to cancel multipart upload: unauthenticated: Unauthenticated (upload failed due to: unauthenticated: Unauthenticated)

May be a topic for another issue though, I haven't looked into that one (yet).

**Comment by ncw** [comment]
> Thanks a lot for the fix! I tested it with the same sync job that I first noticed the issue with. With the old v1.65.0, it only created folders in OneDrive, I did not see a single file being uploaded. With v1.66.0-beta.7595.5841b1253.fix-7405-onedrive-upload, it uploaded files successfully.

Great - thank you for testing.

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.66 and v1.65.1
 
> Regarding the file size: It failed for me with rather small files. I see the "Failed to copy: unauthenticated: Unauthenticated" errors for files as small as 10-20MB in the logs.

Hmm... Well onedrive is complicated and has lots of differently aged parts and systems joined together so I guess the fact that some bits behave differently to others is not surprising!

> One thing to note: Both versions seem to have issues cancelling multipart uploads. v1.66.0-beta.7595.5841b1253.fix-7405-onedrive-upload logs
> 
> > Failed to cancel multipart upload: unauthenticated: Unauthenticated (upload failed due to: <nil>)
> 
> v1.65.0 logs
> 
> > Failed to cancel multipart upload: unauthenticated: Unauthenticated (upload failed due to: unauthenticated: Unauthenticated)
> 
> May be a topic for another issue though, I haven't looked into that one (yet).

Can you make another issue for this please? I want to merge this and get it into the point release which is out in a day or so so another issue would be appropriate - thank you!

**Comment by raspher** [comment]
```
rclone v1.66.0
- os/version: arch rolling (64 bit)
- os/kernel: 6.6.33-1-lts (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.22.1
- go/linking: dynamic
- go/tags: none
```

OneDrive Personal

I've tried to `rclone configure` and refresh token, but that didn't work. I was able to list files, delete file but couldn't open/read file. Mount works too but without reading files.

**Comment by victorviana3** [comment]
It remained a error when needed to cancel the upload.

2024/12/28 10:04:23 NOTICE: haos/haos_ova-14.0.qcow2: Failed to cancel multipart upload: unauthenticated: Unauthenticated (upload failed due to: Put "https://my.microsoftpersonalcontent.com/personal/447b5ac1be1baeee/_api/v2.0/drives/(...)": can't copy - source file is being updated (mod time changed from 2024-12-28 10:03:52.254849716 -0300 -03 to 2024-12-28 10:04:19.911864003 -0300 -03))

**Comment by FernandoRD** [comment]
Hi everybody, reached this thread googling for an answer...
Having similar issue here, but with different circunstancies, in my case I trying to configure in truenas. And also I have a different case, I use two accounts, one is mine. the other belongs to my wife. So, my account, thats linked to a @hotmail.com account works flawlessly, but my wife's account linked to @outlook.com, gives this error. 

So the differences between the accounts are:
1 - the liked e-mail, one is @hotmail.com, the other is @outlook.com
2 - My account is the "Master" account and my wife's account is "family member" that was invited
3 - At the creation of the "cloud account" in TrueNas, mine shows only one drive to connect, and my wife's shows four, beeing 2 different repeated 2 times each

I guess this 2 drivers could be the cause of the problem.... perhaps something related with the age of the account? Because mine is way much older... or could it be due to the association to @outllok.com?

As I still have 3 accounts left, i'm thinking in create another, associated with any other e-mail and see what happens...

**Comment by anvuongb** [comment]
Hi all, I came across this thread when searching for solutions to a similar problems. My rclone OneDrive is acting up. I can mount the drive and list files, but any read/write results in **ERROR : IO error: unauthenticated: Unauthenticated**

I have tried reconfig'd the drive, refresh tokens, update rclone to latest version 1.69, but still the same problem. FWIW my Google drive mount is working fine, so I guess this is specific to OneDrive? MSFT changed something in the backend?

**Comment by diblaze** [comment]
@anvuongb I have the same issue starting from 1 week ago with my private OneDrive. 
However, Business OneDrive works fine. 

Tried reconfig, refreshed tokens, already on latest rclone.

**Comment by anvuongb** [comment]
@diblaze I don't know what's changed but it is now working for me too, I haven't changed anything since last time. Weird.

**Comment by tdtgit** [comment]
> I wonder why this never fails in the integration tests? Maybe it needs very big files?
> 
> Anyway, [@cetteup](https://github.com/cetteup) your idea of a unauthenticated client is easy to implement.
> 
> Please try this [@chscott](https://github.com/chscott) and [@cetteup](https://github.com/cetteup)
> 
> [v1.66.0-beta.7595.5841b1253.fix-7405-onedrive-upload](https://beta.rclone.org/branch/fix-7405-onedrive-upload/v1.66.0-beta.7595.5841b1253.fix-7405-onedrive-upload/) on branch [fix-7405-onedrive-upload](https://github.com/rclone/rclone/tree/fix-7405-onedrive-upload) (uploaded in 15-30 mins)

Confirm this fixed my issue "Failed to copy: unauthenticated: Unauthenticated" although `lsd` is working fine.

**Comment by ncw** [comment]
@tdtgit this fix dedad9f071d81a2b6bf980d5f48d7997cae160af was released in rclone v1.66.0 so is in the current version v1.69.1

**Comment by MarkusKress** [comment]
I have also the problem with 
`Failed to cancel multipart upload: unauthenticated: Unauthenticated (upload failed due to: unauthenticated: Unauthenticated)`

I am using rclone with an paid accout from Microsoft 365 with 6x 1TB for OneDrive (1TB per user). It works since many years. But now , I don't know how long, I see this error. I found on the rclone site I am not the only one with the problem. I've updated to rclone v1.70.3 on debian, but it does not help. Adding the "--multi-thread-streams=0" works for me. It has nothing to do with big files. Even files with some bytes had the problem.

**Comment by ncw** [comment]
@MarkusKress please make a new issue with instructions on how to reproduce and link this issue and any forum threads - thank you

**Comment by Meikkun** [comment]
> I have also the problem with `Failed to cancel multipart upload: unauthenticated: Unauthenticated (upload failed due to: unauthenticated: Unauthenticated)`
> 
> I am using rclone with an paid accout from Microsoft 365 with 6x 1TB for OneDrive (1TB per user). It works since many years. But now , I don't know how long, I see this error. I found on the rclone site I am not the only one with the problem. I've updated to rclone v1.70.3 on debian, but it does not help. Adding the "--multi-thread-streams=0" works for me. It has nothing to do with big files. Even files with some bytes had the problem.

I'm having exactly this same issue. Also paid account.

**Comment by darthShadow** [comment]
As already said above, please make a new issue with instructions on how to reproduce and link this issue and any forum threads.
