### ISSUE TITLE
nfsmount — not functional on macOS for writing files to OneDrive via Finder

### ISSUE THREAD

**Issue by scuba-tech** [rclone/rclone#7503]
**Hello! I'm writing with an active issue that seems to affect `rclone nfsmount` on macOS.**

-----

#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/rclone-v1-65-0-release/43100/25?u=scuba-tech

#### What is the problem you are having with rclone?

**ALL** attempts to copy files of any size or type, from Finder into OneDrive, via `nfsmount` fail. 

It is not possible to write from Finder or save work. It *is* possible to read/open files.

Simple writing operations like `touch` and `cat > filename` from a shell do write properly into nfsmount.

-----

#### What is your rclone version (output from `rclone version`)

1.65.0 via brew

-----

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

**macOS Sonoma (14.1.1)** // ARM64

-----

#### Which cloud storage system are you using? (e.g. Google Drive)

Microsoft OneDrive (personal family // 6TB)

-----

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

`rclone nfsmount --vfs-cache-mode full --filter-from "/Users/<user>/.config/rclone/rclone-filter-rules.txt" OD: ~/MOUNT-OneDrive --verbose`

Notes:

1. I am using `--vfs-cache-mode full` to allow writing with OneDrive. Using none gives an (expected) read-only error message.
2. Here are the contents of my filter rules file:

```
- **/.DS_Store
- **/.hidden*
- **/._*
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
[ERROR] No file for lookup of ._GH010215.mp4
[ERROR] call to 0x106<###>  failed: No such file or directory
INFO  : SdT-Inboxes/GH010215.mp4: vfs cache: removed cache file as file deleted
[ERROR] No file for lookup of ._7F2A7976.JPG
[ERROR] call to 0x106<###>  failed: No such file or directory
[ERROR] err loading attrs for SdT-Inboxes/GH010215.mp4: file does not exist
[ERROR] No file for lookup of ._7F2A7977.JPG
[ERROR] call to 0x106<###>  failed: No such file or directory
[ERROR] err loading attrs for SdT-Inboxes/GH010215.mp4: file does not exist
```

<img width="684" alt="image" src="https://github.com/rclone/rclone/assets/35608185/9d2adedc-09e3-44e5-b4c5-bf5b91602585">

Confirming that the copy into the mount _did fail_, checking with Finder, `ls -hAls`, and even OneDrive webUI... all of these confirm that the file does **not** actually "already exist" as the error message above claims!

I hope this report helps with getting `nfsmount` sorted. :) 

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by scuba-tech** [comment]
Including a further --verbose excerpt for context as I believe it is related;  it appears that the filter rules are not respected.

```
NOTICE: NFS Server running at 127.0.0.1:55165
[ERROR] No file for lookup of ._.
[ERROR] call to 0x106<###> failed: No such file or directory
[ERROR] No file for lookup of .hidden
[ERROR] call to 0x106<###> failed: No such file or directory
[ERROR] No file for lookup of .DS_Store
[ERROR] call to 0x106<###> failed: No such file or directory
[...]
[ERROR] call to 0x106<###> failed: No such file or directory
[ERROR] No file for lookup of ._7F2A8214.JPG
[ERROR] call to 0x106<###> failed: No such file or directory
[ERROR] No file for lookup of ._7F2A8215.JPG
[ERROR] call to 0x106<###> failed: No such file or directory
[ERROR] No file for lookup of ._7F2A8196.JPG
[ERROR] call to 0x106<###> failed: No such file or directory
[ERROR] No file for lookup of ._7F2A8216.JPG
[ERROR] call to 0x106<###> failed: No such file or directory
[ERROR] No file for lookup of ._7F2A8197.JPG

[repeat approx 7200x times]
```

**Comment by maof97** [comment]
+1 I have the exact same issue. @scuba-tech did you figure it out?

**Comment by scuba-tech** [comment]
> +1 I have the exact same issue. @scuba-tech did you figure it out?

Negative. Presently, this command is non-functional for me. There is no solution that I have found.

**Comment by maof97** [comment]
Bummer. I guess I will use Mountain Duck now (sadly not Open Source tho)

**Comment by scuba-tech** [comment]
> Bummer. I guess I will use Mountain Duck now (sadly not Open Source tho)

I will look at _Mountain Duck_, thank you for the suggestion. As much as we may love open source and libre software, sometimes one simply needs things to work!! 

(I'll edit this portion of my comment once I can confirm if Mountain Duck is able to reliably mount my OneDrive partition.)

I will also keep an eye on this thread and am happy to help the developers with any further troubleshooting or testing. 
I would even be happy to send a Mac Mini (or give them 24/7 VNC+Parsec+SSH access with root) to any *active* `rclone` developers who wish to have a Mac as a dev/testing target... that is how much I love this project and want to give back!

**Comment by kapitainsky** [comment]
@ncw - does `nfsmount` has a maintainer? As it is now this feature is not usable at all. At least on macOS. Its existence in released rclone version creates only confusion.

**Comment by nielash** [comment]
I took a brief look at this. The following changes seem to have fixed this particular issue for me: https://github.com/nielash/rclone/commit/07818424265e67cda7df0db2b80f3f64e352b7f2 (Sonoma 14.2.1 / Apple M1 Ultra)

However I'm not very familiar with this part of the codebase, and it is possible that I'm not fully understanding all the consequences.

Also while debugging this I noticed some encoding issues that probably should be fixed (not addressed by these changes).

**Comment by kapitainsky** [comment]
Nice that fixing writes is possible.

Another old issue is NFC/NFD drama on macOS. I suspect that `nsfmount` does not fix it neither.

https://github.com/rclone/rclone/issues/7072

**Comment by kapitainsky** [comment]
I have tried https://github.com/nielash/rclone/commit/07818424265e67cda7df0db2b80f3f64e352b7f2 and indeed now I can write files to nfs mount.

However NFC/NFD problem is still there:

<img width="846" alt="image" src="https://github.com/rclone/rclone/assets/15635386/1c7a761c-f885-4e44-a488-69bb85903f84">

mount was never fully working on macOS. Maybe a lot of people do not even realise because they mostly use nice names without any problematic characters:) But it is massive issue for users in Asia for example.

**Comment by nielash** [comment]
Yes, those are the kinds of encoding issues I was noticing. Great writeup on #7072. Is anyone working on that?

**Comment by kapitainsky** [comment]
> Yes, those are the kinds of encoding issues I was noticing. Great writeup on #7072. Is anyone working on that?

I hope @ncw has it on his radar?:) Unfortunately it is beyond my programming skills so I can only test and complain:)

**Comment by nielash** [comment]
Hi @kapitainsky, continuing our discussion from #7072 about `nfsmount` fixes here. I think I fixed the two issues you mentioned (`--volname` and hanging after external unmount). If you have a chance, let me know if this fixes it for you? https://github.com/nielash/rclone/tree/nfsmount-fixes

One weird thing about `--volname` is that Finder shows the correct name in most places:

![Screenshot 2024-02-08 at 1 06 36 AM](https://github.com/rclone/rclone/assets/31582349/ae7fc58d-8859-4dcf-973f-1aa5672091e2)

except the sidebar, which still shows "localhost". It seems like that is just a limitation of `mount_nfs` https://apple.stackexchange.com/a/188068 But let me know if you know any cool tricks for that.

**Comment by kapitainsky** [comment]
Will test today.

> except the sidebar, which still shows "localhost". It seems like that is just a limitation of `mount_nfs` https://apple.stackexchange.com/a/188068 But let me know if you know any cool tricks for that.

Then it is similar to FUSE-T (which also uses nfs server):

<img width="347" alt="image" src="https://github.com/rclone/rclone/assets/15635386/f8c2b852-4cfc-44b1-b622-df7622a155e2">

I think sidebar show server name which is different to share name. Maybe there is a way to give it is own name? E.g. `nfsshare`?

**Comment by kapitainsky** [comment]
> If you have a chance, let me know if this fixes it for you? https://github.com/nielash/rclone/tree/nfsmount-fixes

I have compiled it already and all looks good. `volname` works and when unmounted  `rclone nfsmount` terminates. I will keep using it now to see if anything else is missing.

**Comment by nielash** [comment]
> I think sidebar shows server name which is different to share name. Maybe there is a way to give it is own name? E.g. `nfsshare`?

Under the hood, `nfsmount` is just running the standard `mount` command, like:

```
mount -o port=xxxxx -o mountport=xxxxx localhost:volname /Users/username/path/to/mount
```

**Comment by nielash** [comment]
> Shame that it is not open source so we can't have a look how it is done

Agreed.

**Comment by kapitainsky** [comment]
fixed `rclone nfsmount` is not using NFD normalisation yet? correct?

**Comment by nielash** [comment]
> fixed `rclone nfsmount` is not using NFD normalisation yet? correct?

Correct. But you could just clone and cherry-pick https://github.com/rclone/rclone/pull/7620/commits/90dbe8b93f05dab7dc2fd6ecdca9aa8f972124ee and it should work... 

I opened the PR for that, btw #7620

**Comment by kapitainsky** [comment]
I have noticed something weird. When used with polling remote like onedrive.

When I delete 2 files from the remote directly - only one file is removed from `nsfmount`. Like polling changes are not fully processed?

**Comment by nielash** [comment]
That is odd. Was that the case before too? Or did my changes break something?

**Comment by kapitainsky** [comment]
For a moment ignore - maybe false alarm... I am trying to reproduce it now with `-vv` to have some data. But all works:) Maybe need another coffee before I proceed.

**Comment by kapitainsky** [comment]
Can we pass extra flags to `mount -o port=xxxxx -o mountport=xxxxx localhost:volname /Users/username/path/to/mount
`?

In similar way how fuse-t allows it? e.g.:

`rclone mount remote: mountpoint -o nfc -o noatime`

**Comment by kapitainsky** [comment]
> > …
> > So what fuse-t does is renaming `localhost` to `fuse-t`. Shame that it is not open source so we can't have a look how it is done
> 
> The fuse-t installer adds `127.0.0.1 fuse-t` to `/etc/hosts`, which would allow it to specify `fuse-t` (as an alias for `localhost`) for the server name in its mount command.

Good find. It would be problematic on the fly though as it requires sudo... 

but we could add this to docs as a hint how to customise all `nfsmount` mounting

**Comment by kapitainsky** [comment]
@manselmi any chance you can try https://github.com/nielash/rclone/tree/nfsmount-fixes as well?

Maybe this time we can avoid releasing crippled feature - which was the case with original `nsfmount`. At least on macOS

**Comment by manselmi** [comment]
> @manselmi any chance you can try https://github.com/nielash/rclone/tree/nfsmount-fixes as well? It requires build it from source though.
> 
> Maybe this time we can avoid releasing crippled feature - which was the case with original `nsfmount`. At least on macOS

@kapitainsky I'm not sure what kind of testing you had in mind, so I compiled the branch from source like this:

``` shell
go build -trimpath -ldflags "-s -X github.com/rclone/rclone/fs.Version=v9.9.9-test"
```

I then mounted my OneDrive remote and tried `touch`ing a new file into existence, which worked (it appeared in OneDrive) but took over 60 seconds to complete for some reason.  I then added some text to the file locally, and this time it quickly synced to OneDrive.  👍

**Comment by kapitainsky** [comment]
Great. And thank you. 

Simply by trying to use it you have a chance to notice something not working.
