### ISSUE TITLE
Excess memory use when syncing millions of files in one directory

### ISSUE THREAD

**Issue by zackees** [rclone/rclone#7974]
## Background - Amazon S3 rclone problems

I'm trying to backup a datalake with 100 million files at the root. They are mostly small files < 1mb.

rclone was simply not designed for this use case and will eat up all available memory and then crash. There was no machine instance that I could throw at it that would fix this issue. Even running locally in a docker instance would eat up all available memory and then crash.

All advice in the forums did nothing to help the situation. And a lot of people seem to be running into this. Therefore I wanted to post this here so that anyone searching for this problem can try our solution.

## Solution in a nutshell: PUT YOUR FILES INTO FOLDERS!!!!

What's interesting is the behavior: rclone would never start transferring files, it would always sit there saying 0 files transferred, 0 bytes transferred, eat up all available memory before crashing with an OOM.

I tried all the suggestions in the forums, reducing the buffering memory, reducing the number of checkers and transfers. Nothing worked.

## Cause & Fix

Without looking at the code or doing any profiling, my hypothesis was that rclone scans an all files in a"directory" into RAM before executing on it. This seems true whether not `--fast-scan` is used or not.

Obviously, having 100 million files at the root was causing our org a whole bunch of problems anyway and it's been something that I've wanted to fix for a while, so this problem gave me enough reason to go ahead and re-organize our entire datalakes.

Since each file is referenced in our database with a datestamp, I was able to write python scripts that would move these files from the root into folders by the service and year-month (for example name.html -> service/2023-04/name.html)

This worked extremely well and I was able to now run rclone and have it at least start transferring some files. However, there were still folders with 5+ million files, and eventually ran into the same out-of-memory error.

So again, I further re-organized the files in our datalake into service/yrmo/day. And now that seems to have done the trick. rclone now consistently runs under 2GB memory and I've been able to increase the number of transfers and checkers up to 100 each and have 3mb of buffer per transfer.

## Dead ends

All the advice about adjust memory buffers and number of transfers is mostly wrong. They will only cut your minimum memory usage by a constant factor, but will do very little to prevent the absolute unbounded memory that rclone uses for extremely large "directories".

If you have this same problem, no amount of setting tweaking will work... you MUST re-organize your data into folders or rclone will just run out of memory every single time. If you have too many files at the root, rclone will simply never start transferring anything and just crash. If one of your subdirectories is too big, you'll get a memory pattern that looks like this:

![image](https://github.com/user-attachments/assets/cad7926e-48b7-46f7-be81-543edc896460)

## Recommendations to the Devs of rclone

Please serialize your directory scans to disk if you start exceeding a certain threshold of memory or files in the current directory. You can probably just get away with just always doing that since the disk is so much faster than network anyway. I'm currently doing an inventory scan of our datalakes and 50 million files entries is only taking up 12 gb of disk without any fancy compression. I know you are storing a lot more file information, like metadata, so it could easily be double or triple that.

But it is simply so much easier and cheaper to allocate disk space to a docker instance than it is to get a machine with much more ram.

An additional pain point about an out of memory issue crash is that when the rclone process gets a kill signal, it will **exit 0** making it look like it succeeded. According to this thread https://github.com/rclone/rclone/issues/7966 this is a feature of linux and you must get the exit code from the operating system instead of the return value of the exited rclone process.

This is super scary if you are relying on rclone to backup your datalake but in reality, it starts failing because one of your directories has millions of files in it. I know on Digital Ocean it's easy to see that a docker instance has failed, on Render.com however you'll get a "Run Succeeded" and it's not until you look at the run history that you'll see that in fact your instance ran out of memory. I'm not sure about the other hosting providers.

Anyway, I'm glad this huge task is finally over with, and we have started syncing up our data for redundancy and backup purposes. So far so good!

![image](https://github.com/user-attachments/assets/5c2b7096-ade2-45d7-993e-4fd0b0f52196)

**Comment by ncw** [comment]
I'll just note that this is mentioned in the FAQ https://rclone.org/faq/#rclone-is-using-too-much-memory-or-appears-to-have-a-memory-leak

And also that I'm scheduled to implement an out of memory sync later this year which will fix the problem properly.

**Comment by msays2000** [comment]
@zackees very articulate post, thank you for raising the large scale experiment issue.

**Comment by ncw** [comment]
I forgot to say there is a workaround for this written up in the wiki

- https://github.com/rclone/rclone/wiki/Big-syncs-with-millions-of-files

Which came from this forum post originally

- https://forum.rclone.org/t/rclone-sync-s3-to-s3-runs-for-hours-and-copy-nothing/39687/23

It isn't the best solution, but it will work until the out of memory sync is in.

**Comment by prasathsekar** [comment]
@ncw is there any workround for this issue. Because I have 50 million objects in single directory. Also I tried the way of sorting it. Almost I have waited for 2 hours, still the sorting is not completed.

**Comment by guysoft** [comment]
> I forgot to say there is a workaround for this written up in the wiki
> 
>     * https://github.com/rclone/rclone/wiki/Big-syncs-with-millions-of-files
> 
> 
> Which came from this forum post originally
> 
>     * https://forum.rclone.org/t/rclone-sync-s3-to-s3-runs-for-hours-and-copy-nothing/39687/23
> 
> 
> It isn't the best solution, but it will work until the out of memory sync is in.

Is there a way to make that solution take in to account changed files? Not sure if there is a quick way to do that

**Comment by ncw** [comment]
If anyone would like to try the solution to this, here is rclone with an out of memory sync for directories with lots of entries. This should fix the memory usage problems.

Testing appreciated :-)

[v1.69.0-beta.8480.59a5530ce.fix-7974-out-of-memory-sync](https://beta.rclone.org/branch/fix-7974-out-of-memory-sync/v1.69.0-beta.8480.59a5530ce.fix-7974-out-of-memory-sync/) on branch [fix-7974-out-of-memory-sync](https://github.com/rclone/rclone/tree/fix-7974-out-of-memory-sync) (uploaded in 15-30 mins)

**Comment by arfbarky** [comment]
I'm having a out of memory issue also though it's not such an extreme case but it behaves the same as this bug...

I have a mini PC, Intel N95, 8gb RAM, running Debian 12. Trying to sync a directory of 1305 files (largest is 4gb, most are less than 1gb) to Backblaze.

In top I see it immediately start grabbing more and more memory until it gets to 100% and the kernel kills it; takes less than a minute.

I tried the version just posted above, didn't help. Is this the same bug or is this something else?

**Comment by mNantern** [comment]
I just tried this new version and it's working perfectly. The sync has been running for almost 2 hours and it has replicated 850k / 5M without an issue.

With the version v1.69 it was always crashing on OOM. 👏

**Comment by zackees** [comment]
Thanks, ill try this this week, i have exactly this problem

**Comment by mNantern** [comment]
I made more tests today but unfortunately the OOM is still happening on a bigger bucket. It takes more time now but after a while the memory usage go from 3G to 30G quickly

**Comment by ncw** [comment]
@mNantern I noticed that once in my testing but I didn't manage to replicate it. How many files of what size did you have?

**Comment by zackees** [comment]
@ncw I'm going to start testing this hardcore on monday. Right now I'm using 16GB and 32GB instances for some of the large datalakes that I'm copying. Do you have a recommendation on the machine ram size? Should I do 2GB, 4GB or ?

Thanks.

**Comment by ncw** [comment]
@zackees in theory it shouldn't use more than 1 or 2 GB ever. However that hasn't been tested much yet so I'd appreciate hearing about your findings. If you can report number of items in the biggest directory that would be great too.

**Comment by guysoft** [comment]
Hey, running ``fix-7974-out-of-memory-sync`` branch on about 6 million files and so far did not pass 1.2GB of ram on a raspsberrpi. Will update when its done but it looks good!

**Comment by zackees** [comment]
Some of the workers are going filling up 100% of 4GB of memory.


This is the shell command that's being issued:

```
rclone --config rclone.conf sync 45062:zlib3_files dst:TorrentBooks/zlib3_files --checkers 1000 --timeout 20m --contimeout 2m --transfers 256 --low-level-retries 100 --progress --metadata --fast-list --max-backlog 10000 --size-only -vvvv --multi-thread-cutoff 32Mi 
--max-depth -1
````

![Image](https://github.com/user-attachments/assets/4c9d6bcb-10c2-421b-ae98-b4d819e9e384)


This confirms the version:

```
root@sync-0dir-aa-misc-data--1:~# rclone --version
rclone v1.69.0-beta.8480.59a5530ce.fix-7974-out-of-memory-sync
- os/version: ubuntu 24.10 (64 bit)
- os/kernel: 6.11.0-9-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.23.4
- go/linking: static
- go/tags: none
root@sync-0dir-aa-misc-data--1:~# 
```

**Comment by ncw** [comment]
@zackees thanks for the info. It would be useful to know what the distribution of files is in the source bucket. So roughly how many files and how big?

I note --transfers 256 and --multi-thread-cutoff 32Mi ? These can potentially be using lots of RAM if you have lots of larger files, potentially --s3-upload-concurrency * --s3-chunk-size * --transfers so 5 GB with those settings.

**Comment by zackees** [comment]
The distribution here is WILD. Some files are a few megabytes, some are 300 GB+

Thanks for pointing out `--s3-upload-concurrency`

I'm a bit confused on whether this overlaps with `--multi*` threaded mode for the file transfers.

If you can clarify this for me then I'll update your docs.

So bear with me:

I have a large distribution of files sizes. I'd like to be able to have as many threads as possible, obviously. But if I oversaturate then connections start being reset and that's bad.

so...

Does `--s3-upload-concurrency` cap the number of total connections to the s3 bucket?

So for example let's say I have `--transfers N` and I also have  `--multi-thread-streams M`. In the degenerate case this will produce N*M uploading threads.

What I'm hoping is that `--s3-upload-concurrency` caps it. So so `--s3-upload-concurrency X` would yield that:

  * `--transfers N` + `--multi-thread-streams M` <= `--s3-upload-concurrency X`
  * N + M <= X

I this true? This forum post here was the closest answer I got:

https://forum.rclone.org/t/s3-concurrency-multi-thread-streams-vs-s3-upload-concurrency/34191


If so this would be great as I can simply do all the uploading for all files in one pass instead of small/big pass.

**Comment by guysoft** [comment]
Ok, fix-7974-out-of-memory-sync branch actually fixes the issue for me. Is there a PR @ncw ?

**Comment by ncw** [comment]
@zackees wrote:
> The distribution here is WILD. Some files are a few megabytes, some are 300 GB+

OK
 
> Thanks for pointing out `--s3-upload-concurrency`
> 
> I'm a bit confused on whether this overlaps with `--multi*` threaded mode for the file transfers.
> 
> If you can clarify this for me then I'll update your docs.

It is super confusing and something that I'd like to fix.

There is discussion of how the options actually work and how we'd like them to work here https://github.com/rclone/rclone/issues/8225

> I have a large distribution of files sizes. I'd like to be able to have as many threads as possible, obviously. But if I oversaturate then connections start being reset and that's bad.
> 
> so...
> 
> Does `--s3-upload-concurrency` cap the number of total connections to the s3 bucket?

No it doesn't and that is a potential problem.

However I've been working on a fix for that which adds a single flag

      --max-buffer-memory SizeSuffix   If set, don't allocate more than this amount of memory as buffers (default off)

Somewhat WIP but you can try it here.

[v1.70.0-beta.8603.7dfc93cfe.fix-max-buffer-memory](https://beta.rclone.org/branch/fix-max-buffer-memory/v1.70.0-beta.8603.7dfc93cfe.fix-max-buffer-memory/) on branch [fix-max-buffer-memory](https://github.com/rclone/rclone/tree/fix-max-buffer-memory) (uploaded in 15-30 mins)

You might find that is actually the correct fix for your problem rather than this issue which is specifically for directories will millions of files in.

**Comment by nneul** [comment]
The fix-7974-out-of-memory-sync branch (for the large dir) made a huge difference in my testing, would love to see it get merged.

**Comment by patrice-go-dsi** [comment]
The fix-7974-out-of-memory-sync branch : How to express the value of the flag --max-buffer-memory SizeSuffix ? 

--max-buffer-memory 16M ?

**Comment by kapitainsky** [comment]
> SizeSuffix ?

https://rclone.org/docs/#size-option

**Comment by patrice-go-dsi** [comment]
> > SizeSuffix ?
> 
> https://rclone.org/docs/#size-option

Tx !

**Comment by nneul** [comment]
Any update on when this fix might make it into actual release?

**Comment by patrice-go-dsi** [comment]
I have always the out of memory error with rclone sync to a google drive shared directory : Only 4 files (81Mo and 134K) !

**Comment by ncw** [comment]
Thanks for testing everyone.

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.70

**Comment by ZigHuang** [comment]
Glad to see this change!
~~What I want to know is, does this `list_cutoff` optimization also work on the rclone `copy` command?
I also encountered the above **excess memory use problem** when rclone `copy` millions of small files in the one directory~~
I checked the code and found that `list-cutoff` should be executed as a default behavior of list and is expected to work in rclone `copy` 👍

**Comment by timucinsolus** [comment]
While this change fixed the memory issue, the whole transfer and check process is significantly slower now (which is to be expected, probably). Only checking the source and destination for change using checksum for 8 million objects takes 8+ hours and is still running.

 However, I noticed something else. Let’s say I have 8 million objects on the source and 6 million on the destination. When I run the rclone sync with the --progress flag,  it shows the listed object count. When it ends counting every object, it stops listing and starts running the sync. But after a while (acouple of hours), it creates a new file in the /tmp directory, and listing starts all over again. The list output from the progress is going up again for some time and stops after the number doubles.

The sync process is still running for more than 8 hours, and it doesn’t seem like it will end anytime soon.
